"""Per-harness plugin delivery adapters (implementation note S3).

Cycle-free module: both ``install`` and ``activation`` import from here;
neither imports the other's privates for harness dispatch.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal, Protocol

import tomlkit
import yaml

from workstate_protocol import RUNTIME_ROOT_DIRNAME

PLUGIN_NAME = "workstate-system"
PLUGIN_MARKETPLACE_NAME = "workstate-marketplace"
PLUGIN_OWNER_NAME = "workstate maintainers"
PLUGIN_DESCRIPTION = (
    "Cross-harness workstate-system plugin: portable workflow skills "
    "(SKILL.md) plus uvx-stdio MCP servers (workstate-handoff-mcp, "
    "workstate-orchestrator-mcp)."
)
PLUGIN_GENERATED_ROOT: tuple[str, ...] = (
    RUNTIME_ROOT_DIRNAME,
    "generated",
    "plugins",
    PLUGIN_NAME,
)
PLUGIN_SELECTOR = f"{PLUGIN_NAME}@{PLUGIN_MARKETPLACE_NAME}"

CLAUDE_MARKETPLACE_PATH = Path(".claude-plugin") / "marketplace.json"
CLAUDE_SETTINGS_PATH = Path(".claude") / "settings.json"
CODEX_MARKETPLACE_PATH = Path(".agents") / "plugins" / "marketplace.json"
CODEX_CONFIG_PATH = Path(".codex") / "config.toml"
CURSOR_COMMANDS_DEST = Path(".cursor") / "commands"
CURSOR_HOOKS_PATH = Path(".cursor") / "hooks.json"
CURSOR_SETTINGS_PATH = Path(".cursor") / "settings.json"
CURSOR_SKILLS_DEST = Path(".cursor") / "skills"
CURSOR_GENERATOR_TAG = (
    "<!-- GENERATED by scripts/generate_agent_workflows.py; do not edit by hand. -->\n"
)
CURSOR_SKILLS_ONLY_MARKER = ".native-skills-only"
GROK_PLUGIN_DEST = Path(".grok") / "plugins" / PLUGIN_NAME

WORKSTATE_SYSTEM_SUBDIR = "packages/workstate-system"
WORKSTATE_SYSTEM_PAYLOAD_SUBDIR = "packages/workstate-system/workstate_system/payload"
HARNESS_PROTOCOL_REL = Path("docs/workstate/contracts/harness-protocol.yaml")

GROK_BARE_SELECTOR = PLUGIN_NAME
STALE_DISCOVERY_SELECTOR_RE = re.compile(
    rf"^project/[0-9a-f]+/{re.escape(PLUGIN_NAME)}$"
)
GROK_CLI_TIMEOUT_SECONDS = 120
# `grok plugin install` keys its registry by content hash and exits non-zero
# with this marker when that exact hash is already registered (a re-run with
# unchanged plugin content). Treated as idempotent success, not a failure.
GROK_ALREADY_INSTALLED_MARKER = "already installed"


@dataclass(frozen=True)
class HarnessContext:
    """Runtime context passed to harness adapter methods."""

    target: Path
    clone: Path
    plugin_tree_kind: str = "effective"
    override_root: Path | None = None


def resolve_in_clone(clone: Path, relpath: str) -> Path:
    """Resolve a surface/asset path against the clone or package root."""
    from workstate_bootstrap.surfaces import clone_layout_probe_roots

    payload_root, nested_root, clone_root = clone_layout_probe_roots(clone)
    payload = payload_root / relpath
    if payload.exists():
        return payload
    nested = nested_root / relpath
    if nested.exists():
        return nested
    root = clone_root / relpath
    if root.exists():
        return root
    return payload


def plugin_tree_out(target: Path, kind: str) -> Path:
    from workstate_bootstrap.surfaces import plugin_tree_out as _plugin_tree_out

    return _plugin_tree_out(target, kind)


def relative_plugin_tree_path(kind: str, harness: str) -> str:
    from workstate_bootstrap.surfaces import relative_plugin_tree_path as _relative

    return _relative(kind, harness)


def load_harness_protocol(clone: Path) -> dict[str, Any]:
    path = resolve_in_clone(clone, HARNESS_PROTOCOL_REL.as_posix())
    if not path.is_file():
        return {}
    payload = yaml.safe_load(path.read_text())
    return payload if isinstance(payload, dict) else {}


def plugin_activation_row(clone: Path, harness_key: str) -> dict[str, Any] | None:
    protocol = load_harness_protocol(clone)
    capabilities = protocol.get("harness_capabilities") or {}
    block = capabilities.get("plugin_activation") or {}
    rows = block.get("rows") or []
    for row in rows:
        if isinstance(row, dict) and row.get("harness_key") == harness_key:
            return row
    return None


class HarnessAdapter(Protocol):
    key: str
    tree_dir_name: str
    activation_kind: str
    activation_path: Path

    def marketplace_paths(self) -> tuple[str, ...]: ...
    def materialized_paths(self) -> tuple[str, ...]: ...
    def plugin_tree_dir(self, ctx: HarnessContext, kind: str) -> Path: ...
    def pin_surfaces(
        self, ctx: HarnessContext, *, write_json: Any, deep_merge: Any
    ) -> list[dict[str, str]]: ...
    def activation_step(self, ctx: HarnessContext) -> dict[str, str]: ...
    def materialization(
        self, ctx: HarnessContext
    ) -> tuple[dict[str, str], dict[str, str]] | None: ...


@dataclass(frozen=True)
class ClaudeHarnessAdapter:
    key: str = "claude-code"
    tree_dir_name: str = "claude"
    activation_kind: str = "claude_plugin_activation"
    activation_path: Path = CLAUDE_SETTINGS_PATH

    def marketplace_paths(self) -> tuple[str, ...]:
        return (CLAUDE_MARKETPLACE_PATH.as_posix(),)

    def materialized_paths(self) -> tuple[str, ...]:
        return ()

    def plugin_tree_dir(self, ctx: HarnessContext, kind: str) -> Path:
        return plugin_tree_out(ctx.target, kind) / self.tree_dir_name

    def pin_surfaces(
        self, ctx: HarnessContext, *, write_json: Any, deep_merge: Any
    ) -> list[dict[str, str]]:
        from workstate_bootstrap.claude_settings import (
            claude_generator_available,
            write_wholesale_claude_settings,
        )

        claude_marketplace = {
            "name": PLUGIN_MARKETPLACE_NAME,
            "owner": {"name": PLUGIN_OWNER_NAME},
            "plugins": [
                {
                    "name": PLUGIN_NAME,
                    "source": relative_plugin_tree_path(
                        ctx.plugin_tree_kind, self.tree_dir_name
                    ),
                    "description": PLUGIN_DESCRIPTION,
                }
            ],
        }
        entries = [
            write_json(
                ctx.target / CLAUDE_MARKETPLACE_PATH,
                claude_marketplace,
                manifest_path=CLAUDE_MARKETPLACE_PATH.as_posix(),
            ),
        ]
        if claude_generator_available(ctx.clone):
            entries.extend(
                write_wholesale_claude_settings(
                    ctx.target,
                    ctx.clone,
                    override_root=ctx.override_root,
                    write_json=write_json,
                )
            )
        else:
            # Clone-less pin (write_plugin_pins(target, None) -> clone or
            # target): no overlay generator to render managed settings from, so
            # skip the wholesale write rather than crash the whole pin pass.
            entries.append(
                {
                    "path": CLAUDE_SETTINGS_PATH.as_posix(),
                    "action": "skipped_no_contract",
                    "kind": "claude_settings",
                }
            )
        return entries

    def activation_step(self, ctx: HarnessContext) -> dict[str, str]:
        if plugin_activation_row(ctx.clone, self.key) is None:
            return {
                "path": self.activation_path.as_posix(),
                "action": "skipped_no_contract",
                "kind": self.activation_kind,
            }
        settings_path = ctx.target / CLAUDE_SETTINGS_PATH
        if not settings_path.is_file():
            return {
                "path": CLAUDE_SETTINGS_PATH.as_posix(),
                "action": "failed",
                "kind": self.activation_kind,
            }
        try:
            payload = json.loads(settings_path.read_text())
        except json.JSONDecodeError:
            return {
                "path": CLAUDE_SETTINGS_PATH.as_posix(),
                "action": "failed",
                "kind": self.activation_kind,
            }
        enabled = payload.get("enabledPlugins")
        if not isinstance(enabled, dict) or not enabled.get(PLUGIN_SELECTOR):
            return {
                "path": CLAUDE_SETTINGS_PATH.as_posix(),
                "action": "failed",
                "kind": self.activation_kind,
            }
        return {
            "path": CLAUDE_SETTINGS_PATH.as_posix(),
            "action": "applied",
            "kind": self.activation_kind,
        }

    def materialization(
        self, ctx: HarnessContext
    ) -> tuple[dict[str, str], dict[str, str]] | None:
        return None


@dataclass(frozen=True)
class CodexHarnessAdapter:
    key: str = "codex"
    tree_dir_name: str = "codex"
    activation_kind: str = "codex_plugin_activation"
    activation_path: Path = CODEX_CONFIG_PATH

    def marketplace_paths(self) -> tuple[str, ...]:
        return (CODEX_MARKETPLACE_PATH.as_posix(),)

    def materialized_paths(self) -> tuple[str, ...]:
        return ()

    def plugin_tree_dir(self, ctx: HarnessContext, kind: str) -> Path:
        return plugin_tree_out(ctx.target, kind) / self.tree_dir_name

    def pin_surfaces(
        self, ctx: HarnessContext, *, write_json: Any, deep_merge: Any
    ) -> list[dict[str, str]]:
        codex_marketplace = {
            "name": PLUGIN_MARKETPLACE_NAME,
            "interface": {"displayName": "Workstate Marketplace"},
            "owner": {"name": PLUGIN_OWNER_NAME},
            "plugins": [
                {
                    "name": PLUGIN_NAME,
                    "source": {
                        "source": "local",
                        "path": relative_plugin_tree_path(
                            ctx.plugin_tree_kind, self.tree_dir_name
                        ),
                    },
                    "policy": {
                        "installation": "AVAILABLE",
                        "authentication": "ON_INSTALL",
                    },
                    "category": "Productivity",
                    "description": PLUGIN_DESCRIPTION,
                }
            ],
        }
        return [
            write_json(
                ctx.target / CODEX_MARKETPLACE_PATH,
                codex_marketplace,
                manifest_path=CODEX_MARKETPLACE_PATH.as_posix(),
            ),
        ]

    def activation_step(self, ctx: HarnessContext) -> dict[str, str]:
        if plugin_activation_row(ctx.clone, self.key) is None:
            return {
                "path": self.activation_path.as_posix(),
                "action": "skipped_no_contract",
                "kind": self.activation_kind,
            }
        entry = write_codex_plugin_activation_config(ctx.target)
        action = entry.get("action", "merged")
        if action == "unchanged":
            action = "applied"
        elif action in {"created", "merged", "updated"}:
            action = "applied"
        return {
            "path": CODEX_CONFIG_PATH.as_posix(),
            "action": action,
            "kind": self.activation_kind,
        }

    def materialization(
        self, ctx: HarnessContext
    ) -> tuple[dict[str, str], dict[str, str]] | None:
        return None


@dataclass(frozen=True)
class VscodeHarnessAdapter:
    key: str = "vscode"
    tree_dir_name: str = "vscode"
    activation_kind: str = "vscode_plugin_activation"
    activation_path: Path = Path(".vscode") / "mcp.json"

    def marketplace_paths(self) -> tuple[str, ...]:
        return ()

    def materialized_paths(self) -> tuple[str, ...]:
        return ()

    def plugin_tree_dir(self, ctx: HarnessContext, kind: str) -> Path:
        return plugin_tree_out(ctx.target, kind) / self.tree_dir_name

    def pin_surfaces(
        self, ctx: HarnessContext, *, write_json: Any, deep_merge: Any
    ) -> list[dict[str, str]]:
        return []

    def activation_step(self, ctx: HarnessContext) -> dict[str, str]:
        return {
            "path": self.activation_path.as_posix(),
            "action": "skipped_no_contract",
            "kind": self.activation_kind,
        }

    def materialization(
        self, ctx: HarnessContext
    ) -> tuple[dict[str, str], dict[str, str]] | None:
        return None


@dataclass(frozen=True)
class CursorHarnessAdapter:
    key: str = "cursor"
    tree_dir_name: str = "cursor"
    activation_kind: str = "cursor_native_surfaces_activation"
    activation_path: Path = Path(".cursor")

    def marketplace_paths(self) -> tuple[str, ...]:
        return ()

    def materialized_paths(self) -> tuple[str, ...]:
        return (CURSOR_HOOKS_PATH.as_posix(),)

    def plugin_tree_dir(self, ctx: HarnessContext, kind: str) -> Path:
        return plugin_tree_out(ctx.target, kind) / self.tree_dir_name

    def pin_surfaces(
        self, ctx: HarnessContext, *, write_json: Any, deep_merge: Any
    ) -> list[dict[str, str]]:
        return []

    def activation_step(self, ctx: HarnessContext) -> dict[str, str]:
        if plugin_activation_row(ctx.clone, self.key) is None:
            return {
                "path": self.activation_path.as_posix(),
                "action": "skipped_no_contract",
                "kind": self.activation_kind,
            }
        if _cursor_native_plugin_independent(ctx.target):
            required = (
                ctx.target / CURSOR_HOOKS_PATH,
                ctx.target / ".cursor" / "mcp.json",
            )
        else:
            required = (
                ctx.target / CURSOR_COMMANDS_DEST,
                ctx.target / CURSOR_SKILLS_DEST,
                ctx.target / CURSOR_HOOKS_PATH,
                ctx.target / ".cursor" / "mcp.json",
            )
        if all(path.exists() for path in required):
            return {
                "path": self.activation_path.as_posix(),
                "action": "applied",
                "kind": self.activation_kind,
            }
        return {
            "path": self.activation_path.as_posix(),
            "action": "failed",
            "kind": self.activation_kind,
        }

    def materialization(
        self, ctx: HarnessContext
    ) -> tuple[dict[str, str], dict[str, str]] | None:
        return None


@dataclass(frozen=True)
class GrokHarnessAdapter:
    key: str = "grok"
    tree_dir_name: str = "grok"
    activation_kind: str = "grok_plugin_activation"
    activation_path: Path = GROK_PLUGIN_DEST

    def marketplace_paths(self) -> tuple[str, ...]:
        return ()

    def materialized_paths(self) -> tuple[str, ...]:
        return (GROK_PLUGIN_DEST.as_posix(),)

    def plugin_tree_dir(self, ctx: HarnessContext, kind: str) -> Path:
        return plugin_tree_out(ctx.target, kind) / self.tree_dir_name

    def pin_surfaces(
        self, ctx: HarnessContext, *, write_json: Any, deep_merge: Any
    ) -> list[dict[str, str]]:
        return []

    def activation_step(self, ctx: HarnessContext) -> dict[str, str]:
        if plugin_activation_row(ctx.clone, self.key) is None:
            return {
                "path": self.activation_path.as_posix(),
                "action": "skipped_no_contract",
                "kind": self.activation_kind,
            }
        # Delegate through activation shim so tests can patch grok CLI helpers.
        from workstate_bootstrap.activation import activate_grok_plugin

        return activate_grok_plugin(ctx.target)

    def materialization(
        self, ctx: HarnessContext
    ) -> tuple[dict[str, str], dict[str, str]]:
        source_root = plugin_tree_out(ctx.target, "effective") / self.tree_dir_name
        dest_root = ctx.target / GROK_PLUGIN_DEST
        if not source_root.is_dir():
            raise FileNotFoundError(
                f"effective grok plugin tree is missing at {source_root}; "
                "run plugin emission before materializing Grok surfaces"
            )
        action = "updated" if dest_root.exists() else "created"
        if dest_root.exists():
            shutil.rmtree(dest_root)
        shutil.copytree(source_root, dest_root)
        surface = {"path": GROK_PLUGIN_DEST.as_posix(), "source": "generated"}
        config = {
            "path": GROK_PLUGIN_DEST.as_posix(),
            "action": action,
            "kind": "grok_plugin",
        }
        return surface, config


HARNESSES: dict[str, HarnessAdapter] = {
    "claude-code": ClaudeHarnessAdapter(),
    "codex": CodexHarnessAdapter(),
    "cursor": CursorHarnessAdapter(),
    "vscode": VscodeHarnessAdapter(),
    "grok": GrokHarnessAdapter(),
}

HARNESS_PLUGIN_DELIVERY: dict[str, dict[str, tuple[str, ...]]] = {
    key: {
        "marketplace": adapter.marketplace_paths(),
        "materialized": adapter.materialized_paths(),
    }
    for key, adapter in HARNESSES.items()
}


def harness_materialized_surfaces() -> tuple[str, ...]:
    return tuple(
        surface
        for delivery in HARNESS_PLUGIN_DELIVERY.values()
        for surface in delivery.get("materialized", ())
    )


def render_codex_plugin_activation_config(target: Path) -> bytes:
    path = target / CODEX_CONFIG_PATH
    if path.exists():
        try:
            doc = tomlkit.parse(path.read_text())
        except (tomlkit.exceptions.TOMLKitError, UnicodeDecodeError):
            doc = tomlkit.document()
    else:
        doc = tomlkit.document()

    marketplaces = doc.get("marketplaces")
    if not isinstance(marketplaces, dict):
        marketplaces = tomlkit.table(is_super_table=True)
        doc["marketplaces"] = marketplaces
    marketplace = tomlkit.table()
    marketplace["source_type"] = "local"
    marketplace["source"] = "."
    marketplaces[PLUGIN_MARKETPLACE_NAME] = marketplace

    plugins = doc.get("plugins")
    if not isinstance(plugins, dict):
        plugins = tomlkit.table(is_super_table=True)
        doc["plugins"] = plugins
    existing_plugin = plugins.get(PLUGIN_SELECTOR)
    if isinstance(existing_plugin, dict):
        plugin_table = existing_plugin
    else:
        plugin_table = tomlkit.table()
        plugins[PLUGIN_SELECTOR] = plugin_table
    if "enabled" not in plugin_table:
        plugin_table["enabled"] = True

    return tomlkit.dumps(doc).encode("utf-8")


def write_codex_plugin_activation_config(target: Path) -> dict[str, str]:
    path = target / CODEX_CONFIG_PATH
    existed = path.exists()
    rendered = render_codex_plugin_activation_config(target)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(rendered)
    return {
        "path": CODEX_CONFIG_PATH.as_posix(),
        "action": "merged" if existed else "created",
    }


def write_plugin_pins(
    target: Path,
    override_root: Path | None = None,
    *,
    include_codex_activation: bool = True,
    clone: Path | None = None,
) -> list[dict[str, str]]:
    from workstate_bootstrap.fsutil import deep_merge, write_json_file

    ctx = HarnessContext(
        target=target,
        clone=clone or target,
        override_root=override_root,
    )
    entries: list[dict[str, str]] = []
    for adapter in (HARNESSES["claude-code"], HARNESSES["codex"]):
        entries.extend(
            adapter.pin_surfaces(ctx, write_json=write_json_file, deep_merge=deep_merge)
        )
    if include_codex_activation:
        entries.append(write_codex_plugin_activation_config(target))
    return entries


def write_plugin_activation(
    harness_key: str,
    target: Path,
    *,
    clone: Path,
) -> dict[str, str]:
    adapter = HARNESSES.get(harness_key)
    if adapter is None:
        raise ValueError(f"unsupported harness activation: {harness_key!r}")
    return adapter.activation_step(HarnessContext(target=target, clone=clone))


def materialize_grok_plugin(
    target: Path,
) -> tuple[dict[str, str], dict[str, str]]:
    adapter = HARNESSES["grok"]
    result = adapter.materialization(HarnessContext(target=target, clone=target))
    assert result is not None
    return result


def _cursor_effective_root(target: Path) -> Path:
    return plugin_tree_out(target, "effective") / "cursor"


def _cursor_native_plugin_independent(target: Path) -> bool:
    """Path A when the native Cursor plugin tree is the delivery surface."""
    effective = _cursor_effective_root(target)
    if not (effective / ".cursor-plugin").is_dir():
        return False
    settings_path = target / CURSOR_SETTINGS_PATH
    if not settings_path.is_file():
        return True
    try:
        doc = json.loads(settings_path.read_text())
    except (json.JSONDecodeError, OSError):
        return True
    plugins = doc.get("plugins") or {}
    row = plugins.get(PLUGIN_NAME) or {}
    return row.get("enabled") is not False


def _is_bootstrap_managed_cursor_command(path: Path) -> bool:
    if not path.is_file() or path.name == CURSOR_SKILLS_ONLY_MARKER:
        return False
    try:
        return path.read_text().startswith(CURSOR_GENERATOR_TAG)
    except OSError:
        return False


def _is_bootstrap_managed_cursor_skill(
    skill_dir: Path, *, effective_skills: Path
) -> bool:
    if not skill_dir.is_dir():
        return False
    for name in ("SKILL.md", "skill.md"):
        actual = skill_dir / name
        expected = effective_skills / skill_dir.name / name
        if actual.is_file() and expected.is_file():
            try:
                if actual.read_bytes() == expected.read_bytes():
                    return True
            except OSError:
                pass
    return False


def _cursor_skill_md_diverges(actual_skill: Path, expected_skill: Path) -> bool:
    """True iff a managed slot's ``SKILL.md`` is missing or byte-differs from effective.

    Shared by the Path B reconciler and guard so they decide drift identically.
    A read error is treated as "no divergence" (leave the slot alone) — mirroring
    the ``OSError`` handling in :func:`_is_bootstrap_managed_cursor_skill` — so a
    transient I/O fault degrades to a no-op rather than crashing ``doctor``.
    """
    if not expected_skill.is_file():
        return False
    if not actual_skill.is_file():
        return True
    try:
        return actual_skill.read_bytes() != expected_skill.read_bytes()
    except OSError:
        return False


CursorSkillSlotState = Literal[
    "FOREIGN_NAME",
    "FOREIGN_MOUNT",
    "MISSING",
    "CLEAN",
    "DIVERGENT_DIR",
    "NON_DIR_OCCUPANT",
]


def _classify_cursor_skill_slot(
    actual_dir: Path, expected_dir: Path
) -> CursorSkillSlotState:
    """Classify a root ``.cursor/skills/<name>`` slot for Path B reconcile/guard.

    ``FOREIGN_NAME`` is derived from ``not expected_dir.is_dir()`` and must be
    checked before any byte/structural cell so foreign-named dirs are never
    ``rmtree``'d. Symlinked slots are always ``FOREIGN_MOUNT`` (preserved).
    """
    try:
        if not expected_dir.is_dir():
            return "FOREIGN_NAME"
        if actual_dir.is_symlink():
            return "FOREIGN_MOUNT"
        if not actual_dir.exists():
            return "MISSING"
        if not actual_dir.is_dir():
            return "NON_DIR_OCCUPANT"
    except OSError:
        return "CLEAN"
    if _cursor_skill_md_diverges(actual_dir / "SKILL.md", expected_dir / "SKILL.md"):
        return "DIVERGENT_DIR"
    return "CLEAN"


def _cursor_skill_slot_guard_problem(
    rel: Path, skill_name: str, state: CursorSkillSlotState
) -> str | None:
    if state == "DIVERGENT_DIR":
        return (
            f"{rel.as_posix()} skill {skill_name} "
            f"differs from effective cursor tree"
        )
    if state == "MISSING":
        return f"{rel.as_posix()} is missing effective skill {skill_name}"
    if state == "NON_DIR_OCCUPANT":
        return (
            f"{rel.as_posix()} skill {skill_name} occupied by non-directory"
        )
    return None


def _retire_bootstrap_managed_cursor_root_surfaces(target: Path) -> list[str]:
    """Remove duplicate root picker surfaces; emit ``retired:`` audit lines."""
    retired: list[str] = []
    effective = _cursor_effective_root(target)
    effective_skills = effective / "skills"

    commands_dir = target / CURSOR_COMMANDS_DEST
    if commands_dir.is_dir() and not commands_dir.is_symlink():
        for entry in list(commands_dir.iterdir()):
            if entry.is_file() and (
                _is_bootstrap_managed_cursor_command(entry)
                or entry.name == CURSOR_SKILLS_ONLY_MARKER
            ):
                rel = entry.relative_to(target).as_posix()
                entry.unlink()
                retired.append(rel)
                print(f"retired: {rel}")

    skills_dir = target / CURSOR_SKILLS_DEST
    if skills_dir.is_dir() and not skills_dir.is_symlink():
        for skill_dir in list(skills_dir.iterdir()):
            if skill_dir.is_dir() and _is_bootstrap_managed_cursor_skill(
                skill_dir, effective_skills=effective_skills
            ):
                rel = skill_dir.relative_to(target).as_posix()
                shutil.rmtree(skill_dir)
                retired.append(rel)
                print(f"retired: {rel}")

    return retired


def _reconcile_cursor_command_surface(
    target: Path, *, source_root: Path
) -> list[str]:
    """Path B: converge commands dir to the effective marker-only shape."""
    reconciled: list[str] = []
    commands_dir = target / CURSOR_COMMANDS_DEST
    source_commands = source_root / "commands"
    if not source_commands.is_dir():
        return reconciled

    commands_dir.mkdir(parents=True, exist_ok=True)
    for entry in list(commands_dir.iterdir()):
        if entry.is_file() and _is_bootstrap_managed_cursor_command(entry):
            rel = entry.relative_to(target).as_posix()
            entry.unlink()
            reconciled.append(rel)
            print(f"reconciled: {rel}")

    marker = source_commands / CURSOR_SKILLS_ONLY_MARKER
    dest_marker = commands_dir / CURSOR_SKILLS_ONLY_MARKER
    if marker.is_file() and (
        not dest_marker.exists()
        or dest_marker.read_bytes() != marker.read_bytes()
    ):
        shutil.copy2(marker, dest_marker)
        reconciled.append(dest_marker.relative_to(target).as_posix())
        print(f"reconciled: {dest_marker.relative_to(target).as_posix()}")

    return reconciled


def _reconcile_cursor_skills_surface(
    target: Path, *, source_root: Path
) -> list[str]:
    """Path B: converge an existing root skills tree toward the effective tree.

    Managed-slot contract (skills carry no generator-tag provenance, unlike
    commands — see ``_is_bootstrap_managed_cursor_command`` — so "managed" is
    decided structurally, by name):

    * A root ``.cursor/skills/<name>/`` is a *managed slot* iff ``<name>`` is in
      the current effective skills tree. Guard and reconciler share
      :func:`_classify_cursor_skill_slot` so structural classification and
      ``SKILL.md`` byte-drift agree by construction: a managed slot whose
      ``SKILL.md`` diverges from effective is reset (``rmtree`` + ``copytree``);
      a managed name occupied by a plain file is reset (``unlink`` + ``copytree``,
      ``reset:`` audit line); operator content squatting a managed name under a
      real directory is intentionally overwritten so the slot stays repairable.
    * Any skill whose name is *not* in the effective tree is foreign and left
      untouched. A skill bootstrap-emitted under an old name and later dropped
      from effective therefore becomes foreign (preserved) rather than retired —
      retiring it safely would need persistent emission provenance the data
      model does not carry.
    * A symlinked skill subdir is treated as foreign (never ``rmtree``'d), both
      to preserve an operator mount and because ``shutil.rmtree`` raises on a
      symlink. Only ``SKILL.md`` bytes are compared; effective skills ship a
      lone ``SKILL.md``, so auxiliary-file drift inside a managed slot is out of
      scope until effective skills carry more than ``SKILL.md``.
    """
    reconciled: list[str] = []
    skills_dir = target / CURSOR_SKILLS_DEST
    source_skills = source_root / "skills"
    if not source_skills.is_dir():
        return reconciled

    skills_dir.mkdir(parents=True, exist_ok=True)
    for skill_dir in list(skills_dir.iterdir()):
        expected = source_skills / skill_dir.name
        state = _classify_cursor_skill_slot(skill_dir, expected)
        if state == "DIVERGENT_DIR":
            shutil.rmtree(skill_dir)
            shutil.copytree(expected, skill_dir)
            rel = skill_dir.relative_to(target).as_posix()
            reconciled.append(rel)
            print(f"reconciled: {rel}")
        elif state == "NON_DIR_OCCUPANT":
            skill_dir.unlink()
            shutil.copytree(expected, skill_dir)
            rel = skill_dir.relative_to(target).as_posix()
            reconciled.append(rel)
            print(f"reset: {rel}")

    for skill in source_skills.iterdir():
        if not skill.is_dir():
            continue
        dest = skills_dir / skill.name
        state = _classify_cursor_skill_slot(dest, skill)
        if state != "MISSING":
            continue
        shutil.copytree(skill, dest)
        rel = dest.relative_to(target).as_posix()
        reconciled.append(rel)
        print(f"reconciled: {rel}")

    return reconciled


def cursor_native_surface_problems(target: Path) -> list[str]:
    source_root = _cursor_effective_root(target)
    if not source_root.is_dir():
        return []

    problems: list[str] = []
    if _cursor_native_plugin_independent(target):
        effective_skills = source_root / "skills"
        for rel in (CURSOR_COMMANDS_DEST, CURSOR_SKILLS_DEST):
            actual = target / rel
            if not actual.exists():
                continue
            if actual.is_symlink():
                problems.append(f"{rel.as_posix()} must not be a symlink under Path A")
                continue
            if not actual.is_dir():
                problems.append(f"{rel.as_posix()} is not a directory")
                continue
            if rel == CURSOR_COMMANDS_DEST:
                for entry in actual.iterdir():
                    if entry.is_file() and (
                        _is_bootstrap_managed_cursor_command(entry)
                        or entry.name == CURSOR_SKILLS_ONLY_MARKER
                    ):
                        problems.append(
                            f"{rel.as_posix()} carries bootstrap-managed entry "
                            f"{entry.name}"
                        )
            else:
                for entry in actual.iterdir():
                    if entry.is_dir() and _is_bootstrap_managed_cursor_skill(
                        entry, effective_skills=effective_skills
                    ):
                        problems.append(
                            f"{rel.as_posix()} carries bootstrap-managed entry "
                            f"{entry.name}"
                        )
    else:
        for rel in (CURSOR_COMMANDS_DEST, CURSOR_SKILLS_DEST):
            expected = source_root / rel.name
            actual = target / rel
            if not actual.exists():
                problems.append(f"{rel.as_posix()} is missing")
                continue
            if actual.is_symlink():
                try:
                    if not actual.resolve().is_dir():
                        problems.append(f"{rel.as_posix()} symlink target is missing")
                except OSError:
                    problems.append(f"{rel.as_posix()} symlink is broken")
                continue
            if not actual.is_dir():
                problems.append(f"{rel.as_posix()} is not a directory")
                continue
            if rel == CURSOR_COMMANDS_DEST:
                marker = expected / CURSOR_SKILLS_ONLY_MARKER
                if marker.is_file() and not (actual / CURSOR_SKILLS_ONLY_MARKER).is_file():
                    problems.append(
                        f"{rel.as_posix()} is missing {CURSOR_SKILLS_ONLY_MARKER}"
                    )
                for entry in actual.iterdir():
                    if entry.is_file() and _is_bootstrap_managed_cursor_command(entry):
                        problems.append(
                            f"{rel.as_posix()} carries bootstrap-managed entry "
                            f"{entry.name}"
                        )
            else:
                # Managed-slot contract mirrors _reconcile_cursor_skills_surface:
                # guard and reconciler share _classify_cursor_skill_slot.
                for skill_dir in expected.iterdir():
                    if not skill_dir.is_dir():
                        continue
                    actual_dir = actual / skill_dir.name
                    state = _classify_cursor_skill_slot(actual_dir, skill_dir)
                    problem = _cursor_skill_slot_guard_problem(
                        rel, skill_dir.name, state
                    )
                    if problem is not None:
                        problems.append(problem)

    hooks_expected = source_root / "hooks.json"
    hooks_actual = target / CURSOR_HOOKS_PATH
    if not hooks_actual.is_file():
        problems.append(f"{CURSOR_HOOKS_PATH.as_posix()} is missing")
    elif hooks_expected.is_file() and hooks_actual.read_bytes() != hooks_expected.read_bytes():
        problems.append(f"{CURSOR_HOOKS_PATH.as_posix()} differs from effective cursor tree")

    return problems


def materialize_cursor_plugin(
    target: Path,
) -> tuple[list[dict[str, str]], dict[str, str]]:
    source_root = _cursor_effective_root(target)
    if not source_root.is_dir():
        raise FileNotFoundError(
            f"effective cursor plugin tree is missing at {source_root}; "
            "run plugin emission before materializing Cursor surfaces"
        )

    surfaces: list[dict[str, str]] = []
    surface_actions: list[str] = []

    if _cursor_native_plugin_independent(target):
        for rel in _retire_bootstrap_managed_cursor_root_surfaces(target):
            surfaces.append({"path": rel, "source": "retired"})
        materialize_commands_skills = False
    else:
        # Path B: the materialize loop below reconciles an existing commands
        # dir (real-dir branch) or copytrees the marker-only effective tree on
        # a fresh install; no separate pre-pass reconcile is needed.
        materialize_commands_skills = True

    if materialize_commands_skills:
        for source_name, dest in (
            ("commands", target / CURSOR_COMMANDS_DEST),
            ("skills", target / CURSOR_SKILLS_DEST),
        ):
            source = source_root / source_name
            if not source.is_dir():
                raise FileNotFoundError(
                    f"missing generated Cursor {source_name}: {source}"
                )
            action = "updated" if dest.exists() or dest.is_symlink() else "created"
            surface_actions.append(action)
            if dest.exists() or dest.is_symlink():
                if dest.is_dir() and not dest.is_symlink():
                    if source_name == "commands":
                        _reconcile_cursor_command_surface(
                            target, source_root=source_root
                        )
                        surfaces.append(
                            {
                                "path": dest.relative_to(target).as_posix(),
                                "source": "generated",
                            }
                        )
                        continue
                    if source_name == "skills":
                        _reconcile_cursor_skills_surface(
                            target, source_root=source_root
                        )
                        surfaces.append(
                            {
                                "path": dest.relative_to(target).as_posix(),
                                "source": "generated",
                            }
                        )
                        continue
                    surface = {
                        "path": dest.relative_to(target).as_posix(),
                        "source": "local",
                    }
                    surfaces.append(surface)
                    continue
                dest.unlink()
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copytree(source, dest)
            surfaces.append(
                {"path": dest.relative_to(target).as_posix(), "source": "generated"}
            )

    hooks_source = source_root / "hooks.json"
    if not hooks_source.is_file():
        raise FileNotFoundError(f"missing generated Cursor hooks: {hooks_source}")
    hooks_dest = target / CURSOR_HOOKS_PATH
    hooks_action = (
        "updated" if hooks_dest.exists() or hooks_dest.is_symlink() else "created"
    )
    surface_actions.append(hooks_action)
    hooks_dest.parent.mkdir(parents=True, exist_ok=True)
    if hooks_dest.is_symlink() or hooks_dest.is_file():
        hooks_dest.unlink()
    elif hooks_dest.exists():
        surfaces.append({"path": CURSOR_HOOKS_PATH.as_posix(), "source": "local"})
    if not hooks_dest.exists():
        shutil.copy2(hooks_source, hooks_dest)
        surfaces.append({"path": CURSOR_HOOKS_PATH.as_posix(), "source": "generated"})

    config_action = "updated" if "updated" in surface_actions else "created"
    return surfaces, {
        "path": Path(".cursor").as_posix(),
        "action": config_action,
        "kind": "cursor_native_surfaces",
    }


def _grok_user_home() -> Path | None:
    home = os.environ.get("HOME", "").strip()
    if not home:
        return None
    return Path(home)


def _grok_cli_available() -> bool:
    return shutil.which("grok") is not None


def _run_grok_cli(
    args: tuple[str, ...], *, cwd: Path
) -> subprocess.CompletedProcess[str]:
    from workstate_bootstrap.external import run_external

    return run_external(
        ["grok", "plugin", *args],
        call_class="grok_cli",
        cwd=cwd,
        capture_output=True,
        text=True,
        check=False,
        timeout_override=GROK_CLI_TIMEOUT_SECONDS,
    )


def activate_grok_plugin(target: Path) -> dict[str, str]:
    plugin_dest = target / GROK_PLUGIN_DEST
    if not plugin_dest.exists():
        return {
            "path": GROK_PLUGIN_DEST.as_posix(),
            "action": "failed",
            "kind": "grok_plugin_activation",
            "message": "materialized grok plugin tree is missing",
        }
    if not _grok_cli_available():
        return {
            "path": GROK_PLUGIN_DEST.as_posix(),
            "action": "skipped_no_cli",
            "kind": "grok_plugin_activation",
        }

    try:
        install_result = _run_grok_cli(
            ("install", plugin_dest.as_posix(), "--trust"), cwd=target
        )
    except subprocess.TimeoutExpired:
        # ExternalCallTimeout subclasses TimeoutExpired, so this catches both.
        return {
            "path": GROK_PLUGIN_DEST.as_posix(),
            "action": "failed",
            "kind": "grok_plugin_activation",
            "message": "grok plugin install timed out",
        }
    already_present = False
    if install_result.returncode != 0:
        detail = (install_result.stderr or install_result.stdout or "").strip()
        # Already-registered content is idempotent success: fall through to
        # `enable` rather than reporting `failed` (see GROK_ALREADY_INSTALLED_MARKER).
        # Changed content produces a new hash and installs cleanly, so this
        # branch never masks a real content update; and a genuinely broken
        # install is still caught by the `enable` returncode check below.
        if GROK_ALREADY_INSTALLED_MARKER not in detail.lower():
            return {
                "path": GROK_PLUGIN_DEST.as_posix(),
                "action": "failed",
                "kind": "grok_plugin_activation",
                "message": detail or "grok plugin install failed",
            }
        already_present = True

    try:
        enable_result = _run_grok_cli(("enable", GROK_BARE_SELECTOR), cwd=target)
    except subprocess.TimeoutExpired:
        # ExternalCallTimeout subclasses TimeoutExpired, so this catches both.
        return {
            "path": GROK_PLUGIN_DEST.as_posix(),
            "action": "failed",
            "kind": "grok_plugin_activation",
            "message": "grok plugin enable timed out",
        }
    if enable_result.returncode != 0:
        detail = (enable_result.stderr or enable_result.stdout or "").strip()
        return {
            "path": GROK_PLUGIN_DEST.as_posix(),
            "action": "failed",
            "kind": "grok_plugin_activation",
            "message": detail or "grok plugin enable failed",
        }

    return {
        "path": GROK_PLUGIN_DEST.as_posix(),
        # Distinguish a re-run that found the plugin already registered from a
        # fresh install, matching the `already_present` convention used for
        # other idempotent surfaces (Makefile, .gitignore).
        "action": "already_present" if already_present else "applied",
        "kind": "grok_plugin_activation",
    }


def detect_stale_grok_discovery_selectors(home: Path | None = None) -> list[str]:
    home = home if home is not None else _grok_user_home()
    if home is None:
        return []
    config_path = home / ".grok" / "config.toml"
    if not config_path.is_file():
        return []
    try:
        payload = tomllib.loads(config_path.read_text())
    except (tomllib.TOMLDecodeError, UnicodeDecodeError):
        return []
    plugins = payload.get("plugins")
    if not isinstance(plugins, dict):
        return []
    enabled = plugins.get("enabled")
    if not isinstance(enabled, list):
        return []
    return [
        entry
        for entry in enabled
        if isinstance(entry, str) and STALE_DISCOVERY_SELECTOR_RE.match(entry)
    ]


def grok_bare_selector_enabled(home: Path | None = None) -> bool | None:
    home = home if home is not None else _grok_user_home()
    if home is None:
        return None
    config_path = home / ".grok" / "config.toml"
    if not config_path.is_file():
        return None
    try:
        payload = tomllib.loads(config_path.read_text())
    except (tomllib.TOMLDecodeError, UnicodeDecodeError):
        return None
    plugins = payload.get("plugins")
    if not isinstance(plugins, dict):
        return None
    enabled = plugins.get("enabled")
    if not isinstance(enabled, list):
        return None
    return GROK_BARE_SELECTOR in enabled


def materialize_grok_plugin_symlink(
    target: Path,
) -> tuple[dict[str, str], dict[str, str]]:
    source_root = plugin_tree_out(target, "effective") / "grok"
    dest_root = target / GROK_PLUGIN_DEST
    if not source_root.is_dir():
        raise FileNotFoundError(
            f"effective grok plugin tree is missing at {source_root}; "
            "run plugin emission before materializing Grok surfaces"
        )
    if dest_root.exists() and not dest_root.is_symlink():
        surface = {"path": GROK_PLUGIN_DEST.as_posix(), "source": "local"}
        config = {
            "path": GROK_PLUGIN_DEST.as_posix(),
            "action": "skipped_foreign_content",
            "kind": "grok_plugin",
        }
        return surface, config
    rel = os.path.relpath(source_root, dest_root.parent)
    action = "updated" if dest_root.exists() or dest_root.is_symlink() else "created"
    if dest_root.is_symlink():
        dest_root.unlink()
    elif dest_root.exists():
        dest_root.unlink()
    dest_root.parent.mkdir(parents=True, exist_ok=True)
    dest_root.symlink_to(rel, target_is_directory=True)
    surface = {"path": GROK_PLUGIN_DEST.as_posix(), "source": "generated"}
    config = {
        "path": GROK_PLUGIN_DEST.as_posix(),
        "action": action,
        "kind": "grok_plugin",
    }
    return surface, config


def grok_dest_is_unmanaged_dir(target: Path) -> bool:
    dest_root = target / GROK_PLUGIN_DEST
    return (
        dest_root.exists()
        and not dest_root.is_symlink()
        and not (dest_root / ".grok-plugin" / "plugin.json").is_file()
    )


def grok_surface_is_foreign_local(target: Path) -> bool:
    from workstate_bootstrap.worktree import is_linked_worktree

    return grok_dest_is_unmanaged_dir(target) and is_linked_worktree(target)


def grok_plugin_surface_problems(target: Path) -> list[str]:
    from workstate_bootstrap.subcommands import _plugin_tree_integrity_problems

    dest_root = target / GROK_PLUGIN_DEST
    effective_root = plugin_tree_out(target, "effective") / "grok"
    if not dest_root.exists():
        if effective_root.is_dir():
            return ["materialized grok plugin is missing"]
        return []
    if grok_surface_is_foreign_local(target):
        return []
    if dest_root.is_symlink():
        try:
            resolved = dest_root.resolve()
            if not resolved.is_dir():
                return ["grok plugin symlink target is missing"]
            dest_root = resolved
        except OSError:
            return ["grok plugin symlink is broken"]
    problems = _plugin_tree_integrity_problems(dest_root, "grok")
    if (
        effective_root.is_dir()
        and (effective_root / "skills").is_dir()
        and (dest_root / "skills").is_dir()
    ):
        expected_skills = {
            path.name for path in (effective_root / "skills").iterdir() if path.is_dir()
        }
        actual_skills = {
            path.name for path in (dest_root / "skills").iterdir() if path.is_dir()
        }
        if expected_skills != actual_skills:
            problems.append("skills/ slug set differs from effective grok plugin tree")
    return problems
