"""Pin-sync gate for the ``workstate-stack`` meta-package (implementation note implementation note).

The meta-package is the single version anchor consumers install: its
``dependencies`` block carries exact ``==`` pins on every published stack
member. Pins are never hand-edited — ``scripts/stack_pins.py sync``
regenerates them from sibling ``pyproject.toml`` versions and
``scripts/stack_pins.py check`` (``make stack-pins-check``) fails when they
drift, so a member bump can never ship without moving the meta pins.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
SOURCE_STACK_PINS = REPO_ROOT / "scripts" / "stack_pins.py"

EXPECTED_MEMBERS = (
    "workstate-protocol",
    "mcp-workstate-handoff",
    "mcp-workstate-orchestrator",
    "workstate-bootstrap",
    "workstate-system",
)


def _load_module():
    spec = importlib.util.spec_from_file_location(
        "stack_pins_under_test", SOURCE_STACK_PINS
    )
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    # Register before exec so @dataclass (under `from __future__ import
    # annotations`) can resolve the module via sys.modules[cls.__module__].
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _member_pyproject(name: str, version: str) -> str:
    return f'[project]\nname = "{name}"\nversion = "{version}"\n'


def _stack_pyproject(pins: dict[str, str] | None) -> str:
    """Stack pyproject with the generated pins block carrying ``pins``."""
    lines = [
        "[build-system]",
        'requires = ["setuptools>=68", "wheel"]',
        'build-backend = "setuptools.build_meta"',
        "",
        "[project]",
        'name = "workstate-stack"',
        'version = "0.1.0"',
        'description = "fixture"',
        'requires-python = ">=3.11"',
        "dependencies = [",
        "    # >>> STACK PINS (generated by scripts/stack_pins.py; make stack-pins-sync) >>>",
    ]
    for distribution, version in (pins or {}).items():
        lines.append(f'    "{distribution}=={version}",')
    lines.extend(
        [
            "    # <<< STACK PINS <<<",
            "]",
            "",
            "[tool.setuptools.packages.find]",
            'where = ["src"]',
            "",
        ]
    )
    return "\n".join(lines)


def _build_repo(
    tmp_path: Path,
    *,
    member_versions: dict[str, str] | None = None,
    stack_pins: dict[str, str] | None = None,
    omit_stack_block: bool = False,
) -> Path:
    """Synthetic monorepo: release manifest, member pyprojects, stack pyproject."""
    repo = tmp_path / "repo"
    versions = dict(member_versions or {})
    for member in EXPECTED_MEMBERS:
        versions.setdefault(member, "1.0.0")
    # Non-member packages prove the member set is closed.
    versions.setdefault("mcp-workstate-canvas", "9.9.9")
    versions.setdefault("workstate-codex-bridge", "9.9.9")

    packages = []
    for name, version in versions.items():
        path = f"packages/{name}"
        _write(repo / path / "pyproject.toml", _member_pyproject(name, version))
        packages.append(
            {
                "name": name,
                "path": path,
                "distribution": name,
                "artifact_prefix": name.replace("-", "_"),
                "publish": name != "mcp-workstate-canvas",
                "test_command": "python -m pytest -q",
                "changelog": f"{path}/CHANGELOG.md",
            }
        )
    _write(
        repo / "config" / "release" / "packages.json",
        json.dumps({"packages": packages}, indent=2) + "\n",
    )

    if omit_stack_block:
        stack_text = _stack_pyproject(None).replace(
            "    # >>> STACK PINS (generated by scripts/stack_pins.py; make stack-pins-sync) >>>\n",
            "",
        ).replace("    # <<< STACK PINS <<<\n", "")
    else:
        pins = stack_pins
        if pins is None:
            pins = {member: versions[member] for member in EXPECTED_MEMBERS}
        stack_text = _stack_pyproject(pins)
    _write(repo / "packages" / "workstate-stack" / "pyproject.toml", stack_text)
    return repo


def test_member_set_is_exactly_the_published_runtime_stack():
    module = _load_module()
    assert tuple(module.STACK_MEMBERS) == EXPECTED_MEMBERS
    assert "mcp-workstate-canvas" not in module.STACK_MEMBERS
    assert "workstate-codex-bridge" not in module.STACK_MEMBERS


def test_check_passes_when_pins_match_member_versions(tmp_path: Path):
    module = _load_module()
    repo = _build_repo(tmp_path, member_versions={"workstate-system": "0.2.1"})
    ok, messages = module.check(repo)
    assert ok, messages


def test_check_flags_drifted_pin(tmp_path: Path):
    module = _load_module()
    versions = {member: "1.0.0" for member in EXPECTED_MEMBERS}
    stale = dict(versions)
    stale["workstate-system"] = "0.9.0"
    repo = _build_repo(tmp_path, member_versions=versions, stack_pins=stale)
    ok, messages = module.check(repo)
    assert not ok
    blob = "\n".join(messages)
    assert "workstate-system" in blob
    assert "0.9.0" in blob and "1.0.0" in blob
    assert "stack-pins-sync" in blob  # remediation is named, not implied


def test_check_flags_missing_member_pin(tmp_path: Path):
    module = _load_module()
    pins = {member: "1.0.0" for member in EXPECTED_MEMBERS}
    del pins["mcp-workstate-handoff"]
    repo = _build_repo(tmp_path, stack_pins=pins)
    ok, messages = module.check(repo)
    assert not ok
    assert any("mcp-workstate-handoff" in line for line in messages)


def test_sync_rewrites_drifted_pins_then_check_passes(tmp_path: Path):
    module = _load_module()
    versions = {member: "2.3.4" for member in EXPECTED_MEMBERS}
    stale = {member: "0.0.1" for member in EXPECTED_MEMBERS}
    repo = _build_repo(tmp_path, member_versions=versions, stack_pins=stale)

    changed = module.sync(repo)
    assert changed

    text = (repo / "packages" / "workstate-stack" / "pyproject.toml").read_text()
    for member in EXPECTED_MEMBERS:
        assert f'"{member}==2.3.4"' in text
    ok, messages = module.check(repo)
    assert ok, messages


def test_sync_is_idempotent_and_preserves_surrounding_content(tmp_path: Path):
    module = _load_module()
    repo = _build_repo(tmp_path)
    pyproject = repo / "packages" / "workstate-stack" / "pyproject.toml"
    before = pyproject.read_text()

    assert module.sync(repo) is False  # already in sync -> no rewrite
    after = pyproject.read_text()
    assert after == before
    assert 'name = "workstate-stack"' in after
    assert "[tool.setuptools.packages.find]" in after


def test_missing_sentinel_block_is_a_clear_error(tmp_path: Path):
    module = _load_module()
    repo = _build_repo(tmp_path, omit_stack_block=True)
    ok, messages = module.check(repo)
    assert not ok
    assert any("STACK PINS" in line for line in messages)


def test_cli_check_exit_codes(tmp_path: Path):
    module = _load_module()
    repo = _build_repo(tmp_path)
    assert module.main(["check", "--repo-root", str(repo)]) == 0

    stale = {member: "0.0.1" for member in EXPECTED_MEMBERS}
    drifted = _build_repo(tmp_path / "drift", stack_pins=stale)
    assert module.main(["check", "--repo-root", str(drifted)]) == 1
    assert module.main(["sync", "--repo-root", str(drifted)]) == 0
    assert module.main(["check", "--repo-root", str(drifted)]) == 0


def test_real_repo_pins_are_in_sync():
    """The committed meta-package pins always match sibling versions."""
    module = _load_module()
    ok, messages = module.check(REPO_ROOT)
    assert ok, messages
