from __future__ import annotations

import os
import json
import shutil
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[4]
SOURCE_RELEASE_SCRIPT = REPO_ROOT / "scripts" / "release.sh"
SOURCE_RELEASE_MANIFEST = REPO_ROOT / "config" / "release" / "packages.json"
SOURCE_RELEASE_MANIFEST_HELPER = REPO_ROOT / "scripts" / "release_manifest.py"
SOURCE_RELEASE_DRIFT_GATE = REPO_ROOT / "scripts" / "check_release_version_drift.py"
SOURCE_STACK_PINS_GATE = REPO_ROOT / "scripts" / "stack_pins.py"
STACK_MEMBERS = (
    "workstate-protocol",
    "mcp-workstate-handoff",
    "mcp-workstate-orchestrator",
    "workstate-bootstrap",
    "workstate-system",
)
FIXTURE_PACKAGES = (
    "workstate-protocol",
    "mcp-workstate-handoff",
    "mcp-workstate-orchestrator",
    "mcp-workstate-canvas",
    "workstate-bootstrap",
    "workstate-codex-bridge",
    "workstate-system",
    "workstate-stack",
)


def _build_release_fixture(
    tmp_path: Path,
    *,
    version: str,
    failing_package: str | None = None,
) -> Path:
    repo = tmp_path / "repo"
    (repo / "config" / "release").mkdir(parents=True)
    (repo / "scripts").mkdir(parents=True)
    shutil.copy2(SOURCE_RELEASE_SCRIPT, repo / "scripts" / "release.sh")
    shutil.copy2(SOURCE_RELEASE_MANIFEST, repo / "config" / "release" / "packages.json")
    shutil.copy2(SOURCE_RELEASE_MANIFEST_HELPER, repo / "scripts" / "release_manifest.py")
    shutil.copy2(SOURCE_RELEASE_DRIFT_GATE, repo / "scripts" / "check_release_version_drift.py")
    shutil.copy2(SOURCE_STACK_PINS_GATE, repo / "scripts" / "stack_pins.py")
    (repo / "scripts" / "release.sh").chmod(0o755)
    (repo / "scripts" / "release_manifest.py").chmod(0o755)
    (repo / "scripts" / "check_release_version_drift.py").chmod(0o755)
    (repo / "scripts" / "stack_pins.py").chmod(0o755)

    for package in FIXTURE_PACKAGES:
        package_dir = repo / "packages" / package
        package_dir.mkdir(parents=True)
        if package == "workstate-stack":
            # The meta-package fixture must carry the generated pins block at
            # the fixture version so the release.sh stack-pin gate passes.
            pins = "".join(
                f'    "{member}=={version}",\n' for member in STACK_MEMBERS
            )
            (package_dir / "pyproject.toml").write_text(
                f"[project]\nname = \"{package}\"\nversion = \"{version}\"\n"
                "dependencies = [\n"
                "    # >>> STACK PINS (generated by scripts/stack_pins.py; "
                "make stack-pins-sync) >>>\n"
                f"{pins}"
                "    # <<< STACK PINS <<<\n"
                "]\n",
                encoding="utf-8",
            )
        else:
            (package_dir / "pyproject.toml").write_text(
                f"[project]\nname = \"{package}\"\nversion = \"{version}\"\n",
                encoding="utf-8",
            )
        (package_dir / "CHANGELOG.md").write_text(
            f"# {package}\n\n## {version}\n\n- Fixture entry.\n",
            encoding="utf-8",
        )
        tests_dir = package_dir / "tests"
        tests_dir.mkdir()
        smoke_assertion = "assert True"
        if package == failing_package:
            smoke_assertion = "assert False"
        (tests_dir / "test_smoke.py").write_text(
            f"def test_smoke() -> None:\n    {smoke_assertion}\n",
            encoding="utf-8",
        )

    (repo / "packages" / "mcp-workstate-orchestrator" / "tests" / "test_protocol_contract.py").write_text(
        "def test_protocol_contract() -> None:\n    assert True\n",
        encoding="utf-8",
    )
    (repo / "packages" / "workstate-bootstrap" / "tests" / "test_bootstrap_install_rehearsal.py").write_text(
        "def test_bootstrap_install_rehearsal() -> None:\n    assert True\n",
        encoding="utf-8",
    )
    return repo


def _install_fake_release_cli(
    tmp_path: Path,
    *,
    anomalous_pkg: str,
    version: str,
    anomaly_mode: str,
    monorepo_tag: str = "",
    released_packages: tuple[str, ...] | None = None,
) -> Path:
    released_packages = FIXTURE_PACKAGES if released_packages is None else released_packages
    released_packages_csv = ",".join(released_packages)
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()

    git_stub = bin_dir / "git"
    git_stub.write_text(
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        "version=\"$FAKE_RELEASE_VERSION\"\n"
        "anomalous_pkg=\"$FAKE_RELEASE_ANOMALOUS_PKG\"\n"
        "anomaly_mode=\"$FAKE_RELEASE_ANOMALY_MODE\"\n"
        "monorepo_tag=\"${FAKE_RELEASE_MONOREPO_TAG:-}\"\n"
        f"released_packages=\",${{FAKE_RELEASE_RELEASED_PACKAGES:-{released_packages_csv}}},\"\n"
        # The `git -C <repo> ...` form is used only by the release version-drift
        # gate (check_release_version_drift.py). Answer log/show/diff so the gate
        # locates a clean version-set commit and reports no drift in the fixture.
        "if [[ ${1:-} == \"-C\" ]]; then\n"
        "    sub=${3:-}\n"
        "    if [[ $sub == \"log\" ]]; then\n"
        "        printf 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\\n'; exit 0\n"
        "    fi\n"
        "    if [[ $sub == \"show\" ]]; then\n"
        "        ref=${4%%:*}\n"
        "        if [[ $ref == *\"^\" ]]; then\n"
        "            printf '[project]\\nname = \"x\"\\nversion = \"0.0.0\"\\n'; exit 0\n"
        "        fi\n"
        "        printf '[project]\\nname = \"x\"\\nversion = \"%s\"\\n' \"$version\"; exit 0\n"
        "    fi\n"
        "    if [[ $sub == \"diff\" ]]; then\n"
        "        exit 0\n"
        "    fi\n"
        "    exit 0\n"
        "fi\n"
        "if [[ ${1:-} == \"status\" && ${2:-} == \"--porcelain\" ]]; then\n"
        "    exit 0\n"
        "fi\n"
        "if [[ ${1:-} == \"fetch\" ]]; then\n"
        "    exit 0\n"
        "fi\n"
        "if [[ ${1:-} == \"rev-parse\" && ${2:-} == \"--abbrev-ref\" ]]; then\n"
        "    printf 'main\\n'\n"
        "    exit 0\n"
        "fi\n"
        "if [[ ${1:-} == \"rev-parse\" && ${2:-} == \"HEAD\" ]]; then\n"
        "    printf 'deadbeefdeadbeefdeadbeefdeadbeefdeadbeef\\n'\n"
        "    exit 0\n"
        "fi\n"
        "if [[ ${1:-} == \"rev-parse\" && ${2:-} == \"origin/main\" ]]; then\n"
        "    printf 'deadbeefdeadbeefdeadbeefdeadbeefdeadbeef\\n'\n"
        "    exit 0\n"
        "fi\n"
        "if [[ ${1:-} == \"rev-parse\" && ${2:-} == \"-q\" && ${3:-} == \"--verify\" ]]; then\n"
        "    tag=${4#refs/tags/}\n"
        "    if [[ -n $monorepo_tag && $tag == $monorepo_tag && $anomaly_mode == \"monorepo_tag_missing\" ]]; then\n"
        "        exit 1\n"
        "    fi\n"
        "    if [[ $tag == ${anomalous_pkg}-v${version} && $anomaly_mode == \"pypi_without_tag\" ]]; then\n"
        "        exit 1\n"
        "    fi\n"
        "    if [[ $tag == *-v${version} ]]; then\n"
        "        pkg=${tag%-v${version}}\n"
        "        if [[ $released_packages != *,${pkg},* ]]; then\n"
        "            exit 1\n"
        "        fi\n"
        "    fi\n"
        "    printf 'deadbeef\\n'\n"
        "    exit 0\n"
        "fi\n"
        "if [[ ${1:-} == \"ls-remote\" && ${2:-} == \"--tags\" && ${3:-} == \"origin\" ]]; then\n"
        "    tag=${4#refs/tags/}\n"
        "    if [[ -n $monorepo_tag && $tag == $monorepo_tag && $anomaly_mode == \"monorepo_tag_missing\" ]]; then\n"
        "        exit 0\n"
        "    fi\n"
        "    if [[ $tag == ${anomalous_pkg}-v${version} && $anomaly_mode == \"pypi_without_tag\" ]]; then\n"
        "        exit 0\n"
        "    fi\n"
        "    if [[ $tag == ${anomalous_pkg}-v${version} && $anomaly_mode == \"local_tag_with_pypi_missing_remote\" ]]; then\n"
        "        exit 0\n"
        "    fi\n"
        "    if [[ $tag == *-v${version} ]]; then\n"
        "        pkg=${tag%-v${version}}\n"
        "        if [[ $released_packages != *,${pkg},* ]]; then\n"
        "            exit 0\n"
        "        fi\n"
        "    fi\n"
        "    printf 'deadbeef\\trefs/tags/%s\\n' \"$tag\"\n"
        "    exit 0\n"
        "fi\n"
        "if [[ ${1:-} == \"tag\" && ${2:-} == \"-l\" ]]; then\n"
        "    printf 'v0.1.9\\n'\n"
        "    exit 0\n"
        "fi\n"
        "if [[ ${1:-} == \"tag\" && ${2:-} != \"-l\" ]]; then\n"
        "    exit 0\n"
        "fi\n"
        "if [[ ${1:-} == \"push\" && ${2:-} == \"origin\" ]]; then\n"
        "    exit 0\n"
        "fi\n"
        "if [[ ${1:-} == \"merge-base\" && ${2:-} == \"--is-ancestor\" ]]; then\n"
        "    exit 0\n"
        "fi\n"
        "printf 'unexpected git invocation: %s\\n' \"$*\" >&2\n"
        "exit 99\n",
        encoding="utf-8",
    )
    git_stub.chmod(0o755)

    uvx_stub = bin_dir / "uvx"
    uvx_stub.write_text(
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        "pkg=${@: -1}\n"
        "version=\"$FAKE_RELEASE_VERSION\"\n"
        "anomalous_pkg=\"$FAKE_RELEASE_ANOMALOUS_PKG\"\n"
        "anomaly_mode=\"$FAKE_RELEASE_ANOMALY_MODE\"\n"
        "published_after_upload_file=\"${FAKE_RELEASE_PUBLISHED_AFTER_UPLOAD_FILE:-}\"\n"
        f"released_packages=\",${{FAKE_RELEASE_RELEASED_PACKAGES:-{released_packages_csv}}},\"\n"
        "if [[ $* == *\"twine check\"* || $* == *\"pyproject-build\"* ]]; then\n"
        "    exit 0\n"
        "fi\n"
        "if [[ $pkg == $anomalous_pkg && $anomaly_mode == \"remote_tag_without_pypi\" ]]; then\n"
        "    printf '%s\\n' 'Available versions: 0.0.1'\n"
        "elif [[ -n $published_after_upload_file && -f $published_after_upload_file && $pkg == $anomalous_pkg ]]; then\n"
        "    printf 'Available versions: %s (%s)\\n' \"$version\" \"$version\"\n"
        "elif [[ $released_packages == *,${pkg},* ]]; then\n"
        "    printf 'Available versions: %s\\n' \"$version\"\n"
        "else\n"
        "    printf '%s\\n' 'Available versions: 0.0.1'\n"
        "fi\n",
        encoding="utf-8",
    )
    uvx_stub.chmod(0o755)

    # gh stub: intercept `gh workflow run` to simulate Trusted Publishing.
    # Writing to published_after_upload_file triggers the PyPI-presence check
    # in release.sh (simulates the CI workflow publishing the package).
    gh_stub = bin_dir / "gh"
    gh_stub.write_text(
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        "published_after_upload_file=\"${FAKE_RELEASE_PUBLISHED_AFTER_UPLOAD_FILE:-}\"\n"
        "if [[ ${1:-} == \"workflow\" && ${2:-} == \"run\" ]]; then\n"
        "    if [[ -n $published_after_upload_file ]]; then\n"
        "        printf 'published\\n' > \"$published_after_upload_file\"\n"
        "    fi\n"
        "    exit 0\n"
        "fi\n"
        "exit 0\n",
        encoding="utf-8",
    )
    gh_stub.chmod(0o755)

    return bin_dir


@pytest.mark.skipif(shutil.which("bash") is None, reason="bash not installed")
def test_pending_blocks_remote_tag_without_pypi(tmp_path: Path) -> None:
    version = "1.2.3"
    anomalous_pkg = "workstate-protocol"
    repo = _build_release_fixture(tmp_path, version=version)
    bin_dir = _install_fake_release_cli(
        tmp_path,
        anomalous_pkg=anomalous_pkg,
        version=version,
        anomaly_mode="remote_tag_without_pypi",
    )

    env = {
        **os.environ,
        "PATH": f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}",
        "FAKE_RELEASE_ANOMALOUS_PKG": anomalous_pkg,
        "FAKE_RELEASE_ANOMALY_MODE": "remote_tag_without_pypi",
        "FAKE_RELEASE_VERSION": version,
    }
    result = subprocess.run(
        ["bash", str(repo / "scripts" / "release.sh"), "--dry-run", "pending"],
        cwd=repo,
        env=env,
        text=True,
        capture_output=True,
    )

    combined = result.stdout + result.stderr
    assert result.returncode == 1, combined
    assert anomalous_pkg in combined
    assert "remote_tag_without_pypi" in combined


@pytest.mark.skipif(shutil.which("bash") is None, reason="bash not installed")
def test_pending_blocks_pypi_without_tag_with_tag_recovery_guidance(tmp_path: Path) -> None:
    version = "1.2.3"
    anomalous_pkg = "workstate-protocol"
    repo = _build_release_fixture(tmp_path, version=version)
    bin_dir = _install_fake_release_cli(
        tmp_path,
        anomalous_pkg=anomalous_pkg,
        version=version,
        anomaly_mode="pypi_without_tag",
    )

    env = {
        **os.environ,
        "PATH": f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}",
        "FAKE_RELEASE_ANOMALOUS_PKG": anomalous_pkg,
        "FAKE_RELEASE_ANOMALY_MODE": "pypi_without_tag",
        "FAKE_RELEASE_VERSION": version,
    }
    result = subprocess.run(
        ["bash", str(repo / "scripts" / "release.sh"), "--dry-run", "pending"],
        cwd=repo,
        env=env,
        text=True,
        capture_output=True,
    )

    combined = result.stdout + result.stderr
    assert result.returncode == 1, combined
    assert anomalous_pkg in combined
    assert "pypi_without_tag" in combined
    assert "create and push the matching package tag" in combined


@pytest.mark.skipif(shutil.which("bash") is None, reason="bash not installed")
def test_pending_blocks_pypi_with_local_tag_missing_remote_tag(tmp_path: Path) -> None:
    version = "1.2.3"
    anomalous_pkg = "workstate-protocol"
    repo = _build_release_fixture(tmp_path, version=version)
    bin_dir = _install_fake_release_cli(
        tmp_path,
        anomalous_pkg=anomalous_pkg,
        version=version,
        anomaly_mode="local_tag_with_pypi_missing_remote",
    )

    env = {
        **os.environ,
        "PATH": f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}",
        "FAKE_RELEASE_ANOMALOUS_PKG": anomalous_pkg,
        "FAKE_RELEASE_ANOMALY_MODE": "local_tag_with_pypi_missing_remote",
        "FAKE_RELEASE_VERSION": version,
    }
    result = subprocess.run(
        ["bash", str(repo / "scripts" / "release.sh"), "--dry-run", "pending"],
        cwd=repo,
        env=env,
        text=True,
        capture_output=True,
    )

    combined = result.stdout + result.stderr
    assert result.returncode == 1, combined
    assert anomalous_pkg in combined
    assert "local_tag_with_pypi_missing_remote" in combined
    assert "push the matching package tag" in combined


@pytest.mark.skipif(shutil.which("bash") is None, reason="bash not installed")
def test_pending_cuts_requested_monorepo_tag_when_packages_are_released(tmp_path: Path) -> None:
    version = "1.2.3"
    requested_tag = "v9.9.9"
    repo = _build_release_fixture(tmp_path, version=version)
    bin_dir = _install_fake_release_cli(
        tmp_path,
        anomalous_pkg="workstate-protocol",
        version=version,
        anomaly_mode="monorepo_tag_missing",
        monorepo_tag=requested_tag,
    )

    env = {
        **os.environ,
        "PATH": f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}",
        "FAKE_RELEASE_ANOMALOUS_PKG": "workstate-protocol",
        "FAKE_RELEASE_ANOMALY_MODE": "monorepo_tag_missing",
        "FAKE_RELEASE_MONOREPO_TAG": requested_tag,
        "FAKE_RELEASE_VERSION": version,
    }
    result = subprocess.run(
        ["bash", str(repo / "scripts" / "release.sh"), "--dry-run", "pending", requested_tag],
        cwd=repo,
        env=env,
        text=True,
        capture_output=True,
    )

    combined = result.stdout + result.stderr
    assert result.returncode == 0, combined
    assert "no unpublished package versions are pending" not in combined
    assert f"monorepo: cutting {requested_tag}" in combined


@pytest.mark.skipif(shutil.which("bash") is None, reason="bash not installed")
def test_all_resumes_when_every_package_is_already_released(tmp_path: Path) -> None:
    version = "1.2.3"
    repo = _build_release_fixture(tmp_path, version=version)
    bin_dir = _install_fake_release_cli(
        tmp_path,
        anomalous_pkg="workstate-protocol",
        version=version,
        anomaly_mode="steady_state",
        released_packages=("workstate-protocol",),
    )

    env = {
        **os.environ,
        "PATH": f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}",
        "FAKE_RELEASE_ANOMALOUS_PKG": "workstate-protocol",
        "FAKE_RELEASE_ANOMALY_MODE": "steady_state",
        "FAKE_RELEASE_RELEASED_PACKAGES": "workstate-protocol",
        "FAKE_RELEASE_VERSION": version,
    }
    result = subprocess.run(
        ["bash", str(repo / "scripts" / "release.sh"), "--dry-run", "all"],
        cwd=repo,
        env=env,
        text=True,
        capture_output=True,
    )

    combined = result.stdout + result.stderr
    assert result.returncode == 0, combined
    assert "tag workstate-protocol-v1.2.3 already exists locally" not in combined
    assert "release: mcp-workstate-handoff 1.2.3" in combined
    assert "Run: scripts/release.sh monorepo vX.Y.Z" in combined


@pytest.mark.skipif(shutil.which("bash") is None, reason="bash not installed")
def test_plan_json_reports_states_and_next_safe_command(tmp_path: Path) -> None:
    version = "1.2.3"
    repo = _build_release_fixture(tmp_path, version=version)
    bin_dir = _install_fake_release_cli(
        tmp_path,
        anomalous_pkg="workstate-protocol",
        version=version,
        anomaly_mode="steady_state",
        released_packages=("workstate-protocol",),
    )

    env = {
        **os.environ,
        "PATH": f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}",
        "FAKE_RELEASE_ANOMALOUS_PKG": "workstate-protocol",
        "FAKE_RELEASE_ANOMALY_MODE": "steady_state",
        "FAKE_RELEASE_RELEASED_PACKAGES": "workstate-protocol",
        "FAKE_RELEASE_VERSION": version,
    }
    result = subprocess.run(
        ["bash", str(repo / "scripts" / "release.sh"), "plan", "--json"],
        cwd=repo,
        env=env,
        text=True,
        capture_output=True,
    )

    assert result.returncode == 0, result.stderr
    plan = json.loads(result.stdout)
    assert plan["monorepo"]["suggested_next_tag"] == "v0.1.10"
    assert plan["next_safe_command"] == "scripts/release.sh pending v0.1.10"
    package_states = {package["name"]: package for package in plan["packages"]}
    assert package_states["workstate-protocol"]["state"] == "released"
    assert package_states["workstate-protocol"]["intended_action"] == "skip"
    assert package_states["mcp-workstate-handoff"]["state"] == "pending_upload"
    assert package_states["mcp-workstate-handoff"]["intended_action"] == "publish"


@pytest.mark.skipif(shutil.which("bash") is None, reason="bash not installed")
def test_pending_dry_run_writes_plan_and_summary_artifacts(tmp_path: Path) -> None:
    version = "1.2.3"
    requested_tag = "v9.9.9"
    repo = _build_release_fixture(tmp_path, version=version)
    bin_dir = _install_fake_release_cli(
        tmp_path,
        anomalous_pkg="workstate-protocol",
        version=version,
        anomaly_mode="steady_state",
        released_packages=("workstate-protocol",),
    )

    env = {
        **os.environ,
        "PATH": f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}",
        "FAKE_RELEASE_ANOMALOUS_PKG": "workstate-protocol",
        "FAKE_RELEASE_ANOMALY_MODE": "monorepo_tag_missing",
        "FAKE_RELEASE_MONOREPO_TAG": requested_tag,
        "FAKE_RELEASE_RELEASED_PACKAGES": "workstate-protocol",
        "FAKE_RELEASE_VERSION": version,
        "WORKSTATE_RELEASE_RUN_ID": "test-run-001",
    }
    result = subprocess.run(
        ["bash", str(repo / "scripts" / "release.sh"), "--dry-run", "pending", requested_tag],
        cwd=repo,
        env=env,
        text=True,
        capture_output=True,
    )

    combined = result.stdout + result.stderr
    assert result.returncode == 0, combined

    run_dir = repo / "logs" / "release" / "test-run-001"
    assert (run_dir / "plan.json").exists()
    assert (run_dir / "summary.json").exists()
    assert (run_dir / "final-summary.md").exists()

    plan = json.loads((run_dir / "plan.json").read_text(encoding="utf-8"))
    summary = json.loads((run_dir / "summary.json").read_text(encoding="utf-8"))
    final_summary = (run_dir / "final-summary.md").read_text(encoding="utf-8")

    assert plan["monorepo"]["requested_tag"] == requested_tag
    assert summary["command"] == "pending"
    assert summary["status"] == "completed"
    assert summary["dry_run"] is True
    assert summary["package_counts"] == {"publish": 6, "skip": 1, "block": 0}
    assert "plan.json" in combined
    assert "summary.json" in combined
    assert requested_tag in final_summary
    assert "scripts/release.sh pending v9.9.9" in final_summary


@pytest.mark.skipif(shutil.which("bash") is None, reason="bash not installed")
def test_preflight_failure_reports_log_path_and_tail(tmp_path: Path) -> None:
    version = "1.2.3"
    repo = _build_release_fixture(tmp_path, version=version, failing_package="mcp-workstate-handoff")
    bin_dir = _install_fake_release_cli(
        tmp_path,
        anomalous_pkg="workstate-protocol",
        version=version,
        anomaly_mode="steady_state",
    )

    env = {
        **os.environ,
        "PATH": f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}",
        "FAKE_RELEASE_ANOMALOUS_PKG": "workstate-protocol",
        "FAKE_RELEASE_ANOMALY_MODE": "steady_state",
        "FAKE_RELEASE_VERSION": version,
        "WORKSTATE_RELEASE_RUN_ID": "test-run-002",
    }
    result = subprocess.run(
        ["bash", str(repo / "scripts" / "release.sh"), "preflight"],
        cwd=repo,
        env=env,
        text=True,
        capture_output=True,
    )

    combined = result.stdout + result.stderr
    assert result.returncode == 1, combined

    log_path = repo / "logs" / "release" / "test-run-002" / "preflight-mcp-workstate-handoff.log"
    assert log_path.exists()
    log_contents = log_path.read_text(encoding="utf-8")
    assert "test_smoke" in log_contents
    assert "assert False" in log_contents
    assert str(log_path) in combined
    assert "assert False" in combined

    run_dir = repo / "logs" / "release" / "test-run-002"
    summary_path = run_dir / "summary.json"
    final_summary_path = run_dir / "final-summary.md"
    assert summary_path.exists()
    assert final_summary_path.exists()

    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    final_summary = final_summary_path.read_text(encoding="utf-8")
    assert summary["command"] == "preflight"
    assert summary["status"] == "failed"
    assert summary["failure_log"] == str(log_path)
    assert str(log_path) in final_summary


@pytest.mark.skipif(shutil.which("bash") is None, reason="bash not installed")
def test_pending_preflight_failure_writes_pending_summary(tmp_path: Path) -> None:
    version = "1.2.3"
    repo = _build_release_fixture(tmp_path, version=version, failing_package="mcp-workstate-handoff")
    bin_dir = _install_fake_release_cli(
        tmp_path,
        anomalous_pkg="workstate-protocol",
        version=version,
        anomaly_mode="steady_state",
        released_packages=(),
    )

    env = {
        **os.environ,
        "PATH": f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}",
        "FAKE_RELEASE_ANOMALOUS_PKG": "workstate-protocol",
        "FAKE_RELEASE_ANOMALY_MODE": "steady_state",
        "FAKE_RELEASE_RELEASED_PACKAGES": "",
        "FAKE_RELEASE_VERSION": version,
        "WORKSTATE_RELEASE_RUN_ID": "test-run-004",
    }
    result = subprocess.run(
        ["bash", str(repo / "scripts" / "release.sh"), "pending", "v9.9.9"],
        cwd=repo,
        env=env,
        text=True,
        capture_output=True,
    )

    combined = result.stdout + result.stderr
    assert result.returncode == 1, combined

    run_dir = repo / "logs" / "release" / "test-run-004"
    log_path = run_dir / "preflight-mcp-workstate-handoff.log"
    summary_path = run_dir / "summary.json"
    final_summary_path = run_dir / "final-summary.md"
    assert log_path.exists()
    assert summary_path.exists()
    assert final_summary_path.exists()

    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    final_summary = final_summary_path.read_text(encoding="utf-8")
    assert summary["command"] == "pending"
    assert summary["status"] == "failed"
    assert summary["requested_tag"] == "v9.9.9"
    assert summary["failure_log"] == str(log_path)
    assert str(log_path) in final_summary


@pytest.mark.skipif(shutil.which("bash") is None, reason="bash not installed")
def test_package_success_writes_summary_artifacts(tmp_path: Path) -> None:
    version = "1.2.3"
    package = "workstate-protocol"
    repo = _build_release_fixture(tmp_path, version=version)
    bin_dir = _install_fake_release_cli(
        tmp_path,
        anomalous_pkg=package,
        version=version,
        anomaly_mode="steady_state",
        released_packages=(),
    )
    published_marker = tmp_path / "published-after-upload"

    env = {
        **os.environ,
        "PATH": f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}",
        "FAKE_RELEASE_ANOMALOUS_PKG": package,
        "FAKE_RELEASE_ANOMALY_MODE": "steady_state",
        "FAKE_RELEASE_RELEASED_PACKAGES": "",
        "FAKE_RELEASE_VERSION": version,
        "FAKE_RELEASE_PUBLISHED_AFTER_UPLOAD_FILE": str(published_marker),
        "WORKSTATE_RELEASE_RUN_ID": "test-run-003",
    }
    result = subprocess.run(
        ["bash", str(repo / "scripts" / "release.sh"), "package", package],
        cwd=repo,
        env=env,
        text=True,
        capture_output=True,
    )

    combined = result.stdout + result.stderr
    assert result.returncode == 0, combined
    assert f"confirmed {package} {version} on PyPI" in combined

    run_dir = repo / "logs" / "release" / "test-run-003"
    summary_path = run_dir / "summary.json"
    final_summary_path = run_dir / "final-summary.md"
    assert summary_path.exists()
    assert final_summary_path.exists()

    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    final_summary = final_summary_path.read_text(encoding="utf-8")
    assert summary["command"] == "package"
    assert summary["status"] == "completed"
    assert summary["dry_run"] is False
    assert "test-run-003" in final_summary
