__version__ = "0.12.6"

from workstate_protocol.branch_naming import (
    TASK_REF_RE,
    derive_task_ref_candidates,
    format_suggested_branch_name,
)

from .api import (
    archive,
    archive_task_state,
    artifacts,
    audit_decision_ids,
    batch_record_review_findings,
    build_handoff_mcp,
    build_write_actor,
    close_slice,
    compact_session,
    configure_runtime,
    export_handoff_state,
    get_archived_task,
    get_artifact,
    get_compaction,
    get_handoff_state,
    get_latest_compaction,
    get_review_coverage,
    get_runtime_config,
    get_touched_files,
    get_verified_tests,
    handoff_close_check,
    import_handoff_state,
    init_state,
    list_active_tasks,
    list_next_actions,
    list_review_findings,
    list_review_runs,
    load_session,
    next_actions,
    post_merge_integrity_check,
    purge_artifacts,
    record_artifact,
    record_decision,
    record_event,
    record_file_touch,
    record_review_finding,
    record_review_run,
    record_test_result,
    render_cold_start_compaction,
    render_handoff,
    repair_review_finding_provenance,
    report_blocker,
    reset_runtime_config,
    review_findings,
    review_runs,
    run_doctor,
    search_artifacts,
    search_handoff,
    set_handoff_state,
    switch_task,
    terminal_guard_telemetry,
    update_next_actions,
    update_review_finding,
    update_task_status,
    validate_decision_id,
    working_tree_integrity_check,
)
from .compaction import CompactionSettings
from .config import ConsumerRootResolutionError, RuntimeConfig
from .core import PromptMetrics, ResolvedWriteContext, ReviewFindingDetails, TokenUsage, WriteActor
from .dashboard_rendering import (
    DashboardContext,
    DashboardExtension,
    DashboardSection,
    clear_dashboard_extensions,
    register_dashboard_extension,
)
from .enums import ReviewKind, ReviewScopeSource
from .plan_resolve import (
    PlanLocation,
    PlanPathNotRegistered,
    list_active_task_locations,
    plan_show_command,
    resolve_plan_location,
)
from .preflight import (
    CANONICAL_BLOCKER_KINDS,
    validate_finding_resolution,
    validate_review_ready,
)
from .shared_write_context import BranchMismatchError, UnresolvedTaskContextError


def generate_current_task_md(task_ref: str | None = None, write_file: bool = True) -> dict:
    """Backward-compatible alias for rendering CURRENT_TASK.json."""
    return render_handoff(kind="current_task", task_ref=task_ref, write_file=write_file)


def generate_dashboard_md(write_file: bool = True) -> dict:
    """Backward-compatible alias for rendering DASHBOARD.txt."""
    return render_handoff(kind="dashboard", write_file=write_file)


__all__ = [
    "__version__",
    "TASK_REF_RE",
    "DashboardContext",
    "DashboardExtension",
    "DashboardSection",
    "BranchMismatchError",
    "CompactionSettings",
    "ConsumerRootResolutionError",
    "UnresolvedTaskContextError",
    "PlanLocation",
    "PlanPathNotRegistered",
    "PromptMetrics",
    "ResolvedWriteContext",
    "RuntimeConfig",
    "ReviewFindingDetails",
    "ReviewKind",
    "ReviewScopeSource",
    "TokenUsage",
    "WriteActor",
    "artifacts",
    "archive",
    "archive_task_state",
    "audit_decision_ids",
    "build_handoff_mcp",
    "build_write_actor",
    "clear_dashboard_extensions",
    "close_slice",
    "compact_session",
    "configure_runtime",
    "derive_task_ref_candidates",
    "export_handoff_state",
    "format_suggested_branch_name",
    "generate_current_task_md",
    "generate_dashboard_md",
    "render_handoff",
    "register_dashboard_extension",
    "get_archived_task",
    "get_artifact",
    "get_compaction",
    "get_handoff_state",
    "get_latest_compaction",
    "get_review_coverage",
    "get_touched_files",
    "get_verified_tests",
    "get_runtime_config",
    "handoff_close_check",
    "import_handoff_state",
    "init_state",
    "load_session",
    "list_active_task_locations",
    "list_active_tasks",
    "list_next_actions",
    "list_review_findings",
    "list_review_runs",
    "next_actions",
    "plan_show_command",
    "post_merge_integrity_check",
    "purge_artifacts",
    "record_artifact",
    "record_decision",
    "record_event",
    "record_file_touch",
    "record_review_finding",
    "batch_record_review_findings",
    "record_review_run",
    "record_test_result",
    "render_cold_start_compaction",
    "repair_review_finding_provenance",
    "report_blocker",
    "resolve_plan_location",
    "reset_runtime_config",
    "review_findings",
    "review_runs",
    "run_doctor",
    "search_artifacts",
    "search_handoff",
    "set_handoff_state",
    "switch_task",
    "terminal_guard_telemetry",
    "validate_decision_id",
    "validate_finding_resolution",
    "validate_review_ready",
    "CANONICAL_BLOCKER_KINDS",
    "update_task_status",
    "update_next_actions",
    "update_review_finding",
    "working_tree_integrity_check",
]
