"""Legacy-mode generator contract tests.

After the WORKSTATE-REF-02 implementation note cutover, the legacy generator path
(``scripts/generate_agent_workflows.py`` invoked without ``--mode=plugin``)
emits only two consumer surfaces:

  - ``.github/prompts/<command_id>.prompt.md``  (VS Code Copilot)
  - ``docs/workstate/generated/codex-command-router.md``  (Codex router doc)

The ``.claude/commands/<id>.md``, ``.claude/skills/<slug>/SKILL.md``, and
``.codex/skills/<slug>/SKILL.md`` surfaces for *portable* manifest entries
are now owned by the plugin tree under ``packages/workstate-system/dist/``
(ADR-001). The legacy mode must not re-emit them and must actively prune
any pre-existing legacy emissions seeded from before the cutover so
consumers do not keep stale duplicates of the plugin-shipped content.

SKILL.md frontmatter, byte-identity, and casing concerns moved to
``test_plugin_emission.py`` along with the surfaces they describe.
"""

from __future__ import annotations

import json
import pathlib
import subprocess
import sys
import tempfile


PACKAGE_ROOT = pathlib.Path(__file__).resolve().parents[1]
PAYLOAD_ROOT = PACKAGE_ROOT / "workstate_system" / "payload"
GENERATOR = PAYLOAD_ROOT / "scripts" / "generate_agent_workflows.py"
MANIFEST = PAYLOAD_ROOT / "config" / "agent-workflows" / "portable_commands.json"
SKILLS_ROOT = PAYLOAD_ROOT / "skills"
GENERATOR_TAG = (
    "<!-- GENERATED by scripts/generate_agent_workflows.py; do not edit by hand. -->\n"
)


def _run_generator(target: pathlib.Path, *extra: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [
            sys.executable,
            str(GENERATOR),
            "--manifest",
            str(MANIFEST),
            "--target",
            str(target),
            *extra,
        ],
        cwd=str(PACKAGE_ROOT),
        capture_output=True,
        text=True,
        check=False,
    )


def _portable_command_ids_and_slugs() -> tuple[set[str], set[str]]:
    manifest = json.loads(MANIFEST.read_text())
    ids = {command["command_id"] for command in manifest["commands"]}
    slugs = {command["skill"] for command in manifest["commands"]}
    return ids, slugs


def test_legacy_mode_emits_prompts_and_router(tmp_path: pathlib.Path) -> None:
    """Copilot prompts and the codex-router doc remain the legacy-mode
    deliverables; both must materialize on a fresh write."""
    result = _run_generator(tmp_path)
    assert result.returncode == 0, (
        f"generator failed: stdout={result.stdout!r} stderr={result.stderr!r}"
    )
    ids, _ = _portable_command_ids_and_slugs()
    assert ids, "manifest must declare at least one portable command_id"
    prompts_dir = tmp_path / ".github" / "prompts"
    assert prompts_dir.is_dir()
    for command_id in ids:
        prompt = prompts_dir / f"{command_id}.prompt.md"
        assert prompt.is_file(), f"missing Copilot prompt for {command_id}"
    router = tmp_path / "docs" / "workstate" / "generated" / "codex-command-router.md"
    assert router.is_file(), "codex-command-router.md must be emitted in legacy mode"


def test_legacy_mode_does_not_emit_portable_skill_or_command_files(
    tmp_path: pathlib.Path,
) -> None:
    """WORKSTATE-REF-02 cutover invariant: the legacy generator no longer emits
    ``.claude/commands/<id>.md``, ``.claude/skills/<slug>/SKILL.md``, or
    ``.codex/skills/<slug>/SKILL.md`` for portable manifest entries."""
    result = _run_generator(tmp_path)
    assert result.returncode == 0
    ids, slugs = _portable_command_ids_and_slugs()
    for command_id in ids:
        legacy_command = tmp_path / ".claude" / "commands" / f"{command_id}.md"
        assert not legacy_command.exists(), (
            f"legacy mode must not emit .claude/commands/{command_id}.md "
            f"(plugin tree owns this surface)"
        )
    for slug in slugs:
        claude_skill = tmp_path / ".claude" / "skills" / slug / "SKILL.md"
        codex_skill = tmp_path / ".codex" / "skills" / slug / "SKILL.md"
        assert not claude_skill.exists(), (
            f"legacy mode must not emit .claude/skills/{slug}/SKILL.md "
            f"(plugin tree owns this surface)"
        )
        assert not codex_skill.exists(), (
            f"legacy mode must not emit .codex/skills/{slug}/SKILL.md "
            f"(plugin tree owns this surface)"
        )


def test_legacy_mode_prunes_pre_existing_legacy_files_for_portable_slugs(
    tmp_path: pathlib.Path,
) -> None:
    """WORKSTATE-REF-02-BR-03 regression: seed the target with legacy emissions for
    portable command_ids and skill slugs (the shape a consumer would
    carry forward from the pre-cutover generator), then run the legacy
    generator and confirm those files are removed.

    Both generator-tagged ``.claude/commands/<id>.md`` and the
    ``SKILL.md`` files under ``.claude/skills/<slug>/`` and
    ``.codex/skills/<slug>/`` must be cleaned up so consumers do not
    keep stale duplicates of the plugin-shipped content. A hand-authored
    slash command at the same id (no generator tag) is left alone.
    """
    ids, slugs = _portable_command_ids_and_slugs()
    sample_id = sorted(ids)[0]
    sample_slug = sorted(slugs)[0]

    seeded_command = tmp_path / ".claude" / "commands" / f"{sample_id}.md"
    seeded_command.parent.mkdir(parents=True, exist_ok=True)
    seeded_command.write_text(GENERATOR_TAG + "# stale legacy emission\n")

    hand_authored = tmp_path / ".claude" / "commands" / "hand-authored.md"
    hand_authored.write_text("# user-owned command — must survive\n")

    seeded_claude_skill = (
        tmp_path / ".claude" / "skills" / sample_slug / "SKILL.md"
    )
    seeded_claude_skill.parent.mkdir(parents=True, exist_ok=True)
    seeded_claude_skill.write_text(
        f"---\nname: {sample_slug}\n---\n\nstale legacy skill\n"
    )

    seeded_codex_skill = (
        tmp_path / ".codex" / "skills" / sample_slug / "SKILL.md"
    )
    seeded_codex_skill.parent.mkdir(parents=True, exist_ok=True)
    seeded_codex_skill.write_text(
        f"---\nname: {sample_slug}\n---\n\nstale legacy skill\n"
    )

    result = _run_generator(tmp_path)
    assert result.returncode == 0, (
        f"generator failed: stdout={result.stdout!r} stderr={result.stderr!r}"
    )

    assert not seeded_command.exists(), (
        "generator-tagged legacy .claude/commands/<id>.md must be pruned"
    )
    assert not seeded_claude_skill.exists(), (
        "legacy .claude/skills/<slug>/SKILL.md must be pruned for portable slugs"
    )
    assert not seeded_codex_skill.exists(), (
        "legacy .codex/skills/<slug>/SKILL.md must be pruned for portable slugs"
    )
    assert hand_authored.exists() and "user-owned" in hand_authored.read_text(), (
        "hand-authored slash commands (no generator tag) must be preserved"
    )


def test_legacy_mode_preserves_skill_md_at_portable_slug_path_with_non_matching_name(
    tmp_path: pathlib.Path,
) -> None:
    """WORKSTATE-REF-02-BR-04 safety gate: pruning legacy SKILL.md at portable slug
    paths is gated on frontmatter ``name`` matching the slug. A file whose
    frontmatter declares a different ``name`` (e.g. a project-local skill
    that happens to live at a colliding path) must NOT be deleted by the
    legacy-mode prune step. The gate prevents the prune helper from being
    a foot-gun for contributors who add project-local SKILL.md files at a
    portable slug path without reading plugin-distribution.md.
    """
    _, slugs = _portable_command_ids_and_slugs()
    sample_slug = sorted(slugs)[0]

    preserved_claude_skill = (
        tmp_path / ".claude" / "skills" / sample_slug / "SKILL.md"
    )
    preserved_claude_skill.parent.mkdir(parents=True, exist_ok=True)
    preserved_claude_skill.write_text(
        "---\nname: project-local-override\n---\n\nhand-authored override\n"
    )

    preserved_codex_skill = (
        tmp_path / ".codex" / "skills" / sample_slug / "SKILL.md"
    )
    preserved_codex_skill.parent.mkdir(parents=True, exist_ok=True)
    preserved_codex_skill.write_text(
        "---\nname: project-local-override\n---\n\nhand-authored override\n"
    )

    result = _run_generator(tmp_path)
    assert result.returncode == 0, (
        f"generator failed: stdout={result.stdout!r} stderr={result.stderr!r}"
    )

    assert preserved_claude_skill.exists(), (
        "SKILL.md with non-matching frontmatter name must be preserved at "
        ".claude/skills/<slug>/SKILL.md (safety gate against accidental "
        "clobber of project-local overrides)"
    )
    assert "hand-authored override" in preserved_claude_skill.read_text()
    assert preserved_codex_skill.exists(), (
        "SKILL.md with non-matching frontmatter name must be preserved at "
        ".codex/skills/<slug>/SKILL.md"
    )
    assert "hand-authored override" in preserved_codex_skill.read_text()


def test_legacy_mode_does_not_prune_lowercase_skill_md_in_unrelated_dirs(
    tmp_path: pathlib.Path,
) -> None:
    """Casing-collapse safety: the prune helper deletes the legacy
    lowercase ``skill.md`` sibling under portable slug dirs (Codex
    discovery is case-sensitive), but only inside ``.claude/skills/<slug>/``
    and ``.codex/skills/<slug>/``. A ``skill.md`` elsewhere in the target
    is untouched."""
    _, slugs = _portable_command_ids_and_slugs()
    sample_slug = sorted(slugs)[0]

    lowercase_in_slug_dir = (
        tmp_path / ".claude" / "skills" / sample_slug / "skill.md"
    )
    lowercase_in_slug_dir.parent.mkdir(parents=True, exist_ok=True)
    lowercase_in_slug_dir.write_text(
        f"---\nname: {sample_slug}\n---\n\nlegacy lowercase emission\n"
    )

    unrelated = tmp_path / "docs" / "skill.md"
    unrelated.parent.mkdir(parents=True, exist_ok=True)
    unrelated.write_text("user-owned docs file with same basename\n")

    result = _run_generator(tmp_path)
    assert result.returncode == 0

    assert not lowercase_in_slug_dir.exists(), (
        "lowercase skill.md inside a portable slug dir must be pruned "
        "(Codex discovery is case-sensitive)"
    )
    assert unrelated.exists() and "user-owned" in unrelated.read_text(), (
        "skill.md outside .claude/skills/<slug>/ or .codex/skills/<slug>/ "
        "must be left alone"
    )


def test_handoff_lifecycle_compaction_guidance_reaches_generated_prompt_surface(
    tmp_path: pathlib.Path,
) -> None:
    """Load-bearing prompt content for handoff-lifecycle must survive the
    legacy emission path."""
    result = _run_generator(tmp_path)
    assert result.returncode == 0
    body = (
        tmp_path / ".github" / "prompts" / "handoff-lifecycle.prompt.md"
    ).read_text()
    assert "compaction_recommended: true" in body
    assert 'compaction(operation="record"' in body
    assert "unknown_harness: warn_and_skip" in body


def test_check_mode_passes_immediately_after_write() -> None:
    """--check must be a no-op against a freshly-written legacy tree."""
    with tempfile.TemporaryDirectory() as raw:
        target = pathlib.Path(raw)
        write_result = _run_generator(target)
        assert write_result.returncode == 0
        check_result = _run_generator(target, "--check")
        assert check_result.returncode == 0, (
            f"--check failed after fresh write: stdout={check_result.stdout!r} "
            f"stderr={check_result.stderr!r}"
        )
