"""implementation note S3: the shipped overlay payload is co-located under
``workstate_system/payload/`` and ships by "ship-the-package" (no force-include).

These tests gate the atomic cutover:
- ``data_root()`` resolves to ``…/workstate_system/payload`` and that tree exists.
- the built wheel's ``workstate_system/payload/`` tree is byte-identical to the
  source ``payload/`` tree (the real publish/delivery parity gate).
- NO internal-only material (``evals``/``adrs``/``generated``) lives under
  ``payload/`` — this single structural guard replaces the hand-curated
  force-include co-move list: drop an internal file under ``payload/`` and it
  goes red.
"""

from __future__ import annotations

import filecmp
import shutil
import subprocess
import zipfile
from pathlib import Path

import pytest

PKG_DIR = Path(__file__).resolve().parents[1]  # packages/workstate-system
SOURCE_PAYLOAD = PKG_DIR / "workstate_system" / "payload"

# Surfaces that MUST be present under payload/ (the shipped overlay).
EXPECTED_SURFACES = (
    "skills",
    "scripts/hooks",
    "scripts/generate_agent_workflows.py",
    "scripts/check_workflow_facade.py",
    "scripts/validate_claude_settings_pin.py",
    "scripts/workstate/lifecycle",
    "config/agent-workflows",
    "docs/workstate/contracts",
    "docs/workstate/rules",
    "docs/workstate/templates",
    "docs/workstate/maps",
    "Makefile.d/workflows.mk",
    ".github/hooks",
)

# Tokens that mark internal-only material; none may appear under payload/.
FORBIDDEN_TOKENS = ("/evals", "/adrs", "/generated")


def test_data_root_resolves_to_payload() -> None:
    from workstate_system import data_root

    root = Path(data_root())
    assert root.name == "payload" and root.parent.name == "workstate_system", (
        f"data_root() must end in workstate_system/payload, got {root}"
    )
    assert root.is_dir(), f"payload root does not exist: {root}"
    assert (root / "skills").is_dir(), "payload must contain skills/"


def test_source_payload_contains_every_expected_surface() -> None:
    missing = [s for s in EXPECTED_SURFACES if not (SOURCE_PAYLOAD / s).exists()]
    assert not missing, f"payload/ is missing expected surfaces: {missing}"


def test_no_internal_material_under_payload() -> None:
    """Structural privacy guard — replaces the force-include co-move list."""
    leaked = [
        str(p.relative_to(SOURCE_PAYLOAD))
        for p in SOURCE_PAYLOAD.rglob("*")
        for token in FORBIDDEN_TOKENS
        if token in f"/{p.relative_to(SOURCE_PAYLOAD).as_posix()}"
    ]
    assert not leaked, f"internal-only material leaked under payload/: {leaked}"


def _build_wheel(out_dir: Path) -> Path:
    uv = shutil.which("uv")
    if uv is None:
        pytest.skip("uv not available to build the wheel")
    proc = subprocess.run(
        [uv, "build", "--wheel", "--out-dir", str(out_dir), str(PKG_DIR)],
        capture_output=True,
        text=True,
        timeout=300,
    )
    assert proc.returncode == 0, proc.stderr
    wheels = list(out_dir.glob("*.whl"))
    assert len(wheels) == 1, [w.name for w in wheels]
    return wheels[0]


def _is_bytecode(rel: str) -> bool:
    """Locally-generated bytecode is never part of the shipped payload — the
    lifecycle subprocess tests write ``__pycache__`` into the in-tree source
    when they run before this one, so ignore it for the parity diff."""
    return "__pycache__/" in rel or rel.endswith(".pyc")


def _diff_trees(a: Path, b: Path) -> list[str]:
    """Return relative paths that differ between two trees (content + presence)."""
    diffs: list[str] = []
    a_files = {
        p.relative_to(a).as_posix()
        for p in a.rglob("*")
        if p.is_file() and not _is_bytecode(p.relative_to(a).as_posix())
    }
    b_files = {
        p.relative_to(b).as_posix()
        for p in b.rglob("*")
        if p.is_file() and not _is_bytecode(p.relative_to(b).as_posix())
    }
    for rel in sorted(a_files ^ b_files):
        diffs.append(f"presence: {rel}")
    for rel in sorted(a_files & b_files):
        if not filecmp.cmp(a / rel, b / rel, shallow=False):
            diffs.append(f"content: {rel}")
    return diffs


def test_wheel_payload_is_byte_identical_to_source(tmp_path: Path) -> None:
    """The installed wheel's payload tree must equal the source payload tree.

    Mirrors the faithful-copy parity guarantee for the package delivery source:
    'ship the package' must deliver exactly what the monorepo dogfoods."""
    wheel = _build_wheel(tmp_path / "dist")
    unpacked = tmp_path / "site"
    with zipfile.ZipFile(wheel) as zf:
        zf.extractall(unpacked)
    installed_payload = unpacked / "workstate_system" / "payload"
    assert installed_payload.is_dir(), "wheel did not ship workstate_system/payload/"
    diffs = _diff_trees(SOURCE_PAYLOAD, installed_payload)
    assert not diffs, f"wheel payload diverged from source payload: {diffs}"
