#!/usr/bin/env python3
"""Pin generator + drift gate for the ``workstate-stack`` meta-package.

``workstate-stack`` is the single version anchor consumers install
(implementation note): its ``dependencies`` block carries exact ``==`` pins on every
published runtime member, so one ``pip install --upgrade workstate-stack``
moves the whole stack. Those pins are **never hand-edited** — this script is
the only writer:

* ``stack_pins.py sync`` / ``make stack-pins-sync`` — regenerate the pins
  between the ``STACK PINS`` sentinels in
  ``packages/workstate-stack/pyproject.toml`` from each member's own
  ``pyproject.toml`` version (resolved via ``config/release/packages.json``
  paths).
* ``stack_pins.py check`` / ``make stack-pins-check`` — fail (exit 1) when
  any pin drifts from its member version, a member pin is missing, or the
  sentinel block is gone. Wired into ``make check-all`` so a member bump
  cannot ship without moving the meta pins (same fail-closed posture as
  ``scripts/check_mcp_pin_drift.py``).

The member set is a deliberate constant, not "everything publishable":
``mcp-workstate-canvas`` is private (``publish=false``) and
``workstate-codex-bridge`` is an optional host-specific bridge (future
``workstate-stack[codex]`` extra), so neither belongs in the base anchor.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
STACK_PYPROJECT_RELPATH = "packages/workstate-stack/pyproject.toml"
PYPROJECT_VERSION_RE = re.compile(r'(?m)^version\s*=\s*"([^"]+)"\s*$')

# Generated-block sentinels inside the stack pyproject ``dependencies`` array.
PINS_SENTINEL_BEGIN = (
    "    # >>> STACK PINS (generated by scripts/stack_pins.py; "
    "make stack-pins-sync) >>>"
)
PINS_SENTINEL_END = "    # <<< STACK PINS <<<"

# Published runtime members anchored by the meta-package, in release order
# (dependency-first; the payload package last). Excludes the private
# ``mcp-workstate-canvas`` and the optional ``workstate-codex-bridge``.
STACK_MEMBERS: tuple[str, ...] = (
    "workstate-protocol",
    "mcp-workstate-handoff",
    "mcp-workstate-orchestrator",
    "workstate-bootstrap",
    "workstate-system",
)


def _load_release_packages(repo_root: Path) -> list[dict[str, object]]:
    manifest_path = repo_root / "config" / "release" / "packages.json"
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    packages = data.get("packages")
    if not isinstance(packages, list):
        raise SystemExit(f"manifest must contain a 'packages' list: {manifest_path}")
    return packages


def member_versions(repo_root: Path) -> tuple[dict[str, str], list[str]]:
    """Resolve each stack member's published version from its pyproject.

    Returns ``(versions, errors)``; a member with no manifest entry, missing
    pyproject, or unparsable version lands in ``errors``.
    """
    path_by_distribution = {
        str(p.get("distribution")): str(p.get("path"))
        for p in _load_release_packages(repo_root)
        if p.get("distribution") and p.get("path")
    }
    versions: dict[str, str] = {}
    errors: list[str] = []
    for member in STACK_MEMBERS:
        relpath = path_by_distribution.get(member)
        if relpath is None:
            errors.append(f"{member}: not in config/release/packages.json")
            continue
        pyproject = repo_root / relpath / "pyproject.toml"
        if not pyproject.is_file():
            errors.append(f"{member}: missing {pyproject}")
            continue
        match = PYPROJECT_VERSION_RE.search(pyproject.read_text(encoding="utf-8"))
        if match is None:
            errors.append(f"{member}: no version field in {pyproject}")
            continue
        versions[member] = match.group(1)
    return versions, errors


def _split_pins_block(text: str) -> tuple[str, str, str] | None:
    """Split stack pyproject text into (before, pins-block, after).

    Returns ``None`` when the sentinel block is absent or malformed.
    """
    begin = text.find(PINS_SENTINEL_BEGIN)
    end = text.find(PINS_SENTINEL_END)
    if begin == -1 or end == -1 or end < begin:
        return None
    block_start = begin + len(PINS_SENTINEL_BEGIN) + 1  # past sentinel + newline
    return text[:block_start], text[block_start:end], text[end:]


def current_pins(text: str) -> dict[str, str] | None:
    """Parse ``"<distribution>==<version>"`` lines inside the sentinel block."""
    parts = _split_pins_block(text)
    if parts is None:
        return None
    pins: dict[str, str] = {}
    for line in parts[1].splitlines():
        match = re.match(r'\s*"([A-Za-z0-9._-]+)==([^"]+)",?\s*$', line)
        if match:
            pins[match.group(1)] = match.group(2)
    return pins


def render_pins(versions: dict[str, str]) -> str:
    return "".join(
        f'    "{member}=={versions[member]}",\n'
        for member in STACK_MEMBERS
        if member in versions
    )


def check(repo_root: Path) -> tuple[bool, list[str]]:
    """Steady-state gate: every member pin equals the member's own version."""
    pyproject = repo_root / STACK_PYPROJECT_RELPATH
    if not pyproject.is_file():
        return False, [f"missing {STACK_PYPROJECT_RELPATH}"]
    versions, errors = member_versions(repo_root)
    messages = list(errors)

    pins = current_pins(pyproject.read_text(encoding="utf-8"))
    if pins is None:
        messages.append(
            f"no STACK PINS sentinel block in {STACK_PYPROJECT_RELPATH}; "
            "restore the generated block, then run `make stack-pins-sync`"
        )
        return False, messages

    ok = not messages
    for member in STACK_MEMBERS:
        expected = versions.get(member)
        if expected is None:
            ok = False
            continue
        found = pins.get(member)
        if found is None:
            ok = False
            messages.append(
                f"DRIFT {member}: no pin (expected =={expected}); "
                "run `make stack-pins-sync`"
            )
        elif found != expected:
            ok = False
            messages.append(
                f"DRIFT {member}: pinned =={found} but pyproject says "
                f"{expected}; run `make stack-pins-sync`"
            )
    stray = sorted(set(pins) - set(STACK_MEMBERS))
    if stray:
        ok = False
        messages.append(
            "non-member pins in generated block (remove or promote "
            f"deliberately): {', '.join(stray)}"
        )
    if ok:
        messages.append(
            "ok: workstate-stack pins match member versions ("
            + ", ".join(f"{m}=={versions[m]}" for m in STACK_MEMBERS)
            + ")"
        )
    return ok, messages


def sync(repo_root: Path) -> bool:
    """Rewrite the generated pins block. Returns True when the file changed."""
    pyproject = repo_root / STACK_PYPROJECT_RELPATH
    if not pyproject.is_file():
        raise SystemExit(f"missing {STACK_PYPROJECT_RELPATH}")
    versions, errors = member_versions(repo_root)
    if errors:
        raise SystemExit("cannot sync pins:\n" + "\n".join(f"  {e}" for e in errors))

    text = pyproject.read_text(encoding="utf-8")
    parts = _split_pins_block(text)
    if parts is None:
        raise SystemExit(
            f"no STACK PINS sentinel block in {STACK_PYPROJECT_RELPATH}; "
            "restore the generated block before syncing"
        )
    before, _, after = parts
    rewritten = before + render_pins(versions) + after
    if rewritten == text:
        return False
    pyproject.write_text(rewritten, encoding="utf-8")
    return True


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Regenerate or verify the workstate-stack exact pins."
    )
    parser.add_argument("command", choices=("sync", "check"))
    parser.add_argument(
        "--repo-root",
        default=str(REPO_ROOT),
        help="Repository root (defaults to the monorepo containing this script).",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    repo_root = Path(args.repo_root).resolve()
    if args.command == "sync":
        changed = sync(repo_root)
        print(
            "stack-pins-sync: pins rewritten"
            if changed
            else "stack-pins-sync: already in sync"
        )
        return 0
    ok, messages = check(repo_root)
    stream = sys.stdout if ok else sys.stderr
    for line in messages:
        print(line, file=stream)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
