#!/usr/bin/env python3
"""Generate host-specific workflow adapters from the canonical manifest.

Canonical sources (implementation note step 1):
  - manifest:  config/agent-workflows/portable_commands.json
  - skills:    skills/<slug>/skill.yaml + skills/<slug>/body.md

Generated outputs (one per agent surface):
  - .claude/skills/<slug>/SKILL.md  (Claude-shape skill files)
  - .github/prompts/<id>.prompt.md  (VS Code Copilot prompts)
  - <codex-router-out>/codex-command-router.md  (Codex CLI router)
  - .codex/skills/<slug>/SKILL.md   (Codex-shape skill files)

The previous layout treated .claude/skills/<slug>/SKILL.md as canonical
and symlinked the Codex skill at it. The neutral layout makes both
agent surfaces generated artifacts so the canonical source is
model-agnostic.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

try:
    import yaml
except ImportError as exc:  # pragma: no cover - PyYAML is a hard dep here
    raise SystemExit("PyYAML is required to read skill.yaml") from exc

# Repo root is 5 parents up after the implementation note S3 move into
# workstate_system/payload/scripts/ (scripts -> payload -> workstate_system ->
# workstate-system -> packages -> <repo root>). Only used as a fresh-clone
# fallback before `uv sync`; masked when workstate_protocol is installed.
_PROTOCOL_SRC = (
    Path(__file__).resolve().parents[5] / "packages" / "workstate-protocol" / "src"
)
if _PROTOCOL_SRC.is_dir() and str(_PROTOCOL_SRC) not in sys.path:
    sys.path.insert(0, str(_PROTOCOL_SRC))

from pydantic import ValidationError

from workstate_protocol import DOCS_MIRROR_DIR
from workstate_protocol.bootstrap import (
    PluginEffectiveLock,
    PluginMcpServerPatch,
    PluginOverrideManifest,
)

# Canonical docs-mirror "generated" output dir, derived from the shared
# constant so the runtime-path rename lives in exactly one place.
_GENERATED_DOCS_SUBDIR = (*DOCS_MIRROR_DIR.split("/"), "generated")

GENERATOR_TAG = (
    "<!-- GENERATED by scripts/generate_agent_workflows.py; do not edit by hand. -->\n"
)
PROMPT_HEADER = "# /{command_id}\n\n"
CODEX_ROUTER_HEADER = "# Portable Command Router\n\n"
CODEX_ROUTER_BEGIN = "<!-- BEGIN GENERATED: codex-command-router -->"
CODEX_ROUTER_END = "<!-- END GENERATED: codex-command-router -->"
CODEX_ROUTER_CONSUMERS = (
    Path("docs/workstate/instructions.md"),
    Path("CLAUDE.md"),
)

_VALID_COMMAND_MODES = frozenset({"guide", "verify", "write"})

_PLUGIN_NAME = "workstate-system"
_PLUGIN_DESCRIPTION = (
    "Cross-harness agentic skills, slash commands, and MCP server registration."
)
_PLUGIN_OVERRIDE_MANIFEST = "overrides.yaml"
_PLUGIN_EFFECTIVE_LOCK = "plugin-lock.json"
_PLUGIN_HARNESSES: tuple[tuple[str, str], ...] = (
    ("claude", ".claude-plugin"),
    ("codex", ".codex-plugin"),
    ("cursor", ".cursor-plugin"),
    ("grok", ".grok-plugin"),
)
# Valid values for the mcp_servers.yaml `registration` ownership table
# (implementation note): `root` = bootstrap-written root surface registers the MCP
# servers and the plugin tree ships skills only; `plugin` = the plugin
# tree registers them via plugin.json mcpServers + sibling .mcp.json.
_MCP_REGISTRATION_OWNERS: frozenset[str] = frozenset({"root", "plugin"})
_HARNESS_ROUTING_BEGIN = "<!-- BEGIN GENERATED: harness-routing-table -->"
_HARNESS_ROUTING_END = "<!-- END GENERATED: harness-routing-table -->"
_HARNESS_PROTOCOL_REL = (
    Path("docs") / "workstate" / "contracts" / "harness-protocol.yaml"
)


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _default_manifest_path() -> Path:
    return _repo_root() / "config" / "agent-workflows" / "portable_commands.json"


def _default_harness_protocol_path() -> Path:
    return _repo_root() / _HARNESS_PROTOCOL_REL


def _load_harness_protocol(path: Path | None = None) -> dict:
    protocol_path = path or _default_harness_protocol_path()
    try:
        payload = yaml.safe_load(protocol_path.read_text()) or {}
    except FileNotFoundError as exc:
        raise SystemExit(f"harness protocol not found: {protocol_path}") from exc
    if not isinstance(payload, dict):
        raise SystemExit(f"{protocol_path}: harness protocol must parse to a mapping")
    return payload


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=_default_manifest_path())
    parser.add_argument(
        "--skills-source-root",
        type=Path,
        help="Directory containing the canonical skills/<slug>/{skill.yaml, body.md}. "
        "Defaults to <manifest-package>/skills.",
    )
    parser.add_argument(
        "--claude-skills-root",
        type=Path,
        help="Deprecated alias for --skills-source-root (kept for one release).",
    )
    parser.add_argument(
        "--target",
        type=Path,
        help="Convenience: when set, default every per-agent --*-out path to this consumer "
        "repo root's standard locations. Per-agent flags still override.",
    )
    parser.add_argument(
        "--claude-out", type=Path, help="Output dir for Claude Code commands."
    )
    parser.add_argument(
        "--claude-skills-out",
        type=Path,
        help="Output dir for generated Claude SKILL.md files.",
    )
    parser.add_argument(
        "--prompts-out", type=Path, help="Output dir for VS Code Copilot prompts."
    )
    parser.add_argument(
        "--codex-router-out", type=Path, help="Output dir for the Codex router doc."
    )
    parser.add_argument(
        "--codex-skills-out",
        type=Path,
        help="Output dir for generated Codex skill files.",
    )
    parser.add_argument(
        "--check-codex-router-blocks",
        action="store_true",
        help="Fail if the marker-delimited Codex router blocks drift from the manifest-rendered content.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated outputs differ from committed files.",
    )
    parser.add_argument(
        "--check-coherence",
        action="store_true",
        help="Fail if installed hook surfaces at --target (or the package payload root) have error-severity coherence findings.",
    )
    parser.add_argument(
        "--mode",
        choices=("legacy", "plugin"),
        default="legacy",
        help="Generator emission mode. 'legacy' (default) emits per-host "
        "adapter files; 'plugin' (internal) emits Claude/Codex/Grok plugin trees "
        "from the canonical skills + portable_commands + mcp_servers.yaml inputs.",
    )
    parser.add_argument(
        "--plugin-mcp-servers",
        type=Path,
        help="Path to mcp_servers.yaml (required when --mode=plugin). "
        "Defaults to <manifest-package>/config/agent-workflows/mcp_servers.yaml.",
    )
    parser.add_argument(
        "--plugin-out",
        type=Path,
        help="Destination root for emitted plugin trees (required when --mode=plugin). "
        "Trees are written to <plugin-out>/{claude,codex,cursor,grok}/.",
    )
    parser.add_argument(
        "--plugin-overrides",
        type=Path,
        help="Optional consumer override root. When set, plugin mode composes an effective tree "
        "from canonical inputs plus <plugin-overrides>/overrides.yaml.",
    )
    parser.add_argument(
        "--plugin-base-remote-sha",
        type=str,
        help="Resolved 40-char upstream git SHA for plugin-lock.json when composing overrides.",
    )
    parser.add_argument(
        "--plugin-passthrough-lock",
        action="store_true",
        help="internal always-effective mode: emit plugin-lock.json with mode=passthrough "
        "entries for every component when composing an effective tree with no overrides. "
        "Requires --plugin-base-remote-sha; mutually exclusive with --plugin-overrides.",
    )
    return parser.parse_args()


def _load_manifest(path: Path) -> dict:
    try:
        payload = json.loads(path.read_text())
    except FileNotFoundError as exc:
        raise SystemExit(f"Manifest not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Invalid JSON in {path}: {exc}") from exc

    if not isinstance(payload, dict):
        raise SystemExit(f"{path} must contain a JSON object.")

    version = payload.get("version")
    if version not in {1, 2}:
        raise SystemExit(
            f"{path} must declare version=1 or version=2; found {version!r}."
        )

    commands = payload.get("commands")
    if not isinstance(commands, list) or not commands:
        raise SystemExit(f"{path} must declare a non-empty commands list.")

    global_instructions = payload.get("global_instructions", [])
    if global_instructions != [] and (
        not isinstance(global_instructions, list)
        or not all(
            isinstance(item, str) and item.strip() for item in global_instructions
        )
    ):
        raise SystemExit(
            f"{path} must declare global_instructions as a list of non-empty strings when present."
        )

    seen_ids: set[str] = set()
    for index, command in enumerate(commands):
        _validate_command(command, index)
        command_id = command["command_id"]
        if command_id in seen_ids:
            raise SystemExit(f"Duplicate command_id {command_id!r} in {path}.")
        seen_ids.add(command_id)

    hooks = payload.get("hooks", [])
    if hooks != [] and not isinstance(hooks, list):
        raise SystemExit(f"{path} must declare hooks as a list when present.")
    for index, hook in enumerate(hooks):
        _validate_hook(hook, index)
    return payload


def _validate_command(command: object, index: int) -> None:
    if not isinstance(command, dict):
        raise SystemExit(f"commands[{index}] must be an object.")

    required_string_fields = (
        "command_id",
        "skill",
        "makefile_target",
        "description",
        "execution_context",
    )
    for field in required_string_fields:
        value = command.get(field)
        if not isinstance(value, str) or not value.strip():
            raise SystemExit(f"commands[{index}].{field} must be a non-empty string.")

    command_id = command["command_id"]
    if any(ch not in "abcdefghijklmnopqrstuvwxyz0123456789-" for ch in command_id):
        raise SystemExit(
            f"commands[{index}].command_id must be lowercase kebab-case; found {command_id!r}."
        )

    # internal1: declare-or-fail mode field. The portable-commands
    # interaction-mode taxonomy is the spec contract between MCP-writer
    # skills and consumer routing; every command must pick one of three.
    mode = command.get("mode")
    if mode is None:
        raise SystemExit(
            f"commands[{index}].mode is required; declare one of "
            f"'guide', 'verify', 'write'."
        )
    if mode not in _VALID_COMMAND_MODES:
        raise SystemExit(
            f"commands[{index}].mode must be one of "
            f"{sorted(_VALID_COMMAND_MODES)!r}; found mode={mode!r}."
        )

    loop = command.get("loop")
    if (
        not isinstance(loop, list)
        or not loop
        or not all(isinstance(item, str) and item.strip() for item in loop)
    ):
        raise SystemExit(f"commands[{index}].loop must be a non-empty list of strings.")

    secondary_targets = command.get("secondary_targets", [])
    if secondary_targets != [] and (
        not isinstance(secondary_targets, list)
        or not all(isinstance(item, str) and item.strip() for item in secondary_targets)
    ):
        raise SystemExit(
            f"commands[{index}].secondary_targets must be a list of strings when present."
        )

    argument_schema = command.get("argument_schema")
    if not isinstance(argument_schema, list):
        raise SystemExit(f"commands[{index}].argument_schema must be a list.")
    for arg_index, arg in enumerate(argument_schema):
        if not isinstance(arg, dict):
            raise SystemExit(
                f"commands[{index}].argument_schema[{arg_index}] must be an object."
            )
        name = arg.get("name")
        description = arg.get("description")
        required = arg.get("required")
        if not isinstance(name, str) or not name.strip():
            raise SystemExit(
                f"commands[{index}].argument_schema[{arg_index}].name must be a non-empty string."
            )
        if not isinstance(description, str) or not description.strip():
            raise SystemExit(
                f"commands[{index}].argument_schema[{arg_index}].description must be a non-empty string."
            )
        if not isinstance(required, bool):
            raise SystemExit(
                f"commands[{index}].argument_schema[{arg_index}].required must be boolean."
            )


def _validate_hook(hook: object, index: int) -> None:
    if not isinstance(hook, dict):
        raise SystemExit(f"hooks[{index}] must be an object.")

    required_string_fields = ("hook_id", "description", "trigger")
    for field in required_string_fields:
        value = hook.get(field)
        if not isinstance(value, str) or not value.strip():
            raise SystemExit(f"hooks[{index}].{field} must be a non-empty string.")

    required_artifacts = hook.get("required_artifacts")
    if not isinstance(required_artifacts, list) or not required_artifacts:
        raise SystemExit(f"hooks[{index}].required_artifacts must be a non-empty list.")
    adapters = hook.get("adapters")
    if not isinstance(adapters, list) or not adapters:
        raise SystemExit(f"hooks[{index}].adapters must be a non-empty list.")
    for adapter_index, adapter in enumerate(adapters):
        _validate_hook_adapter(adapter, index, adapter_index)


def _validate_hook_adapter(
    adapter: object, hook_index: int, adapter_index: int
) -> None:
    prefix = f"hooks[{hook_index}].adapters[{adapter_index}]"
    if not isinstance(adapter, dict):
        raise SystemExit(f"{prefix} must be an object.")
    harness = adapter.get("harness")
    if not isinstance(harness, str) or not harness.strip():
        raise SystemExit(f"{prefix}.harness must be a non-empty string.")
    patch = adapter.get("patch")
    if not isinstance(patch, dict):
        raise SystemExit(f"{prefix}.patch must be an object.")
    entry = patch.get("entry")
    if not isinstance(entry, dict):
        raise SystemExit(f"{prefix}.patch.entry must be an object.")

    if harness in {"claude-code", "grok"}:
        nested_hooks = entry.get("hooks")
        if not isinstance(nested_hooks, list) or not nested_hooks:
            raise SystemExit(
                f"{prefix}.patch.entry must use the matcher + hooks[] shape "
                f"required by {harness}."
            )
        matcher = entry.get("matcher")
        if not isinstance(matcher, str):
            raise SystemExit(f"{prefix}.patch.entry.matcher must be a string.")
        for hook_entry_index, hook_entry in enumerate(nested_hooks):
            if not isinstance(hook_entry, dict):
                raise SystemExit(
                    f"{prefix}.patch.entry.hooks[{hook_entry_index}] must be an object."
                )
            if hook_entry.get("type") != "command":
                raise SystemExit(
                    f"{prefix}.patch.entry.hooks[{hook_entry_index}].type must be 'command'."
                )
            command = hook_entry.get("command")
            if not isinstance(command, str) or not command.strip():
                raise SystemExit(
                    f"{prefix}.patch.entry.hooks[{hook_entry_index}].command must be a non-empty string."
                )
    else:
        # codex/vscode adapters use the flat entry shape; validate the
        # command symmetrically with the nested claude shape above.
        command = entry.get("command")
        if not isinstance(command, str) or not command.strip():
            raise SystemExit(
                f"{prefix}.patch.entry.command must be a non-empty string."
            )


def _render_arguments(command: dict) -> list[str]:
    args = command.get("argument_schema", [])
    if not args:
        return ["Arguments: none."]
    lines = ["Arguments:"]
    for arg in args:
        status = "required" if arg["required"] else "optional"
        lines.append(f"- `{arg['name']}` ({status}): {arg['description']}")
    return lines


def _render_targets(command: dict) -> list[str]:
    lines = [f"Makefile entry point: `{command['makefile_target']}`"]
    secondary = command.get("secondary_targets", [])
    if secondary:
        lines.append("Secondary entry points:")
        lines.extend(f"- `{target}`" for target in secondary)
    return lines


def _global_instruction_items(manifest: dict) -> list[str]:
    instructions = manifest.get("global_instructions") or []
    return list(instructions)


def _global_instruction_bullets(manifest: dict) -> list[str]:
    return [f"- {item}" for item in _global_instruction_items(manifest)]


def _render_global_instructions(manifest: dict) -> list[str]:
    bullets = _global_instruction_bullets(manifest)
    if not bullets:
        return []
    return [
        "Global instructions:",
        "",
        *bullets,
        "",
    ]


def _render_prompt_with_guidance(
    command: dict, prompt_guidance: str | None, manifest: dict
) -> str:
    lines = [
        GENERATOR_TAG.rstrip(),
        "",
        PROMPT_HEADER.format(command_id=command["command_id"]).rstrip(),
        "",
        *_render_global_instructions(manifest),
        f"Load the `{command['skill']}` skill for this workflow.",
        "",
        f"Description: {command['description']}",
        "",
        f"Mode: `{command['mode']}`",
        "",
        *_render_targets(command),
        "",
        *_render_arguments(command),
        "",
        f"Execution context: {command['execution_context']}",
        "",
        "Loop:",
        *(f"- {item}" for item in command["loop"]),
        "",
    ]
    if prompt_guidance:
        lines.extend(
            [
                "Canonical Skill Guidance:",
                "",
                *prompt_guidance.rstrip().splitlines(),
                "",
            ]
        )
    return "\n".join(lines)


def _extract_markdown_section(body: str, heading: str) -> str | None:
    lines = body.splitlines()
    marker = f"## {heading}"
    start: int | None = None

    for index, line in enumerate(lines):
        if line.strip() == marker:
            start = index
            break

    if start is None:
        return None

    end = len(lines)
    for index in range(start + 1, len(lines)):
        if lines[index].startswith("## "):
            end = index
            break

    return "\n".join(lines[start:end]).strip()


def _extract_prompt_guidance(structured: dict, body: str) -> str | None:
    _, generator = _strip_generator_metadata(structured)
    requested_sections = generator.get("prompt_body_sections") or []
    if not isinstance(requested_sections, list):
        requested_sections = []

    # VS Code Copilot does not consume the Claude/Codex plugin tree, so
    # its generated prompt must carry the canonical skill implementation
    # by default. Individual skills can keep prompts smaller by declaring
    # generator.prompt_body_sections in skill.yaml.
    if not requested_sections:
        return body.strip() or None

    sections: list[str] = []
    for heading in requested_sections:
        if not isinstance(heading, str) or not heading.strip():
            continue
        section = _extract_markdown_section(body, heading.strip())
        if section:
            sections.append(section)

    if not sections:
        return None
    return "\n\n".join(sections)


def _render_codex_router_body(manifest: dict) -> list[str]:
    commands: list[dict] = manifest["commands"]
    managed_ids = ", ".join(f"`/{command['command_id']}`" for command in commands)
    return [
        *_render_global_instructions(manifest),
        (
            "If a user prompt begins with a registered `/command_id`, treat that prefix as a portable workflow "
            "command routed through `config/agent-workflows/portable_commands.json`."
        ),
        "",
        f"Current managed ids: {managed_ids}.",
        "",
        "Routing rules:",
        "",
        "- Strip the leading `/command_id` token before normal intent analysis.",
        "- Load the mapped skill from the manifest and use its `makefile_target` as the primary entry point when one exists.",
        "- Interpret the remainder of the user message using the manifest-defined argument names.",
        "- If generated adapters drift from the manifest, run `make generate-agent-workflows`; `make check-agent-workflows` verifies Claude, VS Code, and Codex outputs together.",
        "",
        "Command map:",
        "",
        *(
            f"- `/{command['command_id']}` ({command['mode']}) -> skill `{command['skill']}` -> `{command['makefile_target']}`"
            for command in commands
        ),
    ]


def _render_codex_router(manifest: dict) -> str:
    lines = [
        GENERATOR_TAG.rstrip(),
        "",
        CODEX_ROUTER_HEADER.rstrip(),
        "",
        *_render_codex_router_body(manifest),
        "",
    ]
    return "\n".join(lines)


def _render_codex_router_embed(manifest: dict) -> str:
    lines = [
        GENERATOR_TAG.rstrip(),
        "",
        *_render_codex_router_body(manifest),
        "",
    ]
    return "\n".join(lines)


def _replace_marked_block(content: str, replacement: str) -> tuple[str, bool]:
    begin = content.find(CODEX_ROUTER_BEGIN)
    end = content.find(CODEX_ROUTER_END)
    if begin == -1 or end == -1 or end < begin:
        raise ValueError("missing codex router markers")
    if (
        content.find(CODEX_ROUTER_BEGIN, begin + 1) != -1
        or content.find(CODEX_ROUTER_END, end + 1) != -1
    ):
        raise ValueError("multiple codex router marker blocks")

    block_start = begin + len(CODEX_ROUTER_BEGIN)
    before = content[:block_start]
    current = content[block_start:end]
    after = content[end:]
    new_block = f"\n{replacement}\n"
    return before + new_block + after, current != new_block


def _sync_codex_router_consumers(
    manifest: dict, repo_root: Path, check: bool
) -> list[str]:
    replacement = _render_codex_router_embed(manifest)
    failures: list[str] = []
    for relative_path in CODEX_ROUTER_CONSUMERS:
        absolute_path = repo_root / relative_path
        try:
            content = absolute_path.read_text()
        except FileNotFoundError:
            # In fresh target repos these consumer docs may not exist
            # yet (no CLAUDE.md, no docs/workstate/instructions.md). Treat
            # that as "nothing to sync" rather than a hard failure;
            # --check still flags it so CI can require both.
            if check:
                failures.append(f"missing codex router consumer: {absolute_path}")
            continue

        try:
            updated, changed = _replace_marked_block(content, replacement)
        except ValueError as exc:
            failures.append(f"{absolute_path}: {exc}")
            continue

        if check:
            if changed:
                failures.append(f"codex router drift detected: {absolute_path}")
            continue

        if changed:
            absolute_path.write_text(updated)
    return failures


def _load_skill(skills_source_root: Path, slug: str) -> tuple[dict, str]:
    """Read the canonical neutral layout: skill.yaml + body.md.

    Returns ``(structured_metadata, prose_body)``. Raises SystemExit
    with a precise message on missing or malformed files.
    """
    slug_dir = skills_source_root / slug
    skill_yaml = slug_dir / "skill.yaml"
    body_md = slug_dir / "body.md"
    if not skill_yaml.is_file():
        raise SystemExit(
            f"manifest references skill {slug!r} but canonical source is missing: {skill_yaml}"
        )
    if not body_md.is_file():
        raise SystemExit(
            f"manifest references skill {slug!r} but body.md is missing: {body_md}"
        )
    structured = yaml.safe_load(skill_yaml.read_text()) or {}
    if not isinstance(structured, dict):
        raise SystemExit(f"{skill_yaml}: must parse to a mapping")
    return structured, body_md.read_text()


def _strip_generator_metadata(structured: dict) -> tuple[dict, dict]:
    """Split canonical structured metadata from per-agent overrides.

    The neutral skill.yaml carries a top-level ``generator`` key whose
    children describe per-agent rendering hints
    (e.g. ``generator.claude_overrides.disable-model-invocation``).
    Returns ``(canonical, generator_block)`` where ``canonical`` is the
    structured manifest minus the generator block. The generator block
    is consumed by the per-agent renderers to compose agent-specific
    frontmatter.
    """
    if not isinstance(structured, dict):
        return {}, {}
    structured = dict(structured)
    generator = structured.pop("generator", {}) or {}
    if not isinstance(generator, dict):
        generator = {}
    return structured, generator


def _render_claude_skill(slug: str, structured: dict, body: str) -> str:
    """Compose Claude-shape SKILL.md from canonical skill.yaml + body.md.

    Re-attaches Claude-only frontmatter keys carried under
    ``generator.claude_overrides`` (e.g. ``disable-model-invocation``).
    """
    canonical, generator = _strip_generator_metadata(structured)
    overrides = generator.get("claude_overrides") or {}
    frontmatter = {**canonical, **overrides}
    fm_text = yaml.safe_dump(
        frontmatter, sort_keys=False, default_flow_style=False
    ).rstrip()
    body = body if body.endswith("\n") else body + "\n"
    return f"---\n{fm_text}\n---\n\n{body}"


def _render_codex_skill(slug: str, structured: dict, body: str) -> str:
    """Compose Codex-shape SKILL.md.

    Codex skills carry the same YAML+Markdown shape as Claude. We keep
    only the canonical fields here — Codex doesn't honor Claude's
    ``disable-model-invocation`` knob, so we drop the
    ``generator.claude_overrides`` block.
    """
    canonical, _ = _strip_generator_metadata(structured)
    fm_text = yaml.safe_dump(
        canonical, sort_keys=False, default_flow_style=False
    ).rstrip()
    body = body if body.endswith("\n") else body + "\n"
    return f"---\n{fm_text}\n---\n\n{body}"


def _expected_skill_outputs(
    manifest: dict,
    skills_source_root: Path,
    claude_skills_out: Path | None,
    codex_skills_out: Path | None,
) -> dict[Path, str]:
    """Map per-agent skill output paths to their generated content.

    internal cutover: returns an empty mapping. The cross-harness
    `.claude/skills/<slug>/SKILL.md` and `.codex/skills/<slug>/SKILL.md`
    surfaces are owned by the plugin tree (ADR-001); the legacy mode no
    longer duplicates them per consumer. ``--claude-skills-out`` and
    ``--codex-skills-out`` are accepted (and the destinations are still
    pruned by ``_prune_stale_skill_dirs``) for backwards compatibility
    with existing operator scripts, but no new content is written.
    """
    # Loading every skill at runtime is no longer necessary now that the
    # legacy mode emits nothing here; the plugin-tree emission does its
    # own load via ``_render_skill_body``. Keeping the input parameters
    # so the call sites do not have to change.
    del manifest, skills_source_root, claude_skills_out, codex_skills_out
    return {}


def _write_skill_files(outputs: dict[Path, str]) -> None:
    """Write generated skill files; replace pre-existing symlinks
    pointing at a former canonical source.
    """
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        # If the parent directory used to be a symlink (legacy layout
        # where .codex/skills/<slug> linked to .claude/skills/<slug>),
        # replace it with a real directory.
        if path.parent.is_symlink():
            target = path.parent
            target.unlink()
            target.mkdir(parents=True, exist_ok=True)
        if path.is_symlink():
            path.unlink()
        # Codex output was previously emitted as lowercase skill.md.
        # On case-insensitive filesystems writing SKILL.md over an
        # existing skill.md preserves the lowercase casing, which
        # breaks Codex skill discovery. Remove any legacy lowercase
        # sibling before writing so the on-disk name is exactly SKILL.md.
        if path.name == "SKILL.md":
            legacy = path.with_name("skill.md")
            if legacy.is_symlink() or legacy.exists():
                legacy.unlink()
        path.write_text(content)


def _prune_stale_skill_dirs(out_root: Path | None, expected_slugs: set[str]) -> None:
    """Remove generated skill directories whose slug is no longer in the manifest."""
    if out_root is None or not out_root.exists():
        return
    for entry in out_root.iterdir():
        if entry.name in expected_slugs:
            continue
        if entry.is_symlink() or entry.is_file():
            entry.unlink()
        else:
            shutil.rmtree(entry)


def _prune_legacy_portable_emissions(
    manifest: dict,
    claude_commands_out: Path | None,
    claude_skills_out: Path | None,
    codex_skills_out: Path | None,
) -> list[Path]:
    """Remove legacy emissions for portable command_ids / skill slugs.

    internal stopped writing `.claude/commands/<id>.md`,
    `.claude/skills/<slug>/SKILL.md`, and `.codex/skills/<slug>/SKILL.md`
    for portable manifest entries; those surfaces are owned by the
    plugin tree now. ``_prune_stale_skill_dirs`` only removes slugs that
    were dropped from the manifest, so pre-existing legacy files for
    *still-portable* slugs would otherwise persist as duplicates of the
    plugin-tree content.

    Deletion is conservative:
      - ``.claude/commands/<id>.md``: only removed when the file starts
        with ``GENERATOR_TAG`` (same gate as ``_extra_generated_files``);
        hand-authored slash commands at the same id are left alone.
      - ``.claude/skills/<slug>/SKILL.md`` and ``.codex/skills/<slug>/SKILL.md``
        (plus the legacy lowercase ``skill.md`` sibling): removed only
        when the file's frontmatter ``name`` matches the portable slug,
        which is the shape every pre-cutover legacy emission has (the
        legacy generator copied ``skills/<slug>/body.md`` whose canonical
        frontmatter declares ``name: <slug>``). A file with a non-matching
        ``name`` is treated as a hand-authored project-local override and
        left alone — this is the BR-04 safety gate that keeps the prune
        helper from clobbering contributor files at colliding paths.
      - The parent slug directory is removed only when it becomes empty
        after the SKILL.md deletion, so user-added siblings are
        preserved.
    """
    removed: list[Path] = []
    for command in manifest["commands"]:
        command_id = command["command_id"]
        slug = command["skill"]
        if claude_commands_out is not None:
            legacy_command = claude_commands_out / f"{command_id}.md"
            if legacy_command.is_file():
                try:
                    if legacy_command.read_text().startswith(GENERATOR_TAG):
                        legacy_command.unlink()
                        removed.append(legacy_command)
                except OSError:
                    pass
        for skills_root in (claude_skills_out, codex_skills_out):
            if skills_root is None:
                continue
            skill_dir = skills_root / slug
            if not skill_dir.exists():
                continue
            for name in ("SKILL.md", "skill.md"):
                candidate = skill_dir / name
                if candidate.is_symlink() or candidate.is_file():
                    if _legacy_skill_matches_portable_slug(candidate, slug):
                        candidate.unlink()
                        removed.append(candidate)
            try:
                if not any(skill_dir.iterdir()):
                    skill_dir.rmdir()
                    removed.append(skill_dir)
            except OSError:
                pass
    return removed


def _legacy_skill_matches_portable_slug(path: Path, slug: str) -> bool:
    """Return True iff ``path`` looks like a pre-cutover legacy SKILL.md
    emission for ``slug`` — i.e. it has YAML frontmatter whose ``name``
    field equals the slug. A file at a portable slug path that declares a
    different ``name`` (or has no parseable frontmatter) is treated as a
    hand-authored project-local override and preserved.
    """
    try:
        text = path.read_text()
    except OSError:
        return False
    if not text.startswith("---\n"):
        return False
    try:
        _, fm_raw, _ = text.split("---\n", 2)
    except ValueError:
        return False
    try:
        frontmatter = yaml.safe_load(fm_raw) or {}
    except yaml.YAMLError:
        return False
    if not isinstance(frontmatter, dict):
        return False
    return frontmatter.get("name") == slug


def _check_skill_outputs(outputs: dict[Path, str]) -> list[str]:
    failures: list[str] = []
    for path, expected in outputs.items():
        if not path.exists():
            failures.append(f"missing generated skill file: {path}")
            continue
        if path.is_symlink():
            failures.append(
                f"generated skill path is a symlink (legacy layout): {path}"
            )
            continue
        # Case-insensitive filesystems resolve Path('SKILL.md') to an
        # on-disk skill.md, hiding stale lowercase emissions from the
        # drift gate. Codex skill discovery is case-sensitive, so verify
        # the actual directory entry name matches the expected casing.
        if path.parent.is_dir() and path.name not in {
            entry.name for entry in path.parent.iterdir()
        }:
            failures.append(
                f"generated skill file has wrong on-disk casing: {path} "
                f"(expected exact name {path.name!r})"
            )
            continue
        actual = path.read_text()
        if actual != expected:
            failures.append(f"drift detected: {path}")
    return failures


def _expected_outputs(
    manifest: dict,
    skills_source_root: Path,
    claude_out: Path,
    prompts_out: Path,
    codex_router_out: Path,
    coadded_skill_sources: dict[str, tuple[dict, str]] | None = None,
) -> dict[Path, str]:
    # internal cutover: the cross-harness `.claude/commands/<id>.md`
    # surface for portable slugs is no longer emitted here — consumers
    # discover those slash commands from the plugin tree (ADR-001) and
    # the codex-command-router block. Only Copilot prompts and the
    # router doc are produced from this code path.
    outputs: dict[Path, str] = {}
    coadded_skill_sources = coadded_skill_sources or {}
    for command in manifest["commands"]:
        command_id = command["command_id"]
        slug = command["skill"]
        if slug in coadded_skill_sources:
            structured, body = coadded_skill_sources[slug]
        else:
            structured, body = _load_skill(skills_source_root, slug)
        outputs[prompts_out / f"{command_id}.prompt.md"] = _render_prompt_with_guidance(
            command,
            _extract_prompt_guidance(structured, body),
            manifest,
        )
    outputs[codex_router_out / "codex-command-router.md"] = _render_codex_router(
        manifest
    )
    return outputs


# --- per-harness hook configs (internal) --------------------------------
#
# Single source: the `hooks:` section of docs/workstate/contracts/
# harness-protocol.yaml. The per-harness JSON configs are generated goldens:
#   .github/hooks/terminal-guard.json  (VS Code / Copilot runner)
#   .codex/hooks.json                  (Codex CLI)
# Codex handlers carry `statusMessage` (rendered from the contract's
# harness-neutral `status_message`) so its UI names hooks instead of showing
# "Hook 1 / Hook 2"; the VS Code runner has no display field yet, so the value
# is omitted there. The contract-derived Claude hooks block is generated as
# ``.claude/settings.hooks.json`` (hooks subtree only); wholesale
# ``.claude/settings.json`` composition lands in internal.

_HOOKS_CONTRACT_RELATIVE = Path("docs/workstate/contracts/harness-protocol.yaml")
_HOOK_STAGE_KEYS: tuple[tuple[str, str], ...] = (
    ("pre_tool_use", "PreToolUse"),
    ("post_tool_use", "PostToolUse"),
    ("session_start", "SessionStart"),
    ("user_prompt_submit", "UserPromptSubmit"),
)
# PostToolUse uses the nested matcher+hooks[] grouping (the Claude-schema shape
# both runners already accept for it); the other stages stay flat.
_NESTED_HOOK_STAGES = frozenset({"post_tool_use"})
_DEFAULT_HOOK_TIMEOUT = 5


def _require_codex_optout(item: dict, stage: str) -> None:
    """Enforce the documented Codex opt-out: an entry may omit ``codex_command``
    only when it declares ``codex_enabled: false`` plus a non-empty
    ``unsupported_reason`` — silent omission leaves no audit trail for why a
    hook is absent from ``.codex/hooks.json``."""
    reason = item.get("unsupported_reason")
    if (
        item.get("codex_enabled") is not False
        or not isinstance(reason, str)
        or not reason.strip()
    ):
        raise ValueError(
            f"hook `{item.get('id')}` ({stage}) omits `codex_command`; a "
            "Codex-skipped hook must declare `codex_enabled: false` and a "
            "non-empty `unsupported_reason`"
        )


# internal: fail-open wrapper injection. Every rendered tool-guard
# command is prefixed with the payload wrapper so a missing/unspawnable
# handler exits 0 (with hook_infra_failure telemetry) instead of fail-closing
# the harness. Contract entries may opt out of fail-open via
# ``fail_mode: closed`` (rendered as --fail-mode=closed; the wrapper then
# blocks on a missing handler). The transform lives in the stdlib-only
# sibling module ``_guard_wrap.py`` so ``check_harness_sync.py`` can import
# the SAME implementation without this module's pydantic dependency.


def _load_guard_wrap_module():
    import importlib.util

    path = Path(__file__).resolve().parent / "_guard_wrap.py"
    spec = importlib.util.spec_from_file_location("_payload_guard_wrap", path)
    if spec is None or spec.loader is None:  # pragma: no cover - ships together
        raise SystemExit(f"missing payload module {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_wrap_guard_command = _load_guard_wrap_module().wrap_guard_command


def _render_hooks_config(
    hooks_spec: dict,
    *,
    command_key: str,
    matcher_key: str,
    include_status_message: bool,
    enforce_codex_optout: bool = False,
) -> dict:
    config: dict[str, list[dict]] = {}
    for stage, config_stage in _HOOK_STAGE_KEYS:
        entries: list[dict] = []
        for item in hooks_spec.get(stage) or []:
            command = item.get(command_key)
            # strip-normalized so renderer and check_harness_sync classify a
            # whitespace-only command identically (omitted, not present).
            if not isinstance(command, str) or not command.strip():
                if enforce_codex_optout:
                    _require_codex_optout(item, stage)
                continue
            if enforce_codex_optout and item.get("codex_enabled") is False:
                raise ValueError(
                    f"hook `{item.get('id')}` ({stage}) declares "
                    "`codex_enabled: false` but still sets `codex_command`; "
                    "drop one of the two"
                )
            handler: dict = {
                "type": "command",
                "command": _wrap_guard_command(
                    command, fail_mode=item.get("fail_mode")
                ),
                "timeout": int(item.get("timeout", _DEFAULT_HOOK_TIMEOUT)),
            }
            if include_status_message:
                status_message = item.get("status_message")
                if not isinstance(status_message, str) or not status_message.strip():
                    raise ValueError(
                        f"hook `{item.get('id')}` ({stage}) is missing the non-empty "
                        "`status_message` required to render Codex statusMessage"
                    )
                handler["statusMessage"] = status_message
            matcher = item.get(matcher_key, item.get("matcher"))
            if stage in _NESTED_HOOK_STAGES:
                entries.append({"matcher": matcher, "hooks": [handler]})
            else:
                entry: dict = {}
                if matcher is not None:
                    entry["matcher"] = matcher
                entry.update(handler)
                entries.append(entry)
        config[config_stage] = entries
    return {"hooks": config}


def render_vscode_hooks_config(hooks_spec: dict) -> dict:
    return _render_hooks_config(
        hooks_spec,
        command_key="vscode_command",
        matcher_key="vscode_matcher",
        include_status_message=False,
    )


def render_composed_claude_settings_hooks(
    hooks_spec: dict,
    *,
    override_root: Path | None = None,
    override_manifest: Any | None = None,
) -> dict:
    """Render contract hooks, optionally composing consumer overrides."""
    base = render_claude_hooks_config(hooks_spec)
    if override_root is None or override_manifest is None:
        return base
    from workstate_protocol.bootstrap import PluginOverrideManifest

    # Coerce BEFORE touching attributes: the signature accepts a raw mapping
    # (e.g. the dict loaded from overrides.yaml), which has no `.components`.
    if not isinstance(override_manifest, PluginOverrideManifest):
        override_manifest = PluginOverrideManifest.model_validate(override_manifest)
    if not override_manifest.components.claude_settings_hooks:
        return base
    compose = _import_plugin_override_compose()
    composed_stages, _components = compose.compose_claude_settings_hooks_overrides(
        base["hooks"],
        override_root,
        override_manifest,
    )
    return {"hooks": composed_stages}


def render_claude_hooks_config(hooks_spec: dict) -> dict:
    """Render the contract-derived hooks block for Claude settings.

    Claude Code requires every stage entry to carry nested ``hooks[]`` with a
    ``matcher`` (empty string when the contract omits one). Commands stay RAW —
    no fail-open wrapper — so ``check_harness_sync`` membership stays aligned
    with ``claude_command`` literals (implementation note / internal).
    """
    config: dict[str, list[dict]] = {}
    for stage, config_stage in _HOOK_STAGE_KEYS:
        entries: list[dict] = []
        for item in hooks_spec.get(stage) or []:
            command = item.get("claude_command")
            if not isinstance(command, str) or not command.strip():
                continue
            matcher = item.get("claude_matcher", item.get("matcher"))
            if matcher is None:
                matcher = ""
            entries.append(
                {
                    "matcher": matcher,
                    "hooks": [
                        {
                            "type": "command",
                            "command": command,
                            "timeout": int(item.get("timeout", _DEFAULT_HOOK_TIMEOUT)),
                        }
                    ],
                }
            )
        config[config_stage] = entries
    return {"hooks": config}


def render_codex_hooks_config(hooks_spec: dict) -> dict:
    # The codex_enabled opt-out contract only binds codex-aware contracts (any
    # entry carrying codex_command / codex_enabled). A legacy contract that
    # pre-dates the Codex fields entirely (e.g. a stale consumer mirror) keeps
    # the old skip-silently rendering instead of hard-failing generation.
    codex_aware = any(
        "codex_command" in item or "codex_enabled" in item
        for stage, _ in _HOOK_STAGE_KEYS
        for item in hooks_spec.get(stage) or []
    )
    return _render_hooks_config(
        hooks_spec,
        command_key="codex_command",
        matcher_key="codex_matcher",
        include_status_message=True,
        enforce_codex_optout=codex_aware,
    )


_CURSOR_HOOK_STAGE_KEYS: tuple[tuple[str, str], ...] = (
    ("pre_tool_use", "preToolUse"),
    ("post_tool_use", "postToolUse"),
    ("session_start", "sessionStart"),
    ("user_prompt_submit", "beforeSubmitPrompt"),
)


def render_cursor_hooks_config(hooks_spec: dict) -> dict:
    config: dict[str, list[dict]] = {}
    for stage, config_stage in _CURSOR_HOOK_STAGE_KEYS:
        entries: list[dict] = []
        for item in hooks_spec.get(stage) or []:
            command = item.get("cursor_command")
            if not isinstance(command, str) or not command.strip():
                continue
            entry: dict = {
                "type": "command",
                "command": _wrap_guard_command(
                    command, fail_mode=item.get("fail_mode")
                ),
                "timeout": int(item.get("timeout", _DEFAULT_HOOK_TIMEOUT)),
            }
            matcher = item.get("cursor_matcher", item.get("matcher"))
            if matcher is not None:
                entry["matcher"] = matcher
            entries.append(entry)
        config[config_stage] = entries
    return {"version": 1, "hooks": config}


def render_hooks_config_text(config: dict) -> str:
    return json.dumps(config, indent=2) + "\n"


def _expected_hooks_outputs(repo_root: Path) -> dict[Path, str]:
    """Map generated hook-config paths to content for ``repo_root``.

    Empty when the repo has no harness contract (e.g. a consumer that does not
    materialize the contracts surface) so legacy callers stay unaffected.
    """
    contract_path = repo_root / _HOOKS_CONTRACT_RELATIVE
    if not contract_path.is_file():
        return {}
    contract = yaml.safe_load(contract_path.read_text()) or {}
    hooks_spec = contract.get("hooks")
    if not isinstance(hooks_spec, dict) or not hooks_spec:
        return {}
    outputs = {
        repo_root
        / ".github"
        / "hooks"
        / "terminal-guard.json": render_hooks_config_text(
            render_vscode_hooks_config(hooks_spec)
        ),
        repo_root / ".codex" / "hooks.json": render_hooks_config_text(
            render_codex_hooks_config(hooks_spec)
        ),
        repo_root / ".claude" / "settings.hooks.json": render_hooks_config_text(
            render_claude_hooks_config(hooks_spec)
        ),
    }
    # Overlay consumers materialize shared surfaces (e.g. .github/hooks) as
    # symlinks into the .workstate/remote clone; writing through one would
    # mutate the shared clone instead of the consumer tree. Those paths already
    # resolve to the package-generated golden, so they are skipped here.
    return {
        path: content
        for path, content in outputs.items()
        if not path.is_symlink() and not path.parent.is_symlink()
    }


def _write_outputs(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def _extra_generated_files(root: Path, expected_paths: set[Path]) -> list[Path]:
    if not root.exists():
        return []
    extras: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if path in expected_paths:
            continue
        try:
            content = path.read_text()
        except OSError:
            continue
        if content.startswith(GENERATOR_TAG):
            extras.append(path)
    return sorted(extras)


def _check_outputs(
    outputs: dict[Path, str],
    claude_out: Path,
    prompts_out: Path,
    codex_router_out: Path,
) -> int:
    failures: list[str] = []
    for path, expected in outputs.items():
        if not path.exists():
            failures.append(f"missing generated file: {path}")
            continue
        actual = path.read_text()
        if actual != expected:
            failures.append(f"drift detected: {path}")

    expected_paths = set(outputs)
    # internal: claude_out is no longer manifest-driven (the
    # `.claude/commands/<id>.md` surface moved to the plugin tree), so
    # any tagged file under claude_out — e.g. the harness-only
    # `spec.md` — is intentionally outside this manifest's scope and
    # must not be flagged as stale here.
    extras = _extra_generated_files(
        prompts_out, expected_paths
    ) + _extra_generated_files(codex_router_out, expected_paths)
    for path in extras:
        failures.append(f"stale generated file not declared in manifest: {path}")

    if failures:
        print(
            "Agent workflow adapters are out of sync with the manifest:",
            file=sys.stderr,
        )
        for failure in failures:
            print(f"  - {failure}", file=sys.stderr)
        return 1
    print("✓ agent-workflows: generated adapters match the manifest.")
    return 0


def _load_mcp_servers_manifest(path: Path) -> dict:
    """Load and shallow-validate mcp_servers.yaml (internal input)."""
    try:
        payload = yaml.safe_load(path.read_text()) or {}
    except FileNotFoundError as exc:
        raise SystemExit(f"mcp_servers manifest not found: {path}") from exc
    if not isinstance(payload, dict):
        raise SystemExit(f"{path}: must parse to a mapping")
    if payload.get("version") != 2:
        raise SystemExit(
            f"{path}: must declare version=2; found {payload.get('version')!r}"
        )
    registration = payload.get("registration")
    if not isinstance(registration, dict) or not registration:
        raise SystemExit(
            f"{path}: version=2 requires a non-empty `registration` mapping "
            "(harness -> root|plugin); see implementation note"
        )
    plugin_capable = {h for h, _ in _PLUGIN_HARNESSES}
    for harness_name, owner in registration.items():
        if owner not in _MCP_REGISTRATION_OWNERS:
            raise SystemExit(
                f"{path}: registration.{harness_name} must be one of "
                f"{sorted(_MCP_REGISTRATION_OWNERS)}; found {owner!r}"
            )
        if owner == "plugin" and harness_name not in plugin_capable:
            raise SystemExit(
                f"{path}: registration.{harness_name}=plugin is unimplementable: "
                f"{harness_name!r} has no emitted plugin tree (plugin-capable "
                f"harnesses: {sorted(plugin_capable)}). Under plugin ownership "
                "the root surface stops registering the servers and no plugin "
                ".mcp.json exists to take over, so the harness silently loses "
                "all MCP registration (implementation note). Use registration: root."
            )
    missing = [h for h, _ in _PLUGIN_HARNESSES if h not in registration]
    if missing:
        raise SystemExit(
            f"{path}: registration must cover every plugin harness; missing {missing}"
        )
    plugin_version = payload.get("plugin_version")
    if not isinstance(plugin_version, str) or not plugin_version.strip():
        raise SystemExit(f"{path}: plugin_version must be a non-empty string")
    servers = payload.get("mcp_servers")
    if not isinstance(servers, list) or not servers:
        raise SystemExit(f"{path}: mcp_servers must be a non-empty list")
    for index, server in enumerate(servers):
        if not isinstance(server, dict):
            raise SystemExit(f"{path}: mcp_servers[{index}] must be a mapping")
        for field in ("name", "command"):
            value = server.get(field)
            if not isinstance(value, str) or not value.strip():
                raise SystemExit(
                    f"{path}: mcp_servers[{index}].{field} must be a non-empty string"
                )
        args = server.get("args", [])
        if not isinstance(args, list) or not all(isinstance(a, str) for a in args):
            raise SystemExit(
                f"{path}: mcp_servers[{index}].args must be a list of strings"
            )
        harnesses = server.get("harnesses", [])
        if not isinstance(harnesses, list) or not all(
            isinstance(h, str) for h in harnesses
        ):
            raise SystemExit(
                f"{path}: mcp_servers[{index}].harnesses must be a list of strings"
            )
        unregistered = sorted(set(harnesses) - set(registration))
        if unregistered:
            raise SystemExit(
                f"{path}: mcp_servers[{index}].harnesses {unregistered} missing from "
                "the `registration` ownership table; every server harness must "
                "declare root|plugin ownership (implementation note)"
            )
    return payload


def _render_mcp_servers_json(mcp_manifest: dict, harness: str) -> str:
    """Render the .mcp.json blob for the requested harness.

    Servers whose ``harnesses`` list excludes the harness are skipped.
    Output ordering follows the manifest insertion order; each entry
    carries ``"type": "stdio"`` to stay compatible with the bootstrap
    install path. Claude Code uses the camelCase ``mcpServers`` wrapper
    for plugin MCP config; Codex CLI 0.131.0 rejects wrapped plugin MCP
    config as an invalid server entry, so Codex receives the bare server
    map shape.
    """
    entries: dict[str, dict] = {}
    for server in mcp_manifest["mcp_servers"]:
        harnesses = server.get("harnesses") or []
        if harnesses and harness not in harnesses:
            continue
        entries[server["name"]] = {
            "type": "stdio",
            "command": server["command"],
            "args": list(server.get("args", [])),
        }
        env = server.get("env")
        if isinstance(env, dict) and env:
            entries[server["name"]]["env"] = dict(env)
    if harness in {"claude", "cursor", "grok"}:
        payload = {"mcpServers": entries}
    elif harness == "codex":
        payload = entries
    else:
        raise SystemExit(
            f"unsupported plugin harness for .mcp.json rendering: {harness!r}"
        )
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def _render_plugin_manifest_json(
    plugin_version: str, *, include_mcp_servers: bool
) -> str:
    """Render the metadata-only plugin.json (live-doc verified shape).

    The body is identical across harnesses — only the parent directory
    name differs. ``include_mcp_servers`` is driven by the manifest's
    `registration` ownership table (implementation note): under ``root`` ownership
    the bootstrap-written root surface registers the MCP servers, so the
    plugin manifest omits ``mcpServers`` to avoid double-registration;
    under ``plugin`` ownership the manifest points at the sibling
    ``./.mcp.json``.
    """
    payload = {
        "name": _PLUGIN_NAME,
        "version": plugin_version,
        "description": _PLUGIN_DESCRIPTION,
        "skills": "./skills/",
    }
    if include_mcp_servers:
        payload["mcpServers"] = "./.mcp.json"
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def _render_harness_routing_table(harness_protocol: dict) -> str:
    """Render the review-parallel routing table from harness-protocol.yaml."""
    capabilities = harness_protocol.get("harness_capabilities") or {}
    review_parallel = capabilities.get("review_parallel") or {}
    rows = review_parallel.get("rows") or []
    if not isinstance(rows, list) or not rows:
        raise SystemExit(
            "harness-protocol.yaml must declare harness_capabilities.review_parallel.rows"
        )
    lines = [
        "| Harness detected | Primitive the coordinator uses | Notes |",
        "| --- | --- | --- |",
    ]
    for row in rows:
        if not isinstance(row, dict):
            continue
        lines.append(f"| {row['label']} | {row['primitive']} | {row['notes']} |")
    return "\n".join(lines) + "\n"


def _inject_harness_routing_table(body: str, table: str) -> str:
    begin = body.find(_HARNESS_ROUTING_BEGIN)
    end = body.find(_HARNESS_ROUTING_END)
    if begin == -1 or end == -1 or end < begin:
        return body
    block_start = begin + len(_HARNESS_ROUTING_BEGIN)
    return body[:block_start] + "\n" + table + body[end:]


def _render_grok_plugin_hooks_json(harness_protocol: dict) -> str:
    """Project PreToolUse guards into the Grok plugin hooks surface.

    Only ``pre_tool_use`` rows are emitted here so plugin-delivered guards
    do not double-fire against compat-loaded ``.claude/settings.json`` hooks
    for post/session events after ``/hooks-trust``.
    """
    hook_rows = (harness_protocol.get("hooks") or {}).get("pre_tool_use") or []
    entries: list[dict[str, object]] = []
    for row in hook_rows:
        if not isinstance(row, dict):
            continue
        grok_command = row.get("grok_command")
        if not isinstance(grok_command, str) or not grok_command.strip():
            continue
        entries.append(
            {
                "matcher": row.get("matcher", ""),
                "hooks": [
                    {
                        "type": "command",
                        "command": _wrap_guard_command(
                            grok_command, fail_mode=row.get("fail_mode")
                        ),
                    }
                ],
            }
        )
    payload = {"hooks": {"PreToolUse": entries}}
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def _render_plugin_skill(
    structured: dict, body: str, manifest: dict, harness_protocol: dict | None = None
) -> str:
    """Render a SKILL.md body for the plugin tree.

    ADR-001 mandates byte-identical SKILL.md across harnesses, so this
    intentionally drops the ``generator.claude_overrides`` block.
    """
    canonical, _ = _strip_generator_metadata(structured)
    fm_text = yaml.safe_dump(
        canonical, sort_keys=False, default_flow_style=False
    ).rstrip()
    bullets = _global_instruction_bullets(manifest)
    if bullets:
        body = "## Global Instructions\n\n" + "\n".join(bullets) + "\n\n" + body
    if harness_protocol is not None and _HARNESS_ROUTING_BEGIN in body:
        body = _inject_harness_routing_table(
            body, _render_harness_routing_table(harness_protocol)
        )
    body = body if body.endswith("\n") else body + "\n"
    return f"---\n{fm_text}\n---\n\n{body}"


def _sha256_digest(content: str) -> str:
    return f"sha256:{hashlib.sha256(content.encode('utf-8')).hexdigest()}"


def _load_plugin_override_manifest(override_root: Path) -> PluginOverrideManifest:
    path = override_root / _PLUGIN_OVERRIDE_MANIFEST
    try:
        payload = yaml.safe_load(path.read_text()) or {}
    except FileNotFoundError as exc:
        raise SystemExit(f"plugin override manifest not found: {path}") from exc
    try:
        return PluginOverrideManifest.model_validate(payload)
    except ValidationError as exc:
        raise SystemExit(f"{path}: {exc}") from exc


def _canonical_mcp_server_digest(server: dict[str, object]) -> str:
    return _sha256_digest(json.dumps(server, sort_keys=True, ensure_ascii=False))


def _import_plugin_override_compose():
    script_dir = str(Path(__file__).resolve().parent)
    if script_dir not in sys.path:
        sys.path.insert(0, script_dir)
    import plugin_override_compose

    return plugin_override_compose


def _compose_plugin_skill_overrides(
    rendered_skills: dict[str, str],
    override_root: Path,
    payload: PluginOverrideManifest,
) -> tuple[dict[str, str], list[str], list[dict[str, str]]]:
    compose = _import_plugin_override_compose()
    return compose.compose_plugin_skill_overrides(
        rendered_skills, override_root, payload
    )


def _compose_plugin_mcp_overrides(
    mcp_manifest: dict,
    override_root: Path,
    payload: PluginOverrideManifest,
) -> tuple[dict, list[dict[str, str]], list[str]]:
    compose = _import_plugin_override_compose()
    return compose.compose_plugin_mcp_overrides(mcp_manifest, override_root, payload)


def _compose_plugin_portable_command_overrides(
    manifest: dict,
    override_root: Path,
    payload: PluginOverrideManifest,
    *,
    composed_skills: dict[str, str],
) -> tuple[dict, list[dict[str, str]]]:
    compose = _import_plugin_override_compose()
    return compose.compose_plugin_portable_command_overrides(
        manifest,
        override_root,
        payload,
        composed_skills=composed_skills,
    )


def _parse_skill_md(text: str, *, source: str) -> tuple[dict, str]:
    if not text.startswith("---"):
        raise SystemExit(f"{source}: SKILL.md must begin with YAML frontmatter")
    parts = text.split("---", 2)
    if len(parts) < 3:
        raise SystemExit(f"{source}: SKILL.md frontmatter is malformed")
    structured = yaml.safe_load(parts[1]) or {}
    if not isinstance(structured, dict):
        raise SystemExit(f"{source}: SKILL.md frontmatter must parse to a mapping")
    return structured, parts[2].lstrip("\n")


def _coadded_skill_sources(
    override_root: Path, payload: PluginOverrideManifest
) -> dict[str, tuple[dict, str]]:
    sources: dict[str, tuple[dict, str]] = {}
    for slug, override in payload.components.skills.items():
        if override.mode != "add" or not override.path:
            continue
        path = override_root / override.path
        sources[slug] = _parse_skill_md(path.read_text(), source=str(path))
    return sources


def _ensure_rendered_skills_for_manifest(
    manifest: dict,
    *,
    rendered_skills: dict[str, str],
    seen_slugs: list[str],
    skills_source_root: Path,
    manifest_for_render: dict,
    harness_protocol: dict | None,
    coadded_skill_sources: dict[str, tuple[dict, str]],
) -> None:
    for command in manifest["commands"]:
        slug = command["skill"]
        if slug in rendered_skills:
            continue
        # Defensive fallback: a co-added skill normally lands in rendered_skills
        # via _compose_plugin_skill_overrides before this runs, so this branch
        # is only reached if a command references a co-added skill that bypassed
        # skill composition (none do today). Kept so command->skill linkage can
        # never emit a command whose skill was never rendered.
        if slug in coadded_skill_sources:
            structured, body = coadded_skill_sources[slug]
            rendered_skills[slug] = _render_plugin_skill(
                structured, body, manifest_for_render, harness_protocol
            )
            seen_slugs.append(slug)
            continue
        structured, body = _load_skill(skills_source_root, slug)
        rendered_skills[slug] = _render_plugin_skill(
            structured, body, manifest_for_render, harness_protocol
        )
        seen_slugs.append(slug)


def _portable_command_digest(command: dict) -> str:
    return _sha256_digest(json.dumps(command, sort_keys=True, ensure_ascii=False))


def _render_plugin_effective_lock_json(
    base_remote_sha: str,
    effective_root: Path,
    components: list[dict[str, str]],
) -> str:
    if len(base_remote_sha) != 40 or any(
        ch not in "0123456789abcdef" for ch in base_remote_sha
    ):
        raise SystemExit(
            f"--plugin-base-remote-sha must be a 40-char lowercase git SHA; found {base_remote_sha!r}"
        )
    payload = PluginEffectiveLock.model_validate(
        {
            "schema_version": 1,
            "plugin": _PLUGIN_NAME,
            "base_remote_sha": base_remote_sha,
            "effective_root": ".",
            "components": components,
        }
    ).model_dump(mode="json")
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def _expected_plugin_outputs(
    manifest: dict,
    mcp_manifest: dict,
    skills_source_root: Path,
    plugin_out: Path,
    plugin_overrides: Path | None = None,
    plugin_base_remote_sha: str | None = None,
    plugin_passthrough_lock: bool = False,
    harness_protocol: dict | None = None,
) -> tuple[dict[Path, str], list[str]]:
    """Map every emitted plugin-tree file to its rendered content.

    Layout per harness::

        <plugin_out>/<harness>/<plugin_dir>/plugin.json
        <plugin_out>/<harness>/.mcp.json   (only under `registration: plugin`)
        <plugin_out>/<harness>/skills/<slug>/SKILL.md
    """
    outputs: dict[Path, str] = {}
    audit_lines: list[str] = []
    plugin_version = mcp_manifest["plugin_version"]
    registration = mcp_manifest["registration"]
    if harness_protocol is None:
        harness_protocol = _load_harness_protocol()

    seen_slugs: list[str] = []
    rendered_skills: dict[str, str] = {}
    for command in manifest["commands"]:
        slug = command["skill"]
        if slug in rendered_skills:
            continue
        structured, body = _load_skill(skills_source_root, slug)
        rendered_skills[slug] = _render_plugin_skill(
            structured, body, manifest, harness_protocol
        )
        seen_slugs.append(slug)

    effective_components: list[dict[str, str]] = []
    coadded_skill_sources: dict[str, tuple[dict, str]] = {}
    if plugin_overrides is not None and plugin_passthrough_lock:
        raise SystemExit(
            "--plugin-passthrough-lock cannot be combined with --plugin-overrides"
        )
    if plugin_overrides is not None:
        if plugin_base_remote_sha is None:
            raise SystemExit(
                "--plugin-base-remote-sha is required when --plugin-overrides is set"
            )
        override_payload = _load_plugin_override_manifest(plugin_overrides)
        rendered_skills, seen_slugs, effective_components = (
            _compose_plugin_skill_overrides(
                rendered_skills, plugin_overrides, override_payload
            )
        )
        mcp_manifest, mcp_components, audit_lines = _compose_plugin_mcp_overrides(
            mcp_manifest,
            plugin_overrides,
            override_payload,
        )
        effective_components.extend(mcp_components)
        coadded_skill_sources = _coadded_skill_sources(
            plugin_overrides, override_payload
        )
        if override_payload.components.portable_commands:
            manifest, command_components = _compose_plugin_portable_command_overrides(
                manifest,
                plugin_overrides,
                override_payload,
                composed_skills=rendered_skills,
            )
            effective_components.extend(command_components)
            _ensure_rendered_skills_for_manifest(
                manifest,
                rendered_skills=rendered_skills,
                seen_slugs=seen_slugs,
                skills_source_root=skills_source_root,
                manifest_for_render=manifest,
                harness_protocol=harness_protocol,
                coadded_skill_sources=coadded_skill_sources,
            )
        if override_payload.components.claude_settings_hooks:
            # iter4-g: claude_settings_hooks overrides compose into the managed
            # .claude/settings.json hooks. Record each as an effective-lock
            # component (parity with skill / mcp_server / portable_command) so
            # doctor/repair can detect drift on a consumer settings-hook
            # override. The compose fn already builds the per-component digest;
            # render_composed_claude_settings_hooks previously discarded it.
            base_claude_hooks = render_claude_hooks_config(
                harness_protocol.get("hooks") or {}
            )["hooks"]
            compose = _import_plugin_override_compose()
            _composed_hooks, settings_hook_components = (
                compose.compose_claude_settings_hooks_overrides(
                    base_claude_hooks,
                    plugin_overrides,
                    override_payload,
                )
            )
            effective_components.extend(settings_hook_components)
    elif plugin_passthrough_lock:
        # internal always-effective: a zero-override effective tree is the base
        # tree composed unchanged; the lock receipt records every component as
        # passthrough so doctor/repair can distinguish "composed clean" from
        # "never composed".
        if plugin_base_remote_sha is None:
            raise SystemExit(
                "--plugin-base-remote-sha is required when --plugin-passthrough-lock is set"
            )
        effective_components = [
            {
                "component_kind": "skill",
                "name": slug,
                "mode": "passthrough",
                "effective_digest": _sha256_digest(rendered_skills[slug]),
            }
            for slug in seen_slugs
        ]
        effective_components.extend(
            {
                "component_kind": "mcp_server",
                "name": server["name"],
                "mode": "passthrough",
                "effective_digest": _canonical_mcp_server_digest(server),
            }
            for server in mcp_manifest["mcp_servers"]
        )
        effective_components.extend(
            {
                "component_kind": "portable_command",
                "name": command["command_id"],
                "mode": "passthrough",
                "effective_digest": _portable_command_digest(command),
            }
            for command in manifest["commands"]
        )

    grok_hooks_body = _render_grok_plugin_hooks_json(harness_protocol)
    cursor_hooks_body = render_hooks_config_text(
        render_cursor_hooks_config(harness_protocol.get("hooks") or {})
    )
    cursor_command_bodies: dict[str, str] = {}
    for command in manifest["commands"]:
        slug = command["skill"]
        if slug in coadded_skill_sources:
            structured, body = coadded_skill_sources[slug]
        else:
            structured, body = _load_skill(skills_source_root, slug)
        cursor_command_bodies[command["command_id"]] = _render_prompt_with_guidance(
            command, _extract_prompt_guidance(structured, body), manifest
        )

    for harness, plugin_dir in _PLUGIN_HARNESSES:
        harness_root = plugin_out / harness
        plugin_owns_mcp = registration[harness] == "plugin"
        outputs[harness_root / plugin_dir / "plugin.json"] = (
            _render_plugin_manifest_json(
                plugin_version, include_mcp_servers=plugin_owns_mcp
            )
        )
        if plugin_owns_mcp:
            outputs[harness_root / ".mcp.json"] = _render_mcp_servers_json(
                mcp_manifest, harness
            )
        if harness == "grok":
            outputs[harness_root / "hooks" / "hooks.json"] = grok_hooks_body
        if harness == "cursor":
            outputs[harness_root / "hooks.json"] = cursor_hooks_body
            for command_id, body in cursor_command_bodies.items():
                outputs[harness_root / "commands" / f"{command_id}.md"] = body
        for slug in seen_slugs:
            outputs[harness_root / "skills" / slug / "SKILL.md"] = rendered_skills[slug]
    if plugin_overrides is not None or plugin_passthrough_lock:
        outputs[plugin_out / _PLUGIN_EFFECTIVE_LOCK] = (
            _render_plugin_effective_lock_json(
                plugin_base_remote_sha,
                plugin_out,
                effective_components,
            )
        )
    return outputs, audit_lines


def _extra_plugin_tree_files(plugin_out: Path, outputs: dict[Path, str]) -> list[Path]:
    if not plugin_out.exists():
        return []
    expected = {path.resolve() for path in outputs}
    return sorted(
        path
        for path in plugin_out.rglob("*")
        if path.is_file() and path.resolve() not in expected
    )


def _prune_plugin_tree(plugin_out: Path, outputs: dict[Path, str]) -> None:
    for path in _extra_plugin_tree_files(plugin_out, outputs):
        path.unlink()
    if not plugin_out.exists():
        return
    for path in sorted(
        plugin_out.rglob("*"), key=lambda item: len(item.parts), reverse=True
    ):
        if not path.is_dir():
            continue
        try:
            path.rmdir()
        except OSError:
            continue


def _emit_plugin_tree(plugin_out: Path, outputs: dict[Path, str]) -> None:
    """Write every plugin-tree file deterministically."""
    _prune_plugin_tree(plugin_out, outputs)
    for path, content in sorted(outputs.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def _check_plugin_outputs(plugin_out: Path, outputs: dict[Path, str]) -> list[str]:
    failures: list[str] = []
    for path, expected in sorted(outputs.items()):
        if not path.exists():
            failures.append(f"missing plugin tree file: {path}")
            continue
        if path.read_text() != expected:
            failures.append(f"plugin tree drift: {path}")
    for path in _extra_plugin_tree_files(plugin_out, outputs):
        failures.append(f"unexpected plugin tree file: {path}")
    return failures


def _run_plugin_mode(
    args: argparse.Namespace, package_root: Path, manifest: dict
) -> int:
    skills_source_root = (
        args.skills_source_root or args.claude_skills_root or (package_root / "skills")
    )
    mcp_servers_path = args.plugin_mcp_servers or (
        package_root / "config" / "agent-workflows" / "mcp_servers.yaml"
    )
    if args.plugin_out is None:
        raise SystemExit("--mode=plugin requires --plugin-out <dest>")
    mcp_manifest = _load_mcp_servers_manifest(mcp_servers_path)
    outputs, audit_lines = _expected_plugin_outputs(
        manifest,
        mcp_manifest,
        skills_source_root,
        args.plugin_out,
        args.plugin_overrides,
        args.plugin_base_remote_sha,
        args.plugin_passthrough_lock,
    )
    stale_components: list[dict[str, object]] = []
    conflict_components: list[dict[str, object]] = []
    lock_payload = outputs.get(args.plugin_out / _PLUGIN_EFFECTIVE_LOCK)
    if lock_payload is not None:
        try:
            parsed_lock = json.loads(lock_payload)
        except json.JSONDecodeError:
            parsed_lock = {}
        stale_components = [
            entry
            for entry in parsed_lock.get("components", [])
            if isinstance(entry, dict) and entry.get("status") == "stale"
        ]
        conflict_components = [
            entry
            for entry in parsed_lock.get("components", [])
            if isinstance(entry, dict) and entry.get("status") == "merge_conflict"
        ]
    if args.check:
        failures = _check_plugin_outputs(args.plugin_out, outputs)
        if stale_components:
            print("Plugin override composition has stale overrides:", file=sys.stderr)
            for entry in stale_components:
                print(
                    "  - stale override: "
                    f"{entry.get('override_path')} "
                    f"(recorded {entry.get('recorded_upstream_digest')} vs current {entry.get('current_base_digest')})",
                    file=sys.stderr,
                )
        if conflict_components:
            print("Plugin override composition has merge conflicts:", file=sys.stderr)
            for entry in conflict_components:
                print(
                    "  - merge conflict: "
                    f"{entry.get('override_path')} "
                    f"(recorded {entry.get('recorded_upstream_digest')} vs current {entry.get('current_base_digest')})",
                    file=sys.stderr,
                )
        if failures:
            print(
                "Plugin tree is out of sync with the canonical inputs:", file=sys.stderr
            )
            for failure in failures:
                print(f"  - {failure}", file=sys.stderr)
        if failures or stale_components or conflict_components:
            return 1
        print(f"✓ plugin-tree: {len(outputs)} files match canonical inputs.")
        return 0
    _emit_plugin_tree(args.plugin_out, outputs)
    for line in audit_lines:
        print(line)
    if stale_components:
        for entry in stale_components:
            print(
                "warning: stale override preserved: "
                f"{entry.get('override_path')} "
                f"(recorded {entry.get('recorded_upstream_digest')} vs current {entry.get('current_base_digest')})",
                file=sys.stderr,
            )
    if conflict_components:
        for entry in conflict_components:
            print(
                "warning: merge conflict; consumer copy preserved: "
                f"{entry.get('override_path')} "
                f"(recorded {entry.get('recorded_upstream_digest')} vs current {entry.get('current_base_digest')})",
                file=sys.stderr,
            )
    print(f"✓ plugin-tree: wrote {len(outputs)} files under {args.plugin_out}.")
    return 0


def render_plugin_tree(
    *,
    manifest_path: Path,
    skills_source_root: Path,
    mcp_servers_path: Path,
    plugin_out: Path,
    plugin_overrides: Path | None = None,
    plugin_base_remote_sha: str | None = None,
    plugin_passthrough_lock: bool = False,
) -> dict[Path, str]:
    """Single importable entry point for the plugin-tree payload (path -> content).

    implementation note S2 (pa0020-s2-build-vs-install-generation-parity): every adapter
    producer routes through the same ``_expected_plugin_outputs`` core so build
    output == install output for the same inputs —
      * the build hook / ``make generate-agent-workflows`` calls this directly
        in-process, and
      * the install-time generator in ``workstate-bootstrap`` reaches the same
        core via the subprocess CLI (``main`` -> ``_run_plugin_mode``).

    Pure: computes the output map without writing to disk, so a caller can
    render-then-decide (diff against committed, emit, or ``--check``) before
    any write lands. Materialise the returned map with ``_emit_plugin_tree``.
    """
    manifest = _load_manifest(manifest_path)
    mcp_manifest = _load_mcp_servers_manifest(mcp_servers_path)
    outputs, _audit_lines = _expected_plugin_outputs(
        manifest,
        mcp_manifest,
        skills_source_root,
        plugin_out,
        plugin_overrides,
        plugin_base_remote_sha,
        plugin_passthrough_lock,
    )
    return outputs


def main() -> int:
    args = _parse_args()
    manifest = _load_manifest(args.manifest)
    package_root = args.manifest.resolve().parents[2]

    if args.mode == "plugin":
        return _run_plugin_mode(args, package_root, manifest)

    # Source-of-truth: skills/<slug>/{skill.yaml, body.md}.
    # --claude-skills-root is the legacy alias kept for one release.
    skills_source_root = (
        args.skills_source_root or args.claude_skills_root or (package_root / "skills")
    )

    # Per-agent output paths. --target is sugar for "set every per-agent
    # output to this consumer repo's standard location"; explicit
    # per-agent flags still override.
    target = args.target
    claude_out = args.claude_out or (
        target / ".claude" / "commands" if target else None
    )
    claude_skills_out = args.claude_skills_out or (
        target / ".claude" / "skills" if target else None
    )
    prompts_out = args.prompts_out or (
        target / ".github" / "prompts" if target else None
    )
    codex_router_out = args.codex_router_out or (
        target.joinpath(*_GENERATED_DOCS_SUBDIR) if target else None
    )
    codex_skills_out = args.codex_skills_out or (
        target / ".codex" / "skills" if target else None
    )

    # When invoked without --target and without explicit out paths
    # (e.g. the workstate-system source-of-truth regen) the generated adapters
    # fall back to the package-internal directory that lives OUTSIDE the shipped
    # payload. implementation note S3 moved the generator under workstate_system/payload/,
    # so `package_root` now resolves to the payload tree itself — but generated
    # adapters are internal artifacts that must never land under payload (the
    # tests/test_payload_colocation.py privacy guard forbids `/generated` and the
    # wheel ships payload/ wholesale). Anchor them at the package dir two levels
    # up (payload/ -> workstate_system/ -> packages/workstate-system) so the
    # tracked docs/workstate/generated/codex-command-router.md heals in place and
    # the gitignored .github/prompts/ adapters regenerate cleanly.
    internal_root = package_root.parents[1]
    if claude_out is None:
        claude_out = internal_root / ".claude" / "commands"
    if prompts_out is None:
        prompts_out = internal_root / ".github" / "prompts"
    if codex_router_out is None:
        codex_router_out = internal_root.joinpath(*_GENERATED_DOCS_SUBDIR)

    coadded_skill_sources: dict[str, tuple[dict, str]] = {}
    if args.plugin_overrides is not None:
        override_payload = _load_plugin_override_manifest(args.plugin_overrides)
        # adapter_rendered_skills is a resolution GATE only: it exists so the
        # portable-command composer can confirm each command's skill resolves
        # (upstream or co-added). It is discarded after composition and is never
        # an emission source — SKILL.md output is owned by the plugin tree — so
        # the 3-arg _render_plugin_skill (no harness_protocol) is sufficient
        # here and does not need to match _expected_plugin_outputs' 4-arg form.
        adapter_rendered_skills: dict[str, str] = {}
        for command in manifest["commands"]:
            slug = command["skill"]
            if slug in adapter_rendered_skills:
                continue
            structured, body = _load_skill(skills_source_root, slug)
            adapter_rendered_skills[slug] = _render_plugin_skill(
                structured, body, manifest
            )
        adapter_rendered_skills, _seen_slugs, _components = (
            _compose_plugin_skill_overrides(
                adapter_rendered_skills,
                args.plugin_overrides,
                override_payload,
            )
        )
        if override_payload.components.portable_commands:
            manifest, _command_components = _compose_plugin_portable_command_overrides(
                manifest,
                args.plugin_overrides,
                override_payload,
                composed_skills=adapter_rendered_skills,
            )
        coadded_skill_sources = _coadded_skill_sources(
            args.plugin_overrides, override_payload
        )

    outputs = _expected_outputs(
        manifest,
        skills_source_root,
        claude_out,
        prompts_out,
        codex_router_out,
        coadded_skill_sources,
    )
    skill_outputs = _expected_skill_outputs(
        manifest, skills_source_root, claude_skills_out, codex_skills_out
    )

    # repo_root for the codex-router-consumers sync is the target repo
    # if --target was given, otherwise the manifest-inferred package root.
    repo_root = target if target is not None else package_root
    hooks_outputs = _expected_hooks_outputs(repo_root)

    if args.check_coherence:
        try:
            from workstate_bootstrap.coherence import main as coherence_main  # type: ignore[import-not-found]
        except ImportError as exc:
            print(
                "--check-coherence requires workstate-bootstrap to be importable",
                file=sys.stderr,
            )
            print(f"import error: {exc}", file=sys.stderr)
            return 1
        return int(coherence_main([str(repo_root)]))

    if args.check_codex_router_blocks:
        failures = _sync_codex_router_consumers(manifest, repo_root, check=True)
        if failures:
            print(
                "Codex router consumer docs are out of sync with the manifest:",
                file=sys.stderr,
            )
            for failure in failures:
                print(f"  - {failure}", file=sys.stderr)
            return 1
        print("✓ codex-router: consumer docs match the manifest-rendered block.")
        return 0

    if args.check:
        exit_code = _check_outputs(outputs, claude_out, prompts_out, codex_router_out)
        skill_failures = _check_skill_outputs(skill_outputs)
        if skill_failures:
            print(
                "Generated skill files are out of sync with the manifest:",
                file=sys.stderr,
            )
            for failure in skill_failures:
                print(f"  - {failure}", file=sys.stderr)
            exit_code = 1
        hooks_failures = [
            f"hook config drift: {path}"
            for path, expected in hooks_outputs.items()
            if not path.exists() or path.read_text() != expected
        ]
        if hooks_failures:
            print(
                "Generated hook configs are out of sync with harness-protocol.yaml:",
                file=sys.stderr,
            )
            for failure in hooks_failures:
                print(f"  - {failure}", file=sys.stderr)
            exit_code = 1
        return exit_code

    _write_outputs(outputs)
    _write_outputs(hooks_outputs)
    failures = _sync_codex_router_consumers(manifest, repo_root, check=False)
    if failures:
        raise SystemExit("\n".join(failures))
    _write_skill_files(skill_outputs)
    expected_slugs = {command["skill"] for command in manifest["commands"]}
    _prune_stale_skill_dirs(claude_skills_out, expected_slugs)
    _prune_stale_skill_dirs(codex_skills_out, expected_slugs)
    _prune_legacy_portable_emissions(
        manifest, claude_out, claude_skills_out, codex_skills_out
    )
    total = len(outputs) + len(skill_outputs) + len(hooks_outputs)
    print(f"✓ agent-workflows: wrote {total} adapter files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
