#!/usr/bin/env python3
"""Generate host-specific workflow adapters from the canonical manifest.

Canonical sources (implementation note step 1):
  - manifest:  config/agent-workflows/portable_commands.json
  - skills:    skills/<slug>/skill.yaml + skills/<slug>/body.md

Generated outputs (one per agent surface):
  - .claude/commands/<id>.md       (Claude Code slash commands)
  - .claude/skills/<slug>/SKILL.md  (Claude-shape skill files)
  - .github/prompts/<id>.prompt.md  (VS Code Copilot prompts)
  - <codex-router-out>/codex-command-router.md  (Codex CLI router)
  - .codex/skills/<slug>/SKILL.md   (Codex-shape skill files)

The previous layout treated .claude/skills/<slug>/SKILL.md as canonical
and symlinked the Codex skill at it. The neutral layout makes both
agent surfaces generated artifacts so the canonical source is
model-agnostic.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sys
from pathlib import Path

try:
    import yaml
except ImportError as exc:  # pragma: no cover - PyYAML is a hard dep here
    raise SystemExit("PyYAML is required to read skill.yaml") from exc

_PROTOCOL_SRC = Path(__file__).resolve().parents[3] / "packages" / "workstate-protocol" / "src"
if _PROTOCOL_SRC.is_dir() and str(_PROTOCOL_SRC) not in sys.path:
    sys.path.insert(0, str(_PROTOCOL_SRC))

from pydantic import ValidationError

from workstate_protocol.bootstrap import (
    PluginEffectiveLock,
    PluginMcpServerPatch,
    PluginOverrideManifest,
)

GENERATOR_TAG = (
    "<!-- GENERATED by scripts/generate_agent_workflows.py; do not edit by hand. -->\n"
)
CLAUDE_HEADER = "# /{command_id}\n\n"
PROMPT_HEADER = "# /{command_id}\n\n"
CODEX_ROUTER_HEADER = "# Portable Command Router\n\n"
CODEX_ROUTER_BEGIN = "<!-- BEGIN GENERATED: codex-command-router -->"
CODEX_ROUTER_END = "<!-- END GENERATED: codex-command-router -->"
CODEX_ROUTER_CONSUMERS = (
    Path("docs/agentic/instructions.md"),
    Path("CLAUDE.md"),
)

_VALID_COMMAND_MODES = frozenset({"guide", "verify", "write"})

_PLUGIN_NAME = "workstate-system"
_PLUGIN_DESCRIPTION = (
    "Cross-harness agentic skills, slash commands, and MCP server registration."
)
_PLUGIN_OVERRIDE_MANIFEST = "overrides.yaml"
_PLUGIN_EFFECTIVE_LOCK = "plugin-lock.json"
_PLUGIN_HARNESSES: tuple[tuple[str, str], ...] = (
    ("claude", ".claude-plugin"),
    ("codex", ".codex-plugin"),
)


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _default_manifest_path() -> Path:
    return _repo_root() / "config" / "agent-workflows" / "portable_commands.json"


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=_default_manifest_path())
    parser.add_argument(
        "--skills-source-root",
        type=Path,
        help="Directory containing the canonical skills/<slug>/{skill.yaml, body.md}. "
        "Defaults to <manifest-package>/skills.",
    )
    parser.add_argument(
        "--claude-skills-root",
        type=Path,
        help="Deprecated alias for --skills-source-root (kept for one release).",
    )
    parser.add_argument(
        "--target",
        type=Path,
        help="Convenience: when set, default every per-agent --*-out path to this consumer "
        "repo root's standard locations. Per-agent flags still override.",
    )
    parser.add_argument("--claude-out", type=Path, help="Output dir for Claude Code commands.")
    parser.add_argument("--claude-skills-out", type=Path, help="Output dir for generated Claude SKILL.md files.")
    parser.add_argument("--prompts-out", type=Path, help="Output dir for VS Code Copilot prompts.")
    parser.add_argument("--codex-router-out", type=Path, help="Output dir for the Codex router doc.")
    parser.add_argument("--codex-skills-out", type=Path, help="Output dir for generated Codex skill files.")
    parser.add_argument(
        "--check-codex-router-blocks",
        action="store_true",
        help="Fail if the marker-delimited Codex router blocks drift from the manifest-rendered content.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated outputs differ from committed files.",
    )
    parser.add_argument(
        "--mode",
        choices=("legacy", "plugin"),
        default="legacy",
        help="Generator emission mode. 'legacy' (default) emits per-host "
        "adapter files; 'plugin' (WORKSTATE-REF-01) emits Claude/Codex plugin trees "
        "from the canonical skills + portable_commands + mcp_servers.yaml inputs.",
    )
    parser.add_argument(
        "--plugin-mcp-servers",
        type=Path,
        help="Path to mcp_servers.yaml (required when --mode=plugin). "
        "Defaults to <manifest-package>/config/agent-workflows/mcp_servers.yaml.",
    )
    parser.add_argument(
        "--plugin-out",
        type=Path,
        help="Destination root for emitted plugin trees (required when --mode=plugin). "
        "Trees are written to <plugin-out>/claude/ and <plugin-out>/codex/.",
    )
    parser.add_argument(
        "--plugin-overrides",
        type=Path,
        help="Optional consumer override root. When set, plugin mode composes an effective tree "
        "from canonical inputs plus <plugin-overrides>/overrides.yaml.",
    )
    parser.add_argument(
        "--plugin-base-remote-sha",
        type=str,
        help="Resolved 40-char upstream git SHA for plugin-lock.json when composing overrides.",
    )
    return parser.parse_args()


def _load_manifest(path: Path) -> dict:
    try:
        payload = json.loads(path.read_text())
    except FileNotFoundError as exc:
        raise SystemExit(f"Manifest not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Invalid JSON in {path}: {exc}") from exc

    if not isinstance(payload, dict):
        raise SystemExit(f"{path} must contain a JSON object.")

    version = payload.get("version")
    if version not in {1, 2}:
        raise SystemExit(f"{path} must declare version=1 or version=2; found {version!r}.")

    commands = payload.get("commands")
    if not isinstance(commands, list) or not commands:
        raise SystemExit(f"{path} must declare a non-empty commands list.")

    seen_ids: set[str] = set()
    for index, command in enumerate(commands):
        _validate_command(command, index)
        command_id = command["command_id"]
        if command_id in seen_ids:
            raise SystemExit(f"Duplicate command_id {command_id!r} in {path}.")
        seen_ids.add(command_id)

    hooks = payload.get("hooks", [])
    if hooks != [] and not isinstance(hooks, list):
        raise SystemExit(f"{path} must declare hooks as a list when present.")
    for index, hook in enumerate(hooks):
        _validate_hook(hook, index)
    return payload


def _validate_command(command: object, index: int) -> None:
    if not isinstance(command, dict):
        raise SystemExit(f"commands[{index}] must be an object.")

    required_string_fields = (
        "command_id",
        "skill",
        "makefile_target",
        "description",
        "execution_context",
    )
    for field in required_string_fields:
        value = command.get(field)
        if not isinstance(value, str) or not value.strip():
            raise SystemExit(f"commands[{index}].{field} must be a non-empty string.")

    command_id = command["command_id"]
    if any(ch not in "abcdefghijklmnopqrstuvwxyz0123456789-" for ch in command_id):
        raise SystemExit(
            f"commands[{index}].command_id must be lowercase kebab-case; found {command_id!r}."
        )

    # WORKSTATE-REF-1: declare-or-fail mode field. The portable-commands
    # interaction-mode taxonomy is the spec contract between MCP-writer
    # skills and consumer routing; every command must pick one of three.
    mode = command.get("mode")
    if mode is None:
        raise SystemExit(
            f"commands[{index}].mode is required; declare one of "
            f"'guide', 'verify', 'write'."
        )
    if mode not in _VALID_COMMAND_MODES:
        raise SystemExit(
            f"commands[{index}].mode must be one of "
            f"{sorted(_VALID_COMMAND_MODES)!r}; found mode={mode!r}."
        )

    loop = command.get("loop")
    if (
        not isinstance(loop, list)
        or not loop
        or not all(isinstance(item, str) and item.strip() for item in loop)
    ):
        raise SystemExit(f"commands[{index}].loop must be a non-empty list of strings.")

    secondary_targets = command.get("secondary_targets", [])
    if secondary_targets != [] and (
        not isinstance(secondary_targets, list)
        or not all(isinstance(item, str) and item.strip() for item in secondary_targets)
    ):
        raise SystemExit(
            f"commands[{index}].secondary_targets must be a list of strings when present."
        )

    argument_schema = command.get("argument_schema")
    if not isinstance(argument_schema, list):
        raise SystemExit(f"commands[{index}].argument_schema must be a list.")
    for arg_index, arg in enumerate(argument_schema):
        if not isinstance(arg, dict):
            raise SystemExit(
                f"commands[{index}].argument_schema[{arg_index}] must be an object."
            )
        name = arg.get("name")
        description = arg.get("description")
        required = arg.get("required")
        if not isinstance(name, str) or not name.strip():
            raise SystemExit(
                f"commands[{index}].argument_schema[{arg_index}].name must be a non-empty string."
            )
        if not isinstance(description, str) or not description.strip():
            raise SystemExit(
                f"commands[{index}].argument_schema[{arg_index}].description must be a non-empty string."
            )
        if not isinstance(required, bool):
            raise SystemExit(
                f"commands[{index}].argument_schema[{arg_index}].required must be boolean."
            )


def _validate_hook(hook: object, index: int) -> None:
    if not isinstance(hook, dict):
        raise SystemExit(f"hooks[{index}] must be an object.")

    required_string_fields = ("hook_id", "description", "trigger")
    for field in required_string_fields:
        value = hook.get(field)
        if not isinstance(value, str) or not value.strip():
            raise SystemExit(f"hooks[{index}].{field} must be a non-empty string.")

    required_artifacts = hook.get("required_artifacts")
    if not isinstance(required_artifacts, list) or not required_artifacts:
        raise SystemExit(
            f"hooks[{index}].required_artifacts must be a non-empty list."
        )
    adapters = hook.get("adapters")
    if not isinstance(adapters, list) or not adapters:
        raise SystemExit(f"hooks[{index}].adapters must be a non-empty list.")


def _render_arguments(command: dict) -> list[str]:
    args = command.get("argument_schema", [])
    if not args:
        return ["Arguments: none."]
    lines = ["Arguments:"]
    for arg in args:
        status = "required" if arg["required"] else "optional"
        lines.append(f"- `{arg['name']}` ({status}): {arg['description']}")
    return lines


def _render_targets(command: dict) -> list[str]:
    lines = [f"Makefile entry point: `{command['makefile_target']}`"]
    secondary = command.get("secondary_targets", [])
    if secondary:
        lines.append("Secondary entry points:")
        lines.extend(f"- `{target}`" for target in secondary)
    return lines


def _render_claude(command: dict) -> str:
    lines = [
        GENERATOR_TAG.rstrip(),
        "",
        CLAUDE_HEADER.format(command_id=command["command_id"]).rstrip(),
        "",
        f"Active skill: `{command['skill']}`",
        "",
        f"Mode: `{command['mode']}`",
        "",
        *_render_targets(command),
        "",
        *_render_arguments(command),
        "",
        f"Execution context: {command['execution_context']}",
        "",
        "Loop:",
        *(f"- {item}" for item in command["loop"]),
        "",
    ]
    return "\n".join(lines)


def _render_prompt_with_guidance(command: dict, prompt_guidance: str | None) -> str:
    lines = [
        GENERATOR_TAG.rstrip(),
        "",
        PROMPT_HEADER.format(command_id=command["command_id"]).rstrip(),
        "",
        f"Load the `{command['skill']}` skill for this workflow.",
        "",
        f"Description: {command['description']}",
        "",
        f"Mode: `{command['mode']}`",
        "",
        *_render_targets(command),
        "",
        *_render_arguments(command),
        "",
        f"Execution context: {command['execution_context']}",
        "",
        "Loop:",
        *(f"- {item}" for item in command["loop"]),
        "",
    ]
    if prompt_guidance:
        lines.extend(
            [
                "Canonical Skill Guidance:",
                "",
                *prompt_guidance.rstrip().splitlines(),
                "",
            ]
        )
    return "\n".join(lines)


def _extract_markdown_section(body: str, heading: str) -> str | None:
    lines = body.splitlines()
    marker = f"## {heading}"
    start: int | None = None

    for index, line in enumerate(lines):
        if line.strip() == marker:
            start = index
            break

    if start is None:
        return None

    end = len(lines)
    for index in range(start + 1, len(lines)):
        if lines[index].startswith("## "):
            end = index
            break

    return "\n".join(lines[start:end]).strip()


def _extract_prompt_guidance(structured: dict, body: str) -> str | None:
    _, generator = _strip_generator_metadata(structured)
    requested_sections = generator.get("prompt_body_sections") or []
    if not isinstance(requested_sections, list):
        requested_sections = []

    # VS Code Copilot does not consume the Claude/Codex plugin tree, so
    # its generated prompt must carry the canonical skill implementation
    # by default. Individual skills can keep prompts smaller by declaring
    # generator.prompt_body_sections in skill.yaml.
    if not requested_sections:
        return body.strip() or None

    sections: list[str] = []
    for heading in requested_sections:
        if not isinstance(heading, str) or not heading.strip():
            continue
        section = _extract_markdown_section(body, heading.strip())
        if section:
            sections.append(section)

    if not sections:
        return None
    return "\n\n".join(sections)


def _render_codex_router_body(manifest: dict) -> list[str]:
    commands: list[dict] = manifest["commands"]
    managed_ids = ", ".join(f"`/{command['command_id']}`" for command in commands)
    return [
        (
            "If a user prompt begins with a registered `/command_id`, treat that prefix as a portable workflow "
            "command routed through `config/agent-workflows/portable_commands.json`."
        ),
        "",
        f"Current managed ids: {managed_ids}.",
        "",
        "Routing rules:",
        "",
        "- Strip the leading `/command_id` token before normal intent analysis.",
        "- Load the mapped skill from the manifest and use its `makefile_target` as the primary entry point when one exists.",
        "- Interpret the remainder of the user message using the manifest-defined argument names.",
        "- If generated adapters drift from the manifest, run `make generate-agent-workflows`; `make check-agent-workflows` verifies Claude, VS Code, and Codex outputs together.",
        "",
        "Command map:",
        "",
        *(
            f"- `/{command['command_id']}` ({command['mode']}) -> skill `{command['skill']}` -> `{command['makefile_target']}`"
            for command in commands
        ),
    ]


def _render_codex_router(manifest: dict) -> str:
    lines = [
        GENERATOR_TAG.rstrip(),
        "",
        CODEX_ROUTER_HEADER.rstrip(),
        "",
        *_render_codex_router_body(manifest),
        "",
    ]
    return "\n".join(lines)


def _render_codex_router_embed(manifest: dict) -> str:
    lines = [
        GENERATOR_TAG.rstrip(),
        "",
        *_render_codex_router_body(manifest),
        "",
    ]
    return "\n".join(lines)


def _replace_marked_block(content: str, replacement: str) -> tuple[str, bool]:
    begin = content.find(CODEX_ROUTER_BEGIN)
    end = content.find(CODEX_ROUTER_END)
    if begin == -1 or end == -1 or end < begin:
        raise ValueError("missing codex router markers")
    if (
        content.find(CODEX_ROUTER_BEGIN, begin + 1) != -1
        or content.find(CODEX_ROUTER_END, end + 1) != -1
    ):
        raise ValueError("multiple codex router marker blocks")

    block_start = begin + len(CODEX_ROUTER_BEGIN)
    before = content[:block_start]
    current = content[block_start:end]
    after = content[end:]
    new_block = f"\n{replacement}\n"
    return before + new_block + after, current != new_block


def _sync_codex_router_consumers(
    manifest: dict, repo_root: Path, check: bool
) -> list[str]:
    replacement = _render_codex_router_embed(manifest)
    failures: list[str] = []
    for relative_path in CODEX_ROUTER_CONSUMERS:
        absolute_path = repo_root / relative_path
        try:
            content = absolute_path.read_text()
        except FileNotFoundError:
            # In fresh target repos these consumer docs may not exist
            # yet (no CLAUDE.md, no docs/agentic/instructions.md). Treat
            # that as "nothing to sync" rather than a hard failure;
            # --check still flags it so CI can require both.
            if check:
                failures.append(f"missing codex router consumer: {absolute_path}")
            continue

        try:
            updated, changed = _replace_marked_block(content, replacement)
        except ValueError as exc:
            failures.append(f"{absolute_path}: {exc}")
            continue

        if check:
            if changed:
                failures.append(f"codex router drift detected: {absolute_path}")
            continue

        if changed:
            absolute_path.write_text(updated)
    return failures


def _load_skill(skills_source_root: Path, slug: str) -> tuple[dict, str]:
    """Read the canonical neutral layout: skill.yaml + body.md.

    Returns ``(structured_metadata, prose_body)``. Raises SystemExit
    with a precise message on missing or malformed files.
    """
    slug_dir = skills_source_root / slug
    skill_yaml = slug_dir / "skill.yaml"
    body_md = slug_dir / "body.md"
    if not skill_yaml.is_file():
        raise SystemExit(
            f"manifest references skill {slug!r} but canonical source is missing: {skill_yaml}"
        )
    if not body_md.is_file():
        raise SystemExit(
            f"manifest references skill {slug!r} but body.md is missing: {body_md}"
        )
    structured = yaml.safe_load(skill_yaml.read_text()) or {}
    if not isinstance(structured, dict):
        raise SystemExit(f"{skill_yaml}: must parse to a mapping")
    return structured, body_md.read_text()


def _strip_generator_metadata(structured: dict) -> tuple[dict, dict]:
    """Split canonical structured metadata from per-agent overrides.

    The neutral skill.yaml carries a top-level ``generator`` key whose
    children describe per-agent rendering hints
    (e.g. ``generator.claude_overrides.disable-model-invocation``).
    Returns ``(canonical, generator_block)`` where ``canonical`` is the
    structured manifest minus the generator block. The generator block
    is consumed by the per-agent renderers to compose agent-specific
    frontmatter.
    """
    if not isinstance(structured, dict):
        return {}, {}
    structured = dict(structured)
    generator = structured.pop("generator", {}) or {}
    if not isinstance(generator, dict):
        generator = {}
    return structured, generator


def _render_claude_skill(slug: str, structured: dict, body: str) -> str:
    """Compose Claude-shape SKILL.md from canonical skill.yaml + body.md.

    Re-attaches Claude-only frontmatter keys carried under
    ``generator.claude_overrides`` (e.g. ``disable-model-invocation``).
    """
    canonical, generator = _strip_generator_metadata(structured)
    overrides = generator.get("claude_overrides") or {}
    frontmatter = {**canonical, **overrides}
    fm_text = yaml.safe_dump(frontmatter, sort_keys=False, default_flow_style=False).rstrip()
    body = body if body.endswith("\n") else body + "\n"
    return f"---\n{fm_text}\n---\n\n{body}"


def _render_codex_skill(slug: str, structured: dict, body: str) -> str:
    """Compose Codex-shape SKILL.md.

    Codex skills carry the same YAML+Markdown shape as Claude. We keep
    only the canonical fields here — Codex doesn't honor Claude's
    ``disable-model-invocation`` knob, so we drop the
    ``generator.claude_overrides`` block.
    """
    canonical, _ = _strip_generator_metadata(structured)
    fm_text = yaml.safe_dump(canonical, sort_keys=False, default_flow_style=False).rstrip()
    body = body if body.endswith("\n") else body + "\n"
    return f"---\n{fm_text}\n---\n\n{body}"


def _expected_skill_outputs(
    manifest: dict,
    skills_source_root: Path,
    claude_skills_out: Path | None,
    codex_skills_out: Path | None,
) -> dict[Path, str]:
    """Map per-agent skill output paths to their generated content.

    WORKSTATE-REF-02 implementation note cutover: returns an empty mapping. The cross-harness
    `.claude/skills/<slug>/SKILL.md` and `.codex/skills/<slug>/SKILL.md`
    surfaces are owned by the plugin tree (ADR-001); the legacy mode no
    longer duplicates them per consumer. ``--claude-skills-out`` and
    ``--codex-skills-out`` are accepted (and the destinations are still
    pruned by ``_prune_stale_skill_dirs``) for backwards compatibility
    with existing operator scripts, but no new content is written.
    """
    # Loading every skill at runtime is no longer necessary now that the
    # legacy mode emits nothing here; the plugin-tree emission does its
    # own load via ``_render_skill_body``. Keeping the input parameters
    # so the call sites do not have to change.
    del manifest, skills_source_root, claude_skills_out, codex_skills_out
    return {}


def _write_skill_files(outputs: dict[Path, str]) -> None:
    """Write generated skill files; replace pre-existing symlinks
    pointing at a former canonical source.
    """
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        # If the parent directory used to be a symlink (legacy layout
        # where .codex/skills/<slug> linked to .claude/skills/<slug>),
        # replace it with a real directory.
        if path.parent.is_symlink():
            target = path.parent
            target.unlink()
            target.mkdir(parents=True, exist_ok=True)
        if path.is_symlink():
            path.unlink()
        # Codex output was previously emitted as lowercase skill.md.
        # On case-insensitive filesystems writing SKILL.md over an
        # existing skill.md preserves the lowercase casing, which
        # breaks Codex skill discovery. Remove any legacy lowercase
        # sibling before writing so the on-disk name is exactly SKILL.md.
        if path.name == "SKILL.md":
            legacy = path.with_name("skill.md")
            if legacy.is_symlink() or legacy.exists():
                legacy.unlink()
        path.write_text(content)


def _prune_stale_skill_dirs(
    out_root: Path | None, expected_slugs: set[str]
) -> None:
    """Remove generated skill directories whose slug is no longer in the manifest."""
    if out_root is None or not out_root.exists():
        return
    for entry in out_root.iterdir():
        if entry.name in expected_slugs:
            continue
        if entry.is_symlink() or entry.is_file():
            entry.unlink()
        else:
            shutil.rmtree(entry)


def _prune_legacy_portable_emissions(
    manifest: dict,
    claude_commands_out: Path | None,
    claude_skills_out: Path | None,
    codex_skills_out: Path | None,
) -> list[Path]:
    """Remove legacy emissions for portable command_ids / skill slugs.

    WORKSTATE-REF-02 implementation note stopped writing `.claude/commands/<id>.md`,
    `.claude/skills/<slug>/SKILL.md`, and `.codex/skills/<slug>/SKILL.md`
    for portable manifest entries; those surfaces are owned by the
    plugin tree now. ``_prune_stale_skill_dirs`` only removes slugs that
    were dropped from the manifest, so pre-existing legacy files for
    *still-portable* slugs would otherwise persist as duplicates of the
    plugin-tree content.

    Deletion is conservative:
      - ``.claude/commands/<id>.md``: only removed when the file starts
        with ``GENERATOR_TAG`` (same gate as ``_extra_generated_files``);
        hand-authored slash commands at the same id are left alone.
      - ``.claude/skills/<slug>/SKILL.md`` and ``.codex/skills/<slug>/SKILL.md``
        (plus the legacy lowercase ``skill.md`` sibling): removed only
        when the file's frontmatter ``name`` matches the portable slug,
        which is the shape every pre-cutover legacy emission has (the
        legacy generator copied ``skills/<slug>/body.md`` whose canonical
        frontmatter declares ``name: <slug>``). A file with a non-matching
        ``name`` is treated as a hand-authored project-local override and
        left alone — this is the BR-04 safety gate that keeps the prune
        helper from clobbering contributor files at colliding paths.
      - The parent slug directory is removed only when it becomes empty
        after the SKILL.md deletion, so user-added siblings are
        preserved.
    """
    removed: list[Path] = []
    for command in manifest["commands"]:
        command_id = command["command_id"]
        slug = command["skill"]
        if claude_commands_out is not None:
            legacy_command = claude_commands_out / f"{command_id}.md"
            if legacy_command.is_file():
                try:
                    if legacy_command.read_text().startswith(GENERATOR_TAG):
                        legacy_command.unlink()
                        removed.append(legacy_command)
                except OSError:
                    pass
        for skills_root in (claude_skills_out, codex_skills_out):
            if skills_root is None:
                continue
            skill_dir = skills_root / slug
            if not skill_dir.exists():
                continue
            for name in ("SKILL.md", "skill.md"):
                candidate = skill_dir / name
                if candidate.is_symlink() or candidate.is_file():
                    if _legacy_skill_matches_portable_slug(candidate, slug):
                        candidate.unlink()
                        removed.append(candidate)
            try:
                if not any(skill_dir.iterdir()):
                    skill_dir.rmdir()
                    removed.append(skill_dir)
            except OSError:
                pass
    return removed


def _legacy_skill_matches_portable_slug(path: Path, slug: str) -> bool:
    """Return True iff ``path`` looks like a pre-cutover legacy SKILL.md
    emission for ``slug`` — i.e. it has YAML frontmatter whose ``name``
    field equals the slug. A file at a portable slug path that declares a
    different ``name`` (or has no parseable frontmatter) is treated as a
    hand-authored project-local override and preserved.
    """
    try:
        text = path.read_text()
    except OSError:
        return False
    if not text.startswith("---\n"):
        return False
    try:
        _, fm_raw, _ = text.split("---\n", 2)
    except ValueError:
        return False
    try:
        frontmatter = yaml.safe_load(fm_raw) or {}
    except yaml.YAMLError:
        return False
    if not isinstance(frontmatter, dict):
        return False
    return frontmatter.get("name") == slug


def _check_skill_outputs(outputs: dict[Path, str]) -> list[str]:
    failures: list[str] = []
    for path, expected in outputs.items():
        if not path.exists():
            failures.append(f"missing generated skill file: {path}")
            continue
        if path.is_symlink():
            failures.append(
                f"generated skill path is a symlink (legacy layout): {path}"
            )
            continue
        # Case-insensitive filesystems resolve Path('SKILL.md') to an
        # on-disk skill.md, hiding stale lowercase emissions from the
        # drift gate. Codex skill discovery is case-sensitive, so verify
        # the actual directory entry name matches the expected casing.
        if path.parent.is_dir() and path.name not in {
            entry.name for entry in path.parent.iterdir()
        }:
            failures.append(
                f"generated skill file has wrong on-disk casing: {path} "
                f"(expected exact name {path.name!r})"
            )
            continue
        actual = path.read_text()
        if actual != expected:
            failures.append(f"drift detected: {path}")
    return failures


def _expected_outputs(
    manifest: dict,
    skills_source_root: Path,
    claude_out: Path,
    prompts_out: Path,
    codex_router_out: Path,
) -> dict[Path, str]:
    # WORKSTATE-REF-02 implementation note cutover: the cross-harness `.claude/commands/<id>.md`
    # surface for portable slugs is no longer emitted here — consumers
    # discover those slash commands from the plugin tree (ADR-001) and
    # the codex-command-router block. Only Copilot prompts and the
    # router doc are produced from this code path.
    outputs: dict[Path, str] = {}
    for command in manifest["commands"]:
        command_id = command["command_id"]
        structured, body = _load_skill(skills_source_root, command["skill"])
        outputs[prompts_out / f"{command_id}.prompt.md"] = _render_prompt_with_guidance(
            command,
            _extract_prompt_guidance(structured, body),
        )
    outputs[codex_router_out / "codex-command-router.md"] = _render_codex_router(
        manifest
    )
    return outputs


def _write_outputs(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def _extra_generated_files(root: Path, expected_paths: set[Path]) -> list[Path]:
    if not root.exists():
        return []
    extras: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if path in expected_paths:
            continue
        try:
            content = path.read_text()
        except OSError:
            continue
        if content.startswith(GENERATOR_TAG):
            extras.append(path)
    return sorted(extras)


def _check_outputs(
    outputs: dict[Path, str],
    claude_out: Path,
    prompts_out: Path,
    codex_router_out: Path,
) -> int:
    failures: list[str] = []
    for path, expected in outputs.items():
        if not path.exists():
            failures.append(f"missing generated file: {path}")
            continue
        actual = path.read_text()
        if actual != expected:
            failures.append(f"drift detected: {path}")

    expected_paths = set(outputs)
    # WORKSTATE-REF-02 implementation note: claude_out is no longer manifest-driven (the
    # `.claude/commands/<id>.md` surface moved to the plugin tree), so
    # any tagged file under claude_out — e.g. the harness-only
    # `spec.md` — is intentionally outside this manifest's scope and
    # must not be flagged as stale here.
    extras = (
        _extra_generated_files(prompts_out, expected_paths)
        + _extra_generated_files(codex_router_out, expected_paths)
    )
    for path in extras:
        failures.append(f"stale generated file not declared in manifest: {path}")

    if failures:
        print(
            "Agent workflow adapters are out of sync with the manifest:",
            file=sys.stderr,
        )
        for failure in failures:
            print(f"  - {failure}", file=sys.stderr)
        return 1
    print("✓ agent-workflows: generated adapters match the manifest.")
    return 0


def _load_mcp_servers_manifest(path: Path) -> dict:
    """Load and shallow-validate mcp_servers.yaml (WORKSTATE-REF-01 input)."""
    try:
        payload = yaml.safe_load(path.read_text()) or {}
    except FileNotFoundError as exc:
        raise SystemExit(f"mcp_servers manifest not found: {path}") from exc
    if not isinstance(payload, dict):
        raise SystemExit(f"{path}: must parse to a mapping")
    if payload.get("version") != 1:
        raise SystemExit(f"{path}: must declare version=1; found {payload.get('version')!r}")
    plugin_version = payload.get("plugin_version")
    if not isinstance(plugin_version, str) or not plugin_version.strip():
        raise SystemExit(f"{path}: plugin_version must be a non-empty string")
    servers = payload.get("mcp_servers")
    if not isinstance(servers, list) or not servers:
        raise SystemExit(f"{path}: mcp_servers must be a non-empty list")
    for index, server in enumerate(servers):
        if not isinstance(server, dict):
            raise SystemExit(f"{path}: mcp_servers[{index}] must be a mapping")
        for field in ("name", "command"):
            value = server.get(field)
            if not isinstance(value, str) or not value.strip():
                raise SystemExit(
                    f"{path}: mcp_servers[{index}].{field} must be a non-empty string"
                )
        args = server.get("args", [])
        if not isinstance(args, list) or not all(isinstance(a, str) for a in args):
            raise SystemExit(
                f"{path}: mcp_servers[{index}].args must be a list of strings"
            )
        harnesses = server.get("harnesses", [])
        if not isinstance(harnesses, list) or not all(
            isinstance(h, str) for h in harnesses
        ):
            raise SystemExit(
                f"{path}: mcp_servers[{index}].harnesses must be a list of strings"
            )
    return payload


def _render_mcp_servers_json(mcp_manifest: dict, harness: str) -> str:
    """Render the .mcp.json blob for the requested harness.

    Servers whose ``harnesses`` list excludes the harness are skipped.
    Output ordering follows the manifest insertion order; each entry
    carries ``"type": "stdio"`` to stay compatible with the bootstrap
    install path.
    """
    entries: dict[str, dict] = {}
    for server in mcp_manifest["mcp_servers"]:
        harnesses = server.get("harnesses") or []
        if harnesses and harness not in harnesses:
            continue
        entries[server["name"]] = {
            "type": "stdio",
            "command": server["command"],
            "args": list(server.get("args", [])),
        }
        env = server.get("env")
        if isinstance(env, dict) and env:
            entries[server["name"]]["env"] = dict(env)
    payload = {"mcpServers": entries}
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def _render_plugin_manifest_json(plugin_version: str) -> str:
    """Render the metadata-only plugin.json (live-doc verified shape).

    Both ``.claude-plugin/plugin.json`` and ``.codex-plugin/plugin.json``
    share the same body — only the parent directory name differs per
    harness.
    """
    payload = {
        "name": _PLUGIN_NAME,
        "version": plugin_version,
        "description": _PLUGIN_DESCRIPTION,
        "skills": "./skills/",
        "mcpServers": "./.mcp.json",
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def _render_plugin_skill(structured: dict, body: str) -> str:
    """Render a SKILL.md body for the plugin tree.

    ADR-001 mandates byte-identical SKILL.md across harnesses, so this
    intentionally drops the ``generator.claude_overrides`` block.
    """
    canonical, _ = _strip_generator_metadata(structured)
    fm_text = yaml.safe_dump(canonical, sort_keys=False, default_flow_style=False).rstrip()
    body = body if body.endswith("\n") else body + "\n"
    return f"---\n{fm_text}\n---\n\n{body}"


def _sha256_digest(content: str) -> str:
    return f"sha256:{hashlib.sha256(content.encode('utf-8')).hexdigest()}"


def _load_plugin_override_manifest(override_root: Path) -> PluginOverrideManifest:
    path = override_root / _PLUGIN_OVERRIDE_MANIFEST
    try:
        payload = yaml.safe_load(path.read_text()) or {}
    except FileNotFoundError as exc:
        raise SystemExit(f"plugin override manifest not found: {path}") from exc
    try:
        return PluginOverrideManifest.model_validate(payload)
    except ValidationError as exc:
        raise SystemExit(f"{path}: {exc}") from exc


def _compose_plugin_skill_overrides(
    rendered_skills: dict[str, str],
    override_root: Path,
    payload: PluginOverrideManifest,
) -> tuple[dict[str, str], list[str], list[dict[str, str]]]:
    composed = dict(rendered_skills)
    skill_order = list(rendered_skills)
    components: list[dict[str, str]] = []

    skills = payload.components.skills
    for slug, override in sorted(skills.items()):
        mode = override.mode
        relative_path = override.path
        if mode == "replace":
            if slug not in composed:
                raise SystemExit(
                    f"{override_root / _PLUGIN_OVERRIDE_MANIFEST}: cannot replace unknown skill {slug!r}"
                )
            assert relative_path is not None
            upstream_digest = override.upstream_digest
            assert upstream_digest is not None
            base_digest = _sha256_digest(composed[slug])
            stale_component: dict[str, str] = {}
            if upstream_digest != base_digest:
                on_upstream_change = override.on_upstream_change
                if on_upstream_change == "warn":
                    stale_component = {
                        "status": "stale",
                        "override_path": relative_path,
                        "recorded_upstream_digest": upstream_digest,
                        "current_base_digest": base_digest,
                    }
                elif on_upstream_change != "ignore":
                    raise SystemExit(
                        f"{override_root / _PLUGIN_OVERRIDE_MANIFEST}: components.skills.{slug}.upstream_digest "
                        f"{upstream_digest!r} does not match current base digest {base_digest!r}"
                    )
            override_path = override_root / relative_path
            try:
                composed_skill = override_path.read_text()
            except FileNotFoundError as exc:
                raise SystemExit(f"plugin override skill not found: {override_path}") from exc
            composed[slug] = composed_skill
            components.append(
                {
                    "component_kind": "skill",
                    "name": slug,
                    "mode": "replace",
                    "effective_digest": _sha256_digest(composed_skill),
                    **stale_component,
                }
            )
            continue

        if mode == "add":
            if slug in composed:
                raise SystemExit(
                    f"{override_root / _PLUGIN_OVERRIDE_MANIFEST}: cannot add existing skill {slug!r}; "
                    "use mode=replace instead"
                )
            assert relative_path is not None
            override_path = override_root / relative_path
            try:
                composed_skill = override_path.read_text()
            except FileNotFoundError as exc:
                raise SystemExit(f"plugin override skill not found: {override_path}") from exc
            composed[slug] = composed_skill
            skill_order.append(slug)
            components.append(
                {
                    "component_kind": "skill",
                    "name": slug,
                    "mode": "add",
                    "effective_digest": _sha256_digest(composed_skill),
                }
            )
            continue

        if mode == "disable":
            if slug not in composed:
                raise SystemExit(
                    f"{override_root / _PLUGIN_OVERRIDE_MANIFEST}: cannot disable unknown skill {slug!r}"
                )
            del composed[slug]
            skill_order = [entry for entry in skill_order if entry != slug]
            components.append(
                {
                    "component_kind": "skill",
                    "name": slug,
                    "mode": "disable",
                    "effective_digest": _sha256_digest(f"disabled:{slug}\n"),
                }
            )
            continue

        raise SystemExit(
            f"{override_root / _PLUGIN_OVERRIDE_MANIFEST}: components.skills.{slug}.mode "
            f"must be one of 'replace', 'add', or 'disable' for the current composition slice; found {mode!r}"
        )

    return composed, skill_order, components


def _load_plugin_mcp_patch(override_root: Path, relative_path: str) -> PluginMcpServerPatch:
    path = override_root / relative_path
    try:
        payload = yaml.safe_load(path.read_text()) or {}
    except FileNotFoundError as exc:
        raise SystemExit(f"plugin override MCP patch not found: {path}") from exc
    try:
        return PluginMcpServerPatch.model_validate(payload)
    except ValidationError as exc:
        raise SystemExit(f"{path}: {exc}") from exc


def _canonical_mcp_server_digest(server: dict[str, object]) -> str:
    return _sha256_digest(json.dumps(server, sort_keys=True, ensure_ascii=False))


def _base_plugin_mcp_server(name: str, mode: str, server: dict[str, object] | None) -> dict[str, object]:
    if mode == "add":
        return {"name": name, "command": "", "args": []}
    if server is None:
        raise SystemExit(
            f"MCP server override references unknown canonical server {name!r}; use mode='add' to declare a new one"
        )
    return dict(server)


def _compose_plugin_mcp_overrides(
    mcp_manifest: dict,
    override_root: Path,
    payload: PluginOverrideManifest,
) -> tuple[dict, list[dict[str, str]], list[str]]:
    servers = [dict(server) for server in mcp_manifest["mcp_servers"]]
    by_name = {
        server["name"]: server
        for server in servers
        if isinstance(server.get("name"), str)
    }
    components: list[dict[str, str]] = []
    audit_lines: list[str] = []

    for name, override in sorted(payload.components.mcp_servers.items()):
        mode = override.mode
        if mode == "disable":
            if name not in by_name:
                raise SystemExit(
                    f"{override_root / _PLUGIN_OVERRIDE_MANIFEST}: cannot disable unknown MCP server {name!r}"
                )
            servers = [entry for entry in servers if entry.get("name") != name]
            by_name.pop(name, None)
            components.append(
                {
                    "component_kind": "mcp_server",
                    "name": name,
                    "mode": "disable",
                    "effective_digest": _sha256_digest(f"disabled:{name}\n"),
                }
            )
            audit_lines.append(f"mcp audit: {name} disabled")
            continue

        if mode not in {"patch", "add"}:
            raise SystemExit(
                f"{override_root / _PLUGIN_OVERRIDE_MANIFEST}: components.mcp_servers.{name}.mode "
                f"must be one of 'patch', 'disable', or 'add'; found {mode!r}"
            )

        server = by_name.get(name)
        if mode == "patch" and server is None:
            raise SystemExit(
                f"{override_root / _PLUGIN_OVERRIDE_MANIFEST}: cannot patch unknown MCP server {name!r}"
            )
        if mode == "add" and server is not None:
            raise SystemExit(
                f"{override_root / _PLUGIN_OVERRIDE_MANIFEST}: cannot add existing MCP server {name!r}; use mode='patch' or 'disable'"
            )
        if not override.requires_trust_ack:
            raise SystemExit(
                f"{override_root / _PLUGIN_OVERRIDE_MANIFEST}: components.mcp_servers.{name}.requires_trust_ack "
                "must be true before patching MCP command, args, or env"
            )

        assert override.patch_path is not None
        patch = _load_plugin_mcp_patch(override_root, override.patch_path)
        if patch.target_server != name:
            raise SystemExit(
                f"{override_root / override.patch_path}: target_server {patch.target_server!r} "
                f"does not match override key {name!r}"
            )

        composed = _base_plugin_mcp_server(name, mode, server)
        mutated_fields: list[str] = []
        disabled = False
        for op in patch.ops:
            if op.op == "replace_command":
                composed["command"] = op.value
                mutated_fields.append("command")
                continue
            if op.op == "replace_args":
                composed["args"] = list(op.value)
                mutated_fields.append("args")
                continue
            if op.op == "append_args":
                composed["args"] = [*list(composed.get("args", [])), *op.value]
                mutated_fields.append("args")
                continue
            if op.op == "upsert_env":
                env = dict(composed.get("env", {}))
                env[op.name] = op.value
                composed["env"] = env
                mutated_fields.append("env")
                continue
            if op.op == "remove_env":
                env = dict(composed.get("env", {}))
                env.pop(op.name, None)
                if env:
                    composed["env"] = env
                else:
                    composed.pop("env", None)
                mutated_fields.append("env")
                continue
            if op.op == "disable_server":
                if mode == "add":
                    raise SystemExit(
                        f"{override_root / override.patch_path}: disable_server cannot be used with components.mcp_servers.{name}.mode='add'"
                    )
                disabled = True
                break

        if disabled:
            servers = [entry for entry in servers if entry.get("name") != name]
            by_name.pop(name, None)
            components.append(
                {
                    "component_kind": "mcp_server",
                    "name": name,
                    "mode": "disable",
                    "effective_digest": _sha256_digest(f"disabled:{name}\n"),
                }
            )
            audit_lines.append(f"mcp audit: {name} disabled")
            continue

        command = composed.get("command")
        args = composed.get("args", [])
        if not isinstance(command, str) or not command:
            raise SystemExit(
                f"{override_root / override.patch_path}: composed MCP server {name!r} must set a non-empty command"
            )
        if not isinstance(args, list) or not all(isinstance(arg, str) for arg in args):
            raise SystemExit(
                f"{override_root / override.patch_path}: composed MCP server {name!r} must carry args as a list of strings"
            )

        if mode == "add":
            servers.append(composed)
        else:
            for index, existing in enumerate(servers):
                if existing.get("name") == name:
                    servers[index] = composed
                    break
        by_name[name] = composed
        unique_fields = [field for field in ("command", "args", "env") if field in mutated_fields]
        components.append(
            {
                "component_kind": "mcp_server",
                "name": name,
                "mode": mode,
                "effective_digest": _canonical_mcp_server_digest(composed),
            }
        )
        if unique_fields:
            audit_lines.append(f"mcp audit: {name} {', '.join(unique_fields)}")

    return {
        **mcp_manifest,
        "mcp_servers": servers,
    }, components, audit_lines


def _render_plugin_effective_lock_json(
    base_remote_sha: str,
    effective_root: Path,
    components: list[dict[str, str]],
) -> str:
    if len(base_remote_sha) != 40 or any(ch not in "0123456789abcdef" for ch in base_remote_sha):
        raise SystemExit(
            f"--plugin-base-remote-sha must be a 40-char lowercase git SHA; found {base_remote_sha!r}"
        )
    payload = PluginEffectiveLock.model_validate(
        {
        "schema_version": 1,
        "plugin": _PLUGIN_NAME,
        "base_remote_sha": base_remote_sha,
        "effective_root": ".",
        "components": components,
        }
    ).model_dump(mode="json")
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def _expected_plugin_outputs(
    manifest: dict,
    mcp_manifest: dict,
    skills_source_root: Path,
    plugin_out: Path,
    plugin_overrides: Path | None = None,
    plugin_base_remote_sha: str | None = None,
) -> tuple[dict[Path, str], list[str]]:
    """Map every emitted plugin-tree file to its rendered content.

    Layout per harness::

        <plugin_out>/<harness>/<plugin_dir>/plugin.json
        <plugin_out>/<harness>/.mcp.json
        <plugin_out>/<harness>/skills/<slug>/SKILL.md
    """
    outputs: dict[Path, str] = {}
    audit_lines: list[str] = []
    plugin_version = mcp_manifest["plugin_version"]
    plugin_manifest_body = _render_plugin_manifest_json(plugin_version)

    seen_slugs: list[str] = []
    rendered_skills: dict[str, str] = {}
    for command in manifest["commands"]:
        slug = command["skill"]
        if slug in rendered_skills:
            continue
        structured, body = _load_skill(skills_source_root, slug)
        rendered_skills[slug] = _render_plugin_skill(structured, body)
        seen_slugs.append(slug)

    effective_components: list[dict[str, str]] = []
    if plugin_overrides is not None:
        if plugin_base_remote_sha is None:
            raise SystemExit(
                "--plugin-base-remote-sha is required when --plugin-overrides is set"
            )
        override_payload = _load_plugin_override_manifest(plugin_overrides)
        rendered_skills, seen_slugs, effective_components = _compose_plugin_skill_overrides(
            rendered_skills, plugin_overrides, override_payload
        )
        mcp_manifest, mcp_components, audit_lines = _compose_plugin_mcp_overrides(
            mcp_manifest,
            plugin_overrides,
            override_payload,
        )
        effective_components.extend(mcp_components)

    for harness, plugin_dir in _PLUGIN_HARNESSES:
        harness_root = plugin_out / harness
        outputs[harness_root / plugin_dir / "plugin.json"] = plugin_manifest_body
        outputs[harness_root / ".mcp.json"] = _render_mcp_servers_json(
            mcp_manifest, harness
        )
        for slug in seen_slugs:
            outputs[harness_root / "skills" / slug / "SKILL.md"] = rendered_skills[slug]
    if plugin_overrides is not None:
        outputs[plugin_out / _PLUGIN_EFFECTIVE_LOCK] = _render_plugin_effective_lock_json(
            plugin_base_remote_sha,
            plugin_out,
            effective_components,
        )
    return outputs, audit_lines


def _extra_plugin_tree_files(plugin_out: Path, outputs: dict[Path, str]) -> list[Path]:
    if not plugin_out.exists():
        return []
    expected = {path.resolve() for path in outputs}
    return sorted(
        path
        for path in plugin_out.rglob("*")
        if path.is_file() and path.resolve() not in expected
    )


def _prune_plugin_tree(plugin_out: Path, outputs: dict[Path, str]) -> None:
    for path in _extra_plugin_tree_files(plugin_out, outputs):
        path.unlink()
    if not plugin_out.exists():
        return
    for path in sorted(plugin_out.rglob("*"), key=lambda item: len(item.parts), reverse=True):
        if not path.is_dir():
            continue
        try:
            path.rmdir()
        except OSError:
            continue


def _emit_plugin_tree(plugin_out: Path, outputs: dict[Path, str]) -> None:
    """Write every plugin-tree file deterministically."""
    _prune_plugin_tree(plugin_out, outputs)
    for path, content in sorted(outputs.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def _check_plugin_outputs(plugin_out: Path, outputs: dict[Path, str]) -> list[str]:
    failures: list[str] = []
    for path, expected in sorted(outputs.items()):
        if not path.exists():
            failures.append(f"missing plugin tree file: {path}")
            continue
        if path.read_text() != expected:
            failures.append(f"plugin tree drift: {path}")
    for path in _extra_plugin_tree_files(plugin_out, outputs):
        failures.append(f"unexpected plugin tree file: {path}")
    return failures


def _run_plugin_mode(args: argparse.Namespace, package_root: Path, manifest: dict) -> int:
    skills_source_root = (
        args.skills_source_root
        or args.claude_skills_root
        or (package_root / "skills")
    )
    mcp_servers_path = args.plugin_mcp_servers or (
        package_root / "config" / "agent-workflows" / "mcp_servers.yaml"
    )
    if args.plugin_out is None:
        raise SystemExit("--mode=plugin requires --plugin-out <dest>")
    mcp_manifest = _load_mcp_servers_manifest(mcp_servers_path)
    outputs, audit_lines = _expected_plugin_outputs(
        manifest,
        mcp_manifest,
        skills_source_root,
        args.plugin_out,
        args.plugin_overrides,
        args.plugin_base_remote_sha,
    )
    stale_components: list[dict[str, object]] = []
    lock_payload = outputs.get(args.plugin_out / _PLUGIN_EFFECTIVE_LOCK)
    if lock_payload is not None:
        try:
            parsed_lock = json.loads(lock_payload)
        except json.JSONDecodeError:
            parsed_lock = {}
        stale_components = [
            entry
            for entry in parsed_lock.get("components", [])
            if isinstance(entry, dict) and entry.get("status") == "stale"
        ]
    if args.check:
        failures = _check_plugin_outputs(args.plugin_out, outputs)
        if stale_components:
            print("Plugin override composition has stale overrides:", file=sys.stderr)
            for entry in stale_components:
                print(
                    "  - stale override: "
                    f"{entry.get('override_path')} "
                    f"(recorded {entry.get('recorded_upstream_digest')} vs current {entry.get('current_base_digest')})",
                    file=sys.stderr,
                )
        if failures:
            print("Plugin tree is out of sync with the canonical inputs:", file=sys.stderr)
            for failure in failures:
                print(f"  - {failure}", file=sys.stderr)
        if failures or stale_components:
            return 1
        print(f"✓ plugin-tree: {len(outputs)} files match canonical inputs.")
        return 0
    _emit_plugin_tree(args.plugin_out, outputs)
    for line in audit_lines:
        print(line)
    if stale_components:
        for entry in stale_components:
            print(
                "warning: stale override preserved: "
                f"{entry.get('override_path')} "
                f"(recorded {entry.get('recorded_upstream_digest')} vs current {entry.get('current_base_digest')})",
                file=sys.stderr,
            )
    print(f"✓ plugin-tree: wrote {len(outputs)} files under {args.plugin_out}.")
    return 0


def main() -> int:
    args = _parse_args()
    manifest = _load_manifest(args.manifest)
    package_root = args.manifest.resolve().parents[2]

    if args.mode == "plugin":
        return _run_plugin_mode(args, package_root, manifest)

    # Source-of-truth: skills/<slug>/{skill.yaml, body.md}.
    # --claude-skills-root is the legacy alias kept for one release.
    skills_source_root = (
        args.skills_source_root
        or args.claude_skills_root
        or (package_root / "skills")
    )

    # Per-agent output paths. --target is sugar for "set every per-agent
    # output to this consumer repo's standard location"; explicit
    # per-agent flags still override.
    target = args.target
    claude_out = args.claude_out or (target / ".claude" / "commands" if target else None)
    claude_skills_out = args.claude_skills_out or (
        target / ".claude" / "skills" if target else None
    )
    prompts_out = args.prompts_out or (target / ".github" / "prompts" if target else None)
    codex_router_out = args.codex_router_out or (
        target / "docs" / "agentic" / "generated" if target else None
    )
    codex_skills_out = args.codex_skills_out or (
        target / ".codex" / "skills" if target else None
    )

    # When invoked without --target and without explicit out paths
    # (e.g. workstate-system source-of-truth context), fall back to
    # package-internal sentinel paths so --check still has something
    # to validate against. Writes will refuse to land here.
    if claude_out is None:
        claude_out = package_root / ".claude" / "commands"
    if prompts_out is None:
        prompts_out = package_root / ".github" / "prompts"
    if codex_router_out is None:
        codex_router_out = package_root / "docs" / "agentic" / "generated"

    outputs = _expected_outputs(
        manifest,
        skills_source_root,
        claude_out,
        prompts_out,
        codex_router_out,
    )
    skill_outputs = _expected_skill_outputs(
        manifest, skills_source_root, claude_skills_out, codex_skills_out
    )

    # repo_root for the codex-router-consumers sync is the target repo
    # if --target was given, otherwise the package root.
    repo_root = target if target is not None else package_root

    if args.check_codex_router_blocks:
        failures = _sync_codex_router_consumers(manifest, repo_root, check=True)
        if failures:
            print(
                "Codex router consumer docs are out of sync with the manifest:",
                file=sys.stderr,
            )
            for failure in failures:
                print(f"  - {failure}", file=sys.stderr)
            return 1
        print("✓ codex-router: consumer docs match the manifest-rendered block.")
        return 0

    if args.check:
        exit_code = _check_outputs(outputs, claude_out, prompts_out, codex_router_out)
        skill_failures = _check_skill_outputs(skill_outputs)
        if skill_failures:
            print(
                "Generated skill files are out of sync with the manifest:",
                file=sys.stderr,
            )
            for failure in skill_failures:
                print(f"  - {failure}", file=sys.stderr)
            exit_code = 1
        return exit_code

    _write_outputs(outputs)
    failures = _sync_codex_router_consumers(manifest, repo_root, check=False)
    if failures:
        raise SystemExit("\n".join(failures))
    _write_skill_files(skill_outputs)
    expected_slugs = {command["skill"] for command in manifest["commands"]}
    _prune_stale_skill_dirs(claude_skills_out, expected_slugs)
    _prune_stale_skill_dirs(codex_skills_out, expected_slugs)
    _prune_legacy_portable_emissions(
        manifest, claude_out, claude_skills_out, codex_skills_out
    )
    total = len(outputs) + len(skill_outputs)
    print(f"✓ agent-workflows: wrote {total} adapter files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
